getodk/central-backend

- lib/model/base.js
- test/model/base.js
- test/model/package.js
* the DatabaseShim is the main harness for testing knex’s database
chaining calls.
* our Model (Base-derived) objects all use dependency injection to
actually receive their database objects to work with. What the
DatabaseShim does is create a mock knex object with all the knex and
Promise methods mocked out for chaining; but instead of actually
performing any database actions, they simply record what they were
called with and move on.
* the Shim itself provides access to these recorded method calls, and
a bunch of convenience getters and assertions for pulling out the
relevant calls and parameters for testing.
* it is a bit of a fine balance between testing the appropriate pieces
of logic for the database calls and over-testing fairly obvious code,
but in general expected behaviour should …
> test #10: add database testing infrastructure; tests and fixes for Base.

- lib/problem.js
- lib/server.js
- lib/util/http.js
* closes #34.
* check request.apiVersion to see the version of the request.
* this could change if eg we’d prefer to actually route based on the
version, in which case we can simply submount services instead.
> new #34: add api version to application route; expose on request obj.

- lib/resources/users.js
- test/api/hooks.js
- test/api/resources/users.js
* orElse(mail(… calls immediately. so use orElseGet instead.
* modify tests so that we're sure the right number of emails are sent.
> bug: password reset no-account branch was not inert.

- lib/model/query/field-keys.js
- test/integration/api/field-keys.js
* ie if the field key no longer has an active session, it goes to the
bottom.
* otherwise it still sorts descending by creation date.
* resolves #75.
> improve+test #75: sort revoked field keys to the bottom of the listing.

- lib/bin/backup.js
- lib/model/instance/audit.js
- lib/model/instance/config.js
- lib/model/migrations/20180501-01-add-configs-timestamp.js
- lib/model/query/audits.js
- lib/model/query/configs.js
- lib/resources/config.js
- lib/task/config.js
- lib/task/google.js
- lib/task/task.js
- package-lock.json
- package.json
- test/integration/api/config.js
- test/integration/task/config.js
- test/integration/task/task.js
So, the present API had some problems.
* The release criteria say that only if no backup has succeeded in three days should the UI show a scary message. But the API only returned the latest result, so this was not possible.
* There was not a lot of information in the audit logging on which backup attempts associated with which backup configuration.
This PR ameliorates this somewhat such that `GET /config/backups` now returns:
```
{ "type": "google", "setAt": "0000-00-00T00:00:00.000Z", "recent": [{ AuditLog }, { AuditLog }] }
```
And for successful backup runs, the AuditLog `details` field now also contains a `configSetAt` key with the `setAt` of the backup config that was used. Sadly, I still don't know how to log this information for failures, since getting the configuration can itself …
> Redo the backups status API a little bit.

- lib/model/instance/form.js
- lib/model/instance/submission.js
- lib/model/migrations/20180515-01-enforce-nonnull-form-version.js
- test/integration/api/forms.js
- test/unit/model/instance/form.js
- test/unit/model/instance/submission.js
* for some reason i was squashing empty strings to nulls for Form
version. but postgres, like most RDBMSs, does not enforce uniqueness
on null values.
* so multiple forms can be uploaded without version values (provided the
old ones are deleted), which is not our intention; these duplicates
should be prevented.
* so instead we squash nulls to empty-string throughout.
* and to cap it off we add a non-null constraint on the Form version
column to be completely sure we haven't missed any cases.
* resolves #94.
> bug #94: correctly enforce form version uniqueness for empty versions.

- docs/api.md
- lib/resources/forms.js
* see ticket for details.
* should probably eventually return the updated object but we'll worry
about that later.
* resolves #92.
> bug #92: should return success object rather than string on PATCH forms.

- lib/resources/users.js
- test/integration/api/users.js
* since we are already exposing email addresses via /users listing, and
only people who can GET /users can GET /users/:id on anyone but
themselves anyway.
> new+test: re-enable GET /users/:id.

- lib/data/json.js
- lib/model/instance/submission.js
- lib/model/query/submissions.js
- lib/outbound/odata.js
- lib/resources/odata.js
- lib/util/stream.js
- test/integration/api/odata.js
- test/integration/api/submissions.js
- test/unit/data/json.js
- test/unit/outbound/odata.js
See commits for more; includes the following structure (and associated schema metadata) in each root level JSON output:
```
__system: {
submissionDate: '<iso date>',
submitterId: '<int>',
submitterName: '<string>'
}
```
> Export submission metadata in OData output

- docs/api.md
- lib/http/middleware.js
- lib/model/instance/session.js
- lib/resources/sessions.js
- lib/util/http.js
- test/integration/api/sessions.js
- test/unit/http/middleware.js
- test/unit/util/http.js
* sets an HttpOnly, Secure only cookie on POST /sessions/new along with
normal login path.
* HttpOnly so no JS access.
* only works over HTTPS even if user agent ignores Secure.
* only works on GET requests.
* clears cookie on DELETE /sessions/:token along with logout path.
* new GET /sessions/restore gets the current cookie and returns its
session information if it is valid.
> new: limited cookie authentication.

- lib/bin/run-server.js
at some point, this existed in the codebase, but it fell out the bottom due to lack of use. now i've re-enabled it and subjected it to quite a beating over the course of two days as part of the benchmarking tests (including not just load but also many restarts) so i feel pretty confident in putting this back in and using it in prod.
> new: restore clustered server capability to run-server script.

- lib/data/schema.js
- lib/model/migrations/20180727-03-add-form-attachments-table.js
- test/unit/data/schema.js
1. If the same filename is seen multiple times in a form xml def _and_ the expected type each time is the same, only return that filename once from `expectedFormAttachments`. (This will make the database happy with these cases.)
2. If some form still has duplicate attachment violations even given this change, don't fail the initial migration, just bail out on supporting attachments for that form.
> Address duplicate form attachments

- docs/api.md
- lib/http/endpoint.js
- test/integration/api/forms.js
- test/integration/api/submissions.js
- test/unit/http/endpoint.js
* it turns out that Collect does not send RFC7231 dates (which only
allow English), it sends dates constructed in that format by..
presumably JodaTime, i haven't looked.
* what this means is that when Collect is set to some other language, it
will send the text names in not-English. this in turn fails the Date
validation check per OpenRosa.
* technically OpenRosa does not specify RFC 7231, it just gives an
example that looks like it. but the HTTP spec itself does specify
this, and the Date header used is the same.
* and the OpenRosa spec doesn't explain, either, that the Date /could/
be in a non-English format.
* either way, the simple solution is to simply not validate the Date
field anymore at all. Central doesn't actually care about it or use it
for anything; it was implemented only to …
> rm+bug #125: remove HTTP Date header validation for OpenRosa.

- lib/data/schema.js
- test/unit/data/schema.js
* or any <bind> node for that instance.
* just needed to filter out <bind> nodes that don't have type=; we only
care about the type information.
* resolves #147.
> bug #147: fix cases where groups/structures have <bind relevant=> nodes.

- README.md
- lib/model/migrations/20181011-make-email-case-insensitive.js
- test/integration/api/sessions.js
* the good news is that postgres offers this natively, so that you don't
have to do 'UPPER('input')=UPPER(email)' all over the place, and so
that the uniqueness constraint accounts for the case-insensitivity.
* the bad news is that it's offered via the CITEXT extension which is
bundled but must be manually enabled.
* the worst news is that non-superusers cannot enable extensions, which
crashes the migration.
* but as far as i know our user /is/ a superuser on docker and on
circleci (which uses docker).
* so those cases aren't issues.
* and i've added a line in the README to manually add the extension at
database creation.
> improve #144: make email addresses case-insensitive everywhere.

- docs/api.md
- lib/model/instance/form.js
- lib/model/instance/submission.js
- lib/model/query/submissions.js
- lib/resources/submissions.js
- test/assertions.js
- test/integration/api/forms.js
- test/integration/api/submissions.js
* this applies to list as well as individual fetch (GET / and GET /:id).
* picked up a bug where Extended Submissions were only accidentally
working; now they actual work.
* resolves #103.
> improve #103: do not return Form or Submission XML unless Extended.

- lib/http/endpoint.js
- test/unit/http/endpoint.js
* otherwise back-to-back requests may not have the intended effect.
* eg, logging in then immediately using the new session token.
* this change means that response formulation no longer occurs within
transaction context, which means we might commit things then fail to
tell the user.
* but i guess this is how most services work.
> bug: need to commit before formulating endpoint response.

- lib/data/attachments.js
- test/integration/api/submissions.js
- test/unit/data/attachments.js
* "media", not "files".
* do not create subfolders per instance.
* resolves #156.
> improve #156: change .csv.zip export dir structure to match briefcase.

- lib/outbound/mail.js
- lib/resources/users.js
- test/integration/api/users.js
#151 Adds email notifications when a user updates their email address or password. When a user changes their email address, the email is sent to the email address which was previously on file.
> improve #151: email notifications for password/email changes

- lib/model/instance/submission.js
- lib/model/migrations/20181230-01-add-device-id-to-submission.js
- lib/resources/submissions.js
- test/integration/api/submissions.js
When a submission is created in the submission endpoint, the device id is now recorded using the deviceID query string property (used by Collect app).
More info: #150
> improve #150: adds storage of device id on submit

- docs/api.md
- lib/data/attachments.js
- lib/data/submission.js
- lib/model/instance/submission-attachment.js
- lib/model/instance/submission.js
- lib/model/migrations/20181219-01-add-submission-update-verb.js
- lib/model/migrations/20181221-01-nullable-submission-blobs.js
- lib/model/package.js
- lib/model/query/submission-attachments.js
- lib/model/query/submissions.js
- lib/resources/odata.js
- lib/resources/submissions.js
- lib/util/promise.js
- lib/util/stream.js
- lib/util/util.js
- test/integration/api/submissions.js
- test/integration/data.js
- test/unit/data/submission.js
- test/unit/util/stream.js
1. adds `POST attachments/:name` and `DELETE attachments/:name`
2. also refactors the entire submission attachment process to look like the form attachment process: expected attachments are determined by the submission xml, and the attachment record exists whether the binary does or not. unknown files are now ignored.
> add RESTful attachment to submissions subresource

- lib/http/endpoint.js
- lib/http/service.js
- lib/model/query/projects.js
- lib/resources/compat.js
- lib/resources/submissions.js
- lib/util/http.js
- test/integration/api/projects.js
- test/unit/http/endpoint.js
* fix a bug where projects extended metadata request would include deleted forms in its form count.
* add some temporary backwards compatibility to version 0.4 for already-configured devices.
* the implementation on this one is quite ugly but it's temporary.
> miscellaneous fixes

- lib/model/instance/project.js
- lib/model/migrations/20190405-01-add-project-archival-flag.js
- lib/model/query/projects.js
- lib/util/db.js
- lib/util/problem.js
- test/integration/api/projects.js
* boolean flag on project. modifiable via PATCH.
* affects sorting on project listing; archived projects sort to the
bottom, still alphabetized.
* false == null.
* also expand the 22P02 error handling to support more than integers,
and genericize the error message to not mention a URL.
> new: add archived flag to project; expand invalidtype db error handling.

- lib/util/problem.js
- test/integration/api/forms.js
- test/unit/util/db.js
* ie if a resource already exists.
> api/improve: use a 409 code rather than 400 on key conflict errors.

- lib/model/instance/actor.js
- test/integration/api/users.js
the background here is:
before we moved to role-based permissioning, there was [a clause in the code](https://github.com/opendatakit/central-backend/blob/be6f88b05b81b839154a3a07d56db0f46e7a7827/lib/model/instance/grant.js#L43) that did exactly this.
when we moved to the role-based version, it was half me not liking that exceptional clause and half me not thinking it through but it got dropped. as noted in the TODO comment now in the code, i've restored the line in code rather than solve it in the database because i think it's simpler and cleaner for now even if i don't like code-based grants when a database ACL system has been established.
on the other hand, this new incarnation is far more limited than the old one; the old one let users do anything at all to their own account; the new …
> bug+test: users should be allowed to view and edit their own profile.

- lib/resources/submissions.js
- test/integration/api/submissions.js
* rather than the default application/json which causes safari to append
.json to the filename.
> bug+test: should send application/zip type with .csv.zip download.

- lib/data/json.js
- test/unit/data/json.js
* at least powerbi appears to interpret a missing field as an error
rather than the lack of a value. so we provide all fields, and provide
a null value.
* hopefully output gzip compression will save us the additional bits.
* closes #206.
> bug #206: odata: provide null field markers vice omitting on no value.

- lib/util/sentry.js
This PR will resolve issue #211 
For sensitive endpoints, request payload will be set to `null` before the event is sent to sentry.
> improve #211: Sanitize pwd change requests sent to sentry

- lib/model/instance/form.js
- lib/model/migrations/20200129-01-cascade-submission-deletes.js
- lib/model/query/forms.js
- lib/model/query/keys.js
- lib/model/query/submission-defs.js
- lib/model/query/submissions.js
- lib/resources/forms.js
- test/integration/api/forms.js
in the previous PR, a lot of homework was done because old draft submissions would lay around (with `draft: false` in the database), and we had to do some extra comparisons to be sure we were only returning _current_ draft submissions.
here we instead hard-delete draft submissions any time a draft is created, published, or deleted. (we have to do created because drafts can be replaced without publishing or deleting them). this means all submissions are current, the only question is whether they are draft or not; so we can simplify all our queries to just check the boolean flag.
part of this work is to fix extended form responses; they were counting all submissions without handling draft/nondraft/olddraft at all. this has been corrected.
> redo how draft submissions are discarded

- lib/model/instance/form.js
- lib/resources/forms.js
- lib/util/db.js
- lib/util/problem.js
- test/integration/api/forms.js
* we weren't getting attachments so the manifest node never appeared.
* also a 404 on this endpoint will always yield a custom message that
carries a different hint on what might be wrong.
> improve: draft formList: fix manifest node, use custom error message.

- lib/outbound/mail.js
- test/integration/api/users.js
* so tokens don't get accidentally truncated in client autolinks.
> improve: explicit <a> tags for links in emails.

- lib/data/json.js
- test/unit/data/json.js
Closes #282 
Clients may add trailing semicolons to the end of geotrace or geoshape values.
> bug: account for possible trailing ; in geotrace and geoshape

- docs/api.md
- lib/http/middleware.js
- lib/http/preprocessors.js
- test/integration/api/app-users.js
- test/integration/api/public-links.js
- test/integration/api/sessions.js
- test/integration/api/submissions.js
- test/unit/http/middleware.js
- test/unit/http/preprocessors.js
> rework path token authentication

- docs/api.md
As discovered at https://forum.getodk.org/t/ideas-and-extensions-for-central-public-links/29499/2, the public links docs didn't include the `token` attribute. While there, I added the structure of user-facing links and changed `/enketo` to `/-`.
> docs: add token attribute to public links

- lib/data/briefcase.js
- package-lock.json
- package.json
- test/integration/api/submissions.js
- test/unit/data/briefcase.js
* this can be a hard bug to reproduce. the number of bytes of csv
produced per row of data, as well as the size of the rows coming from
the database.
* whatever the conditions, the issue is that for whatever reason the csv
stringify stream doesn't always wait to flush out, so it erroneously
reports to the zip archive that it's done.
* if we wrap it in a PassThrough it works perfectly.
* there is probably a different solution that involves patching
csv-stringify, but that's a far more expensive operation than we have
time for rn.
> bug: could sometimes fail to export all repeat rows. depends on chunks.

- lib/model/instance/client-audit.js
- lib/model/instance/submission-attachment.js
- lib/model/query/client-audits.js
- lib/model/query/submission-attachments.js
- lib/resources/submissions.js
- test/integration/api/submissions.js
* on the /submissions.csv.zip endpoint.
* reviewers: ignore whitespace for an easier time.
> bug: need to filter attachments and client audits by the odata filter.

- lib/resources/backup.js
This code is only run if the end of the first chunk is reached, which will happen for a longer-running backup. In that case, we reset `ptr` so that all data after the first chunk is exported.
> Export all keepalive data for a longer-running backup

- lib/task/fs.js
Right now `lib/bin/restore.js` quits with the following error message when restoring a backup downloaded from `/v1/backup`:
```
Required parameter undefined missing.
'keepalive local key'
```
This PR modifies the restore process so that it ignores `keepalive`.
I had trouble writing a test for this change. Ideally, we would test the result of calling `decryptFromArchive()` on a .zip file that contains both encrypted files and a `keepalive` file. `encryptToArchive()` returns a .zip files with encrypted files, but I didn't see an easy way to insert a `keepalive` file into it. Instead, I verified this change as follows:
- I downloaded a .zip file locally using the "Download backup now" button.
- I modified `restore.js` so that it expands the zip into a persistent directory and decrypts …
> Ignore keepalive file when restoring backup

- README.md
- docs/api.md
- lib/data/json.js
- lib/http/endpoint.js
- lib/outbound/odata.js
- lib/util/problem.js
- test/unit/data/json.js
- test/unit/http/endpoint.js
As discussed here https://forum.getodk.org/t/extend-api-to-retrieve-plain-json/32204, $expand is now implemented with "*" as only available option for now.
Additionally, enhanced README.md to create the test database, too.
Related to #84
> new: OData: implement $expand=*

- CONTRIBUTING.md
Changing the link from sign-in to registration, using the same link as
https://docs.getodk.org/docs-tech-guide/.
> docs: update Slack link in contributing guidelines.

- lib/data/client-audits.js
- lib/model/query/client-audits.js
- test/integration/api/submissions.js
This addresses issue #333 and forum comment https://forum.getodk.org/t/update-the-audit-log-structure/31887. Now each row of client audit events contains an extra `uuid` column referring to the unique ID of the corresponding submission.
The new `uuid` column id named that because of the forum post, but it should possibly be named `KEY` or `instanceID` to be more consistent with other exported files.
Turns out, although there's a complicated query in `model/query/client-audits.js` spanning many tables, the `submissions` table with `instanceId` column is already one of the tables active in that big join so this doesn't impact the database performance.
> include instanceId in client audit csv export

- docs/api.md
- lib/model/frames/form.js
- lib/model/query/forms.js
- test/integration/api/forms.js
- test/integration/api/projects.js
This resolves an issue brought up in [getodk/central#29](https://github.com/getodk/central/issues/29#issuecomment-800617039) and described in the [Central block 12 release criteria](https://docs.google.com/document/d/10uUU1nlIFRPJmtTr-zukKDXFY0flFAw_kuvDXZqLgxg).
There are two main changes:
**1. Update form name based on latest XForm title when new draft is uploaded**
Previously, Central's form display name was read once from the initial form's title. Now, the form display name will update if a user uploads a new version of a form with a different title. More specifically, any time a user uploads a new draft, the form name/title will update. 
Changing the name here (vs. on form publication or some other place) seemed like the best option, especially when working with forms only in draft …
> Keeping Form name/title consistent with XForm title

- lib/bin/backup.js
- lib/task/google.js
I made this change after encountering this error:
```
TypeError: Unexpected value expression.
at sql (/usr/odk/node_modules/slonik/dist/factories/createSqlTag.js:45:23)
at /usr/odk/lib/model/query/configs.js:19:49
at module.<computed> (/usr/odk/lib/model/container.js:30:33)
at /usr/odk/lib/task/task.js:51:44
at persistCredentials (/usr/odk/lib/task/google.js:32:5)
at /usr/odk/lib/bin/backup.js:44:5
at processTicksAndRejections (internal/process/task_queues.js:85:5)
```
This PR calls `JSON.stringify()` on an object before passing it to `Configs.set()`, which is what seems to be done elsewhere.
I also await `persistCredentials()`, since I think that returns a promise.
> bug: stringify backups.google credentials before setting them

- docs/api.md
As mentioned in #339, and according to the [backend code](https://github.com/getodk/central-backend/blob/master/lib/resources/submissions.js#L254) the parameter to exclude media attachments is `attachments`, not `media`. This patch updates the three mentions of this parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getodk/central-backend/340)
> Fix #339: submission export param is attachments

- lib/formats/odata.js
- test/integration/api/odata.js
> bug #337: $top=0 would accidentally give ALL rows.

- lib/data/odata.js
- lib/formats/odata.js
- lib/resources/odata.js
- test/integration/api/odata.js
The base branch of this PR is `issa/1.2-misc`. However, the parent commit is 79f7863835eb1cb60ada0691c727b0dafe8a8bba on `master`, so this PR could also be merged into `master`.
The goal of this PR is to update the OData .../Submissions(':instanceId') endpoint so that the `uuid:` prefix of an instance ID may be encoded. The encoding will be preserved in the OData URLs that the endpoint returns: both the form ID and the instance ID will remain encoded. Not all instance IDs have a `uuid:` prefix, but some do. This PR intersects with getodk/central-frontend#429, which adds a submission detail page that uses this endpoint.
With these changes, I think the endpoint may also be pretty close to being able to accept an instance ID that is not a UUID.
CircleCI is failing, but I think it's also …
> bug: decode/encode URLs for OData .../Submissions(':id') endpoints.

- lib/model/frames/form.js
- lib/resources/forms.js
- test/integration/api/forms.js
- test/unit/model/frames/form.js
There was an issue with database migrations where the migration to backfill form def names used `Form.fromXml`, which was checking for `.xml` and `.xslx` extensions inside formIDs and throwing an error. This was causing the whole migration to fail, which was no good! The original purpose of this formID check was to prevent forms with this formID pattern from even being uploaded.
This extension check has now been moved from `fromXml` to a `getPartial()` method used in the form ingestion resource.
> Move formId extension check from Form.fromXml to Form ingestion resource (migration patch)

- docs/api.md
- lib/data/submission.js
- lib/resources/submissions.js
- test/integration/api/submissions.js
- test/unit/data/submission.js
I've added an API endpoint for fetching the diffs/deltas/edits between submission versions given the root/original Instance ID:
`/v1/projects/{projectId}/forms/{xmlFormId}/submissions/{rootInstanceId}/diffs`
It returns an object of arrays of edits. So a name + age form with two separate edits
a) name: "Gordin" -> "Gordon"
b) age: 22 -> 12
would look like:
```
{
"uuid:8fd73636-1d02-4162-877a-97bed07436bb":[
{
"new":"Gordon",
"old":"Gordin",
"path":[
"name"
]
},
{
"new":"12",
"old":"22",
"path":[
"age"
]
},
{
"new":"uuid:8fd73636-1d02-4162-877a-97bed07436bb",
"old":"uuid:89d2c893-e3c2-431f-a2d4-2ac1595c7ed2",
"path":[
"meta",
"instanceID"
]
},
{
"new":"uuid:89d2c893-e3c2-431f-a2d4-2ac1595c7ed2",
"old":null,
"path":[
"meta",
"deprecatedID"
]
}
]
}
```
Edits that are within repeats have their …
> Calculate diffs between versions of XML submissions

- lib/external/sentry.js
- test/unit/external/sanitize-sentry.js
Closes #347. This issue requested filtering out the request body for a number of endpoints. These are endpoints that might contain emails and other sensitive information. (Note that extra sensitive information, such as passwords, was already filtered by Sentry, but with this change, that information is erased before it is even sent to Sentry.) The issue also requested filtering out the query parameters of certain endpoints.
* /sessions
* /users
* /users/:id (covered by endpoint regex `/users`)
* /users/reset/initiate
* /projects/:id/key
* /config/backups/initiate
* /backup (at least the POST version)
* any more...?
Changes:
1. I've expanded the list of sensitive endpoints, and any matching endpoint, regardless of what kind of GET/POST/PUT request it is, will have both it's request body …
> Implement additional filtering for Sentry

- lib/task/reap-sessions.js
- test/integration/task/reap-sessions.js
Making a small change to the `reapSessions` task. (I ran the `reapSessions` task as part of debugging something unrelated and noticed that the task threw an error.)
> bug: fix reference to query module in reapSessions task.

- Makefile
- README.md
Hey folks,
I've tried setting up a development instance for the first time and ran into some problems, which turned out to be mainly Node.js version related. ODK Central doesn't seem to currently play well with Node.js >= 15, where most of the integration tests fail with
````
TypeError: Cannot read property 'authorization' of undefined
````
I also tried to provide an easier way of starting a local postgres instance, as close as possible to what currently happens in CircleCI. Let me know if there's anything that can be improved.
Thanks for building ODK Central and have a great weekend 🎉
> Improve setup instructions / provide a make rule for starting a Postgres instance

- lib/data/schema.js
This test was failing because `basename` seemed to be an array instead of a string, e.g. `[ 'fileone' ]`
```
1) form schema
expectedFormAttachments
should detect primitive search() appearances:
TypeError: basename.endsWith is not a function
at getSearchAppearance (lib/data/schema.js:284:27
```
> Fix to failing test

- lib/model/query/audits.js
Making this change so that `analytics` audit log entries are no longer shown in the Frontend audit log. (These audit log entries will be shown on the "Usage Reporting" page instead.)
> improve: exclude analytics audit log entries from nonverbose query.

- lib/model/migrations/20210927-01-revert-disallow-structure-downcast.js
- test/integration/api/forms.js
This commit effectively reverts 4d5619cdd52f5a734ee255fb607832ce59a1bc02.
> bug: temporarily allow structure/repeat downcast to string.

- lib/bin/run-server.js
Making this change because we've encountered errors in Sentry whose stack trace ends before it indicates what line in Central triggered the error. Example: https://sentry.io/organizations/getodk/issues/2703129106/?project=5724763
> improve: increase stack trace limit.

- lib/data/client-audits.js
- test/integration/api/submissions.js
* also fix the name of this other option that i guess is now or always
was (or maybe it likes both?) underscores and not camels.
> bug: fix csv parsing options to allow ragged line lengths.

- lib/model/knexfile.js
We want to be able to manage Knex migrations from the command line: that will facilitate troubleshooting when a migration fails in production and will also aid local development. In particular, we want to be able to list completed and pending migrations, and we want to be able to run one migration at a time.
We thought about writing our own CLI, but I think we can actually benefit from the built-in Knex [migration CLI](https://knexjs.org/#Migrations-CLI). The Knex CLI is not easy to set up, but once it's set up, it seems to work nicely. The output is clear, and in contrast to the JavaScript API, the CLI automatically outputs the stack trace if there is a migration failure. There is also a `--debug` flag that seems potentially useful. The CLI also allows you to run a specific migration. …
> improve: add knexfile.js for Knex migration CLI.

- lib/model/frames/form.js
- lib/model/migrations/20211117-01-add-form-restore-verb.js
- lib/model/query/audits.js
- lib/model/query/forms.js
- lib/resources/forms.js
- lib/util/db.js
- test/integration/api/forms.js
- test/integration/api/projects.js
This exposes two new endpoints:
1. `/projects/:projectId/deletedForms` that fetches list of deleted forms for display in the frontend (in a trash section below the rest of a project's forms). All the same info about a form is there as well as an additional `deletedAt` field.
2. `/projects/:projectId/forms/:id/restore` that restores a soft-deleted form with a given (numeric) form id.
There are two quirks of this `restore` endpoint:
1. While you can (soft-)delete a form and then make a new one with the same `xmlFormId`, you can't restore the deleted form while an active form of the same `xmlFormId` exists. This will be prevented and explained in both the backend API and the frontend.
~2. It's possible to have multiple deleted forms with the same `xmlFormId`, but different integer form ids …
> Delete API that fetches list of trashed forms and lets trashed forms be restored

- lib/model/migrations/20210423-01-add-name-to-form-def.js
A migration is being killed in rare cases. I tried to patch the migration's JavaScript in #429, but ran into issues. This PR tries to fix the issue by taking a different approach, replacing the JavaScript with a single Postgres statement. That Postgres statement makes use of the Postgres `xml` data type. I tried this PR on the problem server, and with it, the migration was able to complete (after about 30 seconds). 🎉 It seems that Postgres is better able to manage the resources around parsing the relatively large XForms on the server.
I'll also add comments about specific lines below.
References:
https://www.postgresql.org/docs/9.6/datatype-xml.html
https://www.postgresql.org/docs/9.6/functions-xml.html
> bug: prevent migration from being killed by using Postgres xml type.

- lib/model/knexfile.js
Knex documents the `DEBUG` environment variable under its FAQ: https://knexjs.org/#faq. I found this variable helpful while working on #429 and #430, because it makes it easy to view the queries being run (along with their bindings!). Just adding a comment so that we remember this variable the next time we use the Knex migration CLI.
> noop: add comment about using DEBUG variable with Knex migration CLI.

- config/default.json
- lib/model/query/analytics.js
- lib/task/analytics.js
- test/integration/other/analytics-queries.js
issa noticed that the counts for number of viewers and number of submissions in edited state was mysteriously always zero. Turns out I wasn't handing the data returned from the query correctly.
> Fix to populating project viewer and edited submission counts

- lib/util/promise.js
- lib/worker/worker.js
- test/integration/worker/worker.js
* one try/catch we didn't have before, around checker invocation.
* one .catch() we didn't have before, around checker promise result.
* watchdog timer which kicks the loop if it looks stale.
> improve: worker resiliency, hopefully.

- lib/data/briefcase.js
- lib/data/odata.js
- lib/formats/odata.js
- lib/model/frames/submission.js
- lib/model/migrations/20211109-01-add-user-agent-to-submissions.js
- lib/model/migrations/20211114-01-flag-initial-submission-def.js
- lib/model/query/submissions.js
- lib/resources/submissions.js
- test/assertions.js
- test/integration/api/odata.js
- test/integration/api/submissions.js
- test/integration/other/encryption.js
- test/unit/data/briefcase.js
- test/unit/data/odata.js
- test/unit/formats/odata.js
the goal here is to do the following:
1. return an extra `FormVersion`/`formVersion` field on csv/odata export. this field reflects only the original "root" version of a submission, it does not update if the submission is edited.
2. return an extra `formVersion` field on extended submission version request. ditto it's the root version.
3. track and return `userAgent` for each submission version.
4. track and return `deviceId` for each submission version.
this pr does _not_ deprecate the existing `deviceId` on the _logical_ submission, which will also always reflect the initial submission. it only adds an _additional_ `deviceId` to version requests.
this pr does _not_ add `userAgent` to submission logical requests. maybe it should.
> track and return more of: formVersion, deviceId, userAgent

- lib/model/frames.js
- lib/model/migrations/20210423-01-add-name-to-form-def.js
- lib/model/migrations/20211117-01-add-form-restore-verb.js
- lib/model/migrations/20211129-01-add-purged-details-to-actees.js
- lib/model/query/audits.js
- lib/model/query/forms.js
- test/integration/api/audits.js
This PR adds purged information fields (`purgedAt`, `purgedName`, and `details`) to the Actees table. 
* `purgedAt` is when the actee was purged
* `purgedName` is a name field to use anywhere this actee is expected to have a name, and likely came from the original Actee
* `details` can store in JSON any other infromation about the actee that needs to be kept around (e.g. the project and form id of a purged form)
It also exposes the purged information through the Audit log API for actees that no longer exist in their original tables. 
Still to do:
(Note: I split PR #431 into more manageable PRs, though now there is a specific order for merging them.)
> Add purged info (name, purged date, details) to actees table

- lib/bin/purge-forms.js
- lib/task/purge.js
- test/integration/task/purge.js
This is a command line tool for purging forms that a daily cron job will use. It can also be used to force purge specific forms.
```
$ node lib/bin/purge-forms.js --help
Usage:
purge-forms.js [OPTIONS] [ARGS]
Options:
-f, --force BOOL       Force any soft-deleted form to be purged right away.
-i, --formId NUMBER   Purge a specific form based on its id.
-h, --help             Display help and usage details
```
(Originally part of PR #431.)
> Task and command line tool for purging forms

- lib/http/service.js
For a project with 1,500 forms and 14 app users, an attempt to update app user access resulted in a 500 error. From the log:
```
ClientError [PayloadTooLargeError]: request entity too large
at readStream (/usr/odk/node_modules/raw-body/index.js:155:17)
at getRawBody (/usr/odk/node_modules/raw-body/index.js:108:12)
at read (/usr/odk/node_modules/body-parser/lib/read.js:77:3)
at jsonParser (/usr/odk/node_modules/body-parser/lib/types/json.js:134:5)
at Layer.handle [as handle_request] (/usr/odk/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/usr/odk/node_modules/express/lib/router/index.js:317:13)
at /usr/odk/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/usr/odk/node_modules/express/lib/router/index.js:335:12)
at next …
```
> improve: increase bodyParser limit so that large payload is accepted.

- lib/bin/purge-forms.js
- lib/model/migrations/20220121-01-form-cascade-delete.js
- lib/model/migrations/20220121-02-purge-deleted-forms.js
- lib/model/query/audits.js
- lib/model/query/blobs.js
- lib/model/query/forms.js
- lib/task/purge.js
- test/integration/api/audits.js
- test/integration/other/form-purging.js
- test/integration/other/migrations.js
- test/integration/task/purge.js
This PR enables the purging of soft-deleted forms and their associated resources (definitions, versions, submissions, attachments, comments, etc.)
Purging follows these steps:
- Redact notes about forms from the audit table that reference a form (includes one kind of comment on a submission)
- Log the purge in the audit log with actor not set
- Update actees table for the specific form to leave some useful information behind
- Delete the forms and their resources from the database
- Purge unattached blobs
Purging of a form will happen a few different ways:
- via a script run daily by a cron job that will purge forms deleted more than 30 days ago
- the migration described below that purges all old deleted forms
- when a form with only a draft is abandoned
This PR has a number of …
> Purge forms and all related resources

- lib/model/migrations/20220121-02-purge-deleted-forms.js
- lib/model/query/blobs.js
- lib/model/query/forms.js
- test/integration/other/blobs.js
- test/integration/other/form-purging.js
- test/integration/other/migrations.js
This error came up while applying the form purging migration on the QA server on Feb 2, 2022, and it turns out to be an issue in the regular blob purging SQL as well. That code checks for blobs with no references and tries to delete them, but it wasn't considering the reference to `xlsBlobId` in the `form_defs` table, so it was trying (and failing) to delete blobs that shouldn't have been deleted. 
service_1             | migration file "20220121-02-purge-deleted-forms.js" failed
service_1             | migration failed with error:
service_1             | delete from blobs
service_1             |   using blobs as b
service_1             |   left join client_audits as ca on ca."blobId" = b.id
service_1             |   left join submission_attachments as sa on sa."blobId" = b.id
service_1 …
> Addressing xlsBlobId issue in form and blob purging

- lib/model/migrations/20220209-01-purge-unneeded-drafts.js
- lib/model/query/forms.js
- lib/resources/forms.js
- lib/resources/projects.js
- test/integration/api/forms/draft.js
- test/integration/api/projects.js
- test/integration/other/migrations.js
If a user does something that makes a particular Draft Form unneeded, it should be immediately hard-deleted from the database.
There are three scenarios for this:
1. Uploading a new Draft while there is currently a draft, which replaces the existing one
2. Enabling Project Managed Encryption, which replaces all existing drafts
3. Deleting a draft directly (only when there is a published version already on the form)
> Purge unneeded form draft definitions

- lib/model/query/projects.js
- lib/model/query/users.js
- lib/util/problem.js
- test/integration/api/forms/forms.js
- test/integration/api/projects.js
- test/integration/api/users.js
- test/integration/other/analytics-queries.js
- test/integration/task/account.js
Complain if a user tries to set a password that is too short (<10 chars) on several API endpoints and in the central CLI. Includes creating and updating a user password and specifying a passphrase when enabling managed encryption on a project.
> Disallow passwords that are too short

- config/default.json
- lib/data/analytics.js
- lib/model/query/analytics.js
- test/integration/other/analytics-queries.js
Adds 5 new metrics:
1. number of total archived projects (no recent vs. total, just how many there are at the time of computing analytics)
2. number of unique project managers (if a user is a manager on multiple projects, this is only counted once. if a user has two different roles on different projects, each type of role is counted.)
3. same as above but for project viewers
4. same as above but for data collectors
5. number of reused form ids: will report how many active forms use an (`xmlFormid`) ID that was ever deleted or purged in the past.
* this will give us a sense of whether people are reusing form IDs at all (which will they have to use form deletion to do).
> New metrics: archived projects, unique roles

- lib/model/container.js
- lib/model/query/forms.js
- lib/model/query/submissions.js
- lib/worker/submission.js
- test/integration/api/submissions.js
* we now just get the fields for the form def in question rather than
try to merge them all. we did the latter for paranoia+compatibility
with deletedFields = true.
* but theoretically nobody can be filling out data their form version
doesn't ask for, so it should cover all the values in the instance.
> bug: fix splitSelectMultiples for draft submissions.

- Makefile
- lib/model/migrate.js
Adds a helper function for checking for pending migrations that returns an error exit code (1) if there are any pending migrations. This is used to prevent running the server after automatically applying migrations if there happened to be a problem with the migrations. See issues #461 and https://github.com/getodk/central/issues/258. 
This check has been added to the Makefile so the dev server won't run if there is a problem with the migrations, but it also needs to be used in `start-odk.sh` of the main central repo.
Here's an example non-make script (similar to `start-odk.sh`) that will exit before starting the server if the migration check fails:
#!/bin/sh
echo "pretending to work like start-odk.sh in the main central repo"
node -e 'const { withDatabase, migrate } = …
> Check for pending migrations before running server

- lib/model/query/submissions.js
- test/integration/api/submissions.js
This PR addresses an error seen on [Sentry](https://sentry.io/organizations/getodk/issues/2703129106/?environment=production):
```
error: missing FROM-clause entry for table "submissions"
```
The issue is that the `odataFilter()` function references a table named `submissions`, which means that a query that uses `odataFilter()` must have a table or subquery named `submissions`. However, `Submissions.getSelectMultipleValuesForExport()` does not: the subquery there is named `subs`.
I considered a few different solutions, but opted simply for renaming `subs` to `submissions`. That pattern is used in other queries in the `Submissions`, `SubmissionAttachments`, and `ClientAudits` query modules.
I also did a quick check of other queries that use `odataFilter()`. All seem to have a table or …
> bug: allow user to both splitSelectMultiples and $filter.

- lib/model/migrations/20181206-01-add-projects.js
- lib/model/migrations/20181212-01-add-roles.js
- test/integration/fixtures/01-users.js
- test/integration/other/migrations.js
I wanted to give this a shot... of changing the migrations that create default projects. Default projects get created in an old migration `20181206-01-add-projects.js` and removing that behavior from the migration in the first place seemed cleaner than trying to undo that behavior later by trying to remove the default project or something else more risky.
It turned out to be a bit more complicated than that, though.
1) default project creation should still happen in the case that forms exist (without projects) at the time of running the migration.
2) a later roles migration `20181212-01-add-roles.js` assumes that a project exists.
3) the text fixture data assumes that a default project exists.
I think I addressed these three issues and tested them (with migration tests that don't use any …
> Do not automatically create a Default Project

- docs/api.md
- lib/model/frames/form.js
- lib/model/query/forms.js
- lib/model/query/projects.js
- lib/resources/projects.js
- test/assertions.js
- test/integration/api/forms/list.js
- test/integration/api/projects.js
This PR is to be used by the frontend for the new Project list page (the Central homepage) in Block 15, where forms and key details about each form are shown on that page.
This backend PR makes two key changes:
1. It extends what an "Extended" Form is to also include counts of Submissions in specific review states, such as 'edited', 'hasIssues', and 'received' (the default state for new Submissions)
2. It adds a query parameter `?forms=true` to the Project listing API call to get a list of Forms (extended with the fields described above) associated with each project that are visible to the authenticated Actor. 
- Actors that are admins or managers of Projects will be able to see all the Forms of a Project including drafts, while Actors who are data collectors will only be able to see the …
> In-depth project + form queries

- lib/formats/mail.js
- lib/resources/users.js
- lib/util/problem.js
- test/integration/api/users.js
- Updated `/users/reset/initiate` API such that it does not send any email if no account is found and returns 404
- Updated integration test to validate the change
- Performed manual testing to see how error appears on UI
> improve #468: no send email if no account exists

- lib/external/slonik.js
- lib/util/db.js
- test/unit/util/db.js
This PR adds the ability to configure `maximumPoolSize` for Slonik. See #476 for more on why it could be useful to change the pool size. We originally planned to set `maximumPoolSize` to a constant, but ultimately decided to make it configurable. With this PR, the user can specify `maximumPoolSize` in their database config; it defaults to 10. We use the database config to connect to both Slonik and Knex, but we only need to use `maximumPoolSize` with Slonik: Knex has its own approach to pooling. That means that part of the work of this PR is forwarding `maximumPoolSize` on to Slonik but not Knex.
> improve: add ability to configure maximumPoolSize.

- lib/model/frames.js
- lib/model/query/projects.js
- test/integration/api/projects.js
The verbs (permissions) for a given user on each individual project are needed to construct links in the project list frontend page. (E.g. project viewer form links go straight to a form's submission page, and data collector links should either be disabled or go directly to enketo.) 
Previously, the project list query for this endpoint used an auth check to hide draft forms for certain levels of users, and that same auth query was able to be used to get the project verbs as well.
Additionally, there is a change that if a non-extended project list is requested, data (like the form count `forms` and `lastSubmission` date) that can be calculated by the form list will be automatically filled in.
> Change to project list query to get verbs when also getting form lists

- docs/api.md
- test/integration/api/projects.js
Added 1.5 change log to API docs...
But as I was writing about the new description field, realized that while the `PUT` endpoint is tested, the more basic Project endpoints didn't seem to have description-related tests.
> Updated changelog for block 15 and added missing tests

- README.md
Without this, I see the following error when running `make test`:
```bash
$ make test
env BCRYPT=no node node_modules/mocha/bin/mocha --recursive --exit
migration file "20181011-make-email-case-insensitive.js" failed
migration failed with error: create extension if not exists CITEXT - permission denied to create extension "citext"
1) "before all" hook: initialize in "{root}"
0 passing (548ms)
1 failing
1) "before all" hook: initialize in "{root}":
error: create extension if not exists CITEXT - permission denied to create extension "citext"
at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
at Socket.<anonymous> …
```
> README: add extra step to db setup instructions

- .gitignore
- Makefile
docs: https://eslint.org/docs/latest/user-guide/command-line-interface#--cache
This should speed up `make lint`, and any targets which depend on it (...which seems to be none of them!)
```
$ time make lint
node node_modules/.bin/eslint lib
real	0m5.331s
user	0m7.761s
sys	0m0.229s
$ time make lint
node node_modules/.bin/eslint lib
real	0m5.254s
user	0m7.701s
sys	0m0.212s
$ time make lint
node node_modules/.bin/eslint lib
real	0m5.250s
user	0m7.683s
sys	0m0.216s
```
Note that on the first run, cache will need to be built.
```
$ time make lint
node node_modules/.bin/eslint --cache lib
real	0m5.531s
user	0m7.962s
sys	0m0.246s
$ time make lint
node node_modules/.bin/eslint --cache lib
real	0m0.598s
user	0m0.657s
sys	0m0.049s
$ time make lint
node node_modules/.bin/eslint --cache lib
real …
```
> Makefile: use eslint cache

- Makefile
I think `lint` should depend on `node_modules` as the `eslint` binary is inside the `node_modules` directory.
> Makefile: make lint depend on node_modules

- .circleci/config.yml
Ref https://github.com/getodk/central/blob/master/service.dockerfile#L1
Should tests be run against the same version used in production?
> Circleci node version

- Makefile
If I've understood correctly, this means that a change in `package.json` should trigger a re-run of `make node_modules` on the next invocation of `make`.
This should be helpful e.g. when switching to a branch with different dependencies.
> Makefile: make node_modules depend on package.json

- Makefile
As per https://github.com/getodk/central-backend/pull/497#discussion_r906957505, I think all the `make` targets except for `node_modules` should be listed as phony.
> Makefile: add non-file-based targets to .PHONY list

- package.json
`npm` re-orders these every time a dev dependency is added or removed.  Making the change permanently would save a bit of fiddling when changing dependencies.
> package.json: order dev dependencies alphabetically

- Makefile
For me this knocks 5-6 seconds off every re-run of `make test`, `make run` etc.
> make: don't re-run `npm install` unnecessarily

- lib/worker/worker.js
It looks like this code should be skipping locked rows, as in its current form it looks like it falls prey to this:
> If two are started at exactly the same moment, the subSELECTs for each will be processed first. (It’s not that simple, but we can pretend for this purpose. Don’t rely on subqueries executing in any particular order for correctness). Each one scans for a row with [supplied `WHERE` query]. Both find the same row and attempt to lock it. One succeeds, one waits on the other one’s lock.
https://www.2ndquadrant.com/en/blog/what-is-select-skip-locked-for-in-postgresql-9-5/
> worker: prevent blocking on audit table

- lib/util/db.js
Closes #479 
@matthew-white I can't see any concerns about double-resolution/rejection of the promises in either [`slonik` `23.6.0`](https://github.com/gajus/slonik/blob/v23.6.0/src/connectionMethods/stream.ts#L44-L79) or [`slonik` `master`](https://github.com/gajus/slonik/blob/master/src/connectionMethods/stream.ts#L35-L80)
> Handle ConnectionError thrown by Slonik stream()

- lib/bin/.eslintrc.js
- lib/bin/check-migrations.js
- lib/bin/run-migrations.js
Closes #509
Example
```shell
$ make migrations 2>&1
node lib/bin/enforce-node-version.js
node lib/bin/run-migrations.js
Error: The migration directory is corrupt, the following files are missing: 20220121-01-form-cascade-delete.js
make: *** [Makefile:15: migrations] Error 1
```
> migrations: handle async errors in scripts

- lib/bin/enforce-node-version.js
Ignores lint violation:
```
lib/bin/enforce-node-version.js
1:16  error  'semver' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
```
An alternative fix might be to move `enforce-node-version.js` to a directory specific to dev-only scripts.
> enforce-node-version: ignore lint violation

- .eslintrc.json
- Makefile
Closes #505
I have disabled 3 more eslint rules in this PR because these rules are currently violated on `master`.  If the violations need fixing, I'd suggest doing this separately.
> Include lint in make test & test-full targets

- test/integration/setup.js
Closes #499
This will fail the whole suite fast if `initialize()` times out in a single test.  IMO this is helpful, as otherwise the state of the database is unpredictable for subsequent tests.
Example failure:
```
1 failing
1) "before each" hook for "should reject forms created while project managed encryption is being enabled @slow":
Error: Failed to reinitalize after previous test: 'managed encryption lock management should reject keyless forms in keyed projects @slow'.  You may need to increase your mocha timeout.
at Context.<anonymous> (test/integration/setup.js:80:29)
at processImmediate (internal/timers.js:464:21)
```
> move test reinit to mocha's after hooks

- lib/model/frames/form.js
- lib/model/query/comments.js
- lib/util/util.js
- package-lock.json
- test/integration/api/comments.js
- test/integration/api/forms/list.js
- test/unit/model/frames/form.js
- test/unit/util/util.js
Closes #478 
I have decoded only title before saving it in database
Created unit tests
Manually tested in ODK Collect and Enketo to ensure that change is not breaking functionality there
I could have decoded the title in GET APIs after retrieving the data from DB but there are few of them. 
Other option was to change the `text()` function but I am afraid of ripple effect it might create across the application
> bug #478: decode html entities in form title

- lib/data/schema.js
- lib/model/query/forms.js
- lib/util/problem.js
- test/data/xml.js
- test/integration/api/forms/entity.js
- test/unit/data/schema.js
Makes progress on entity-based data collection!
This PR focuses on validating the `<entity>` element (defined in a [new Form spec](https://docs.google.com/document/d/1-O_wT0JZZFaWvzHl_krrzERJcnrdGMKP55ZZ_hxV0gU/edit#)) of Form XML as it is uploaded, and extracting the dataset name. 
Tests.
I experimented with some other things in this PR #517 that I'm going to close.
I first tried a separate XML parse pass to extract entity information, just to get a feel for how it would work. This new PR responds to some code suggestions on the previous PR. I wasn't yet clear on when or where this code would run when a form was uploaded, and we discussed how maybe the entity extraction should happen during an existing form parsing pass and not on its own.
I tried incorporating the entity-extraction in …
> Parse Form XML to get dataset name and validate entity element

- Makefile
Some of the makefile commands aren't working on some machines. This PR uses npx in the makefile so that those commands will work on all machines.
`make lint` and `make test` now run on my machine.
See the [commit message](https://github.com/getodk/central-backend/pull/579/commits/42d799a284171e543971c97328cd042e07f2e414) for related notes. Another approach would have been to revert #524. However, I think #524 provided a nice improvement in the readability of the makefile, so I didn't want to revert it entirely.
Not user-facing.
No changes required.
> Use npx in makefile

- lib/model/frames/form.js
- lib/model/migrations/20220803-01-create-entities-schema.js
- lib/model/migrations/20220830-01-create-dataset_def.js
- lib/model/migrations/20220830-01-create-dataset_form_def.js
- lib/model/query/datasets.js
- lib/model/query/forms.js
- test/integration/api/forms/datasets.js
- test/integration/model/query/dataset.js
Added dataset_form_defs table that maintains relationship between datasets and form definitions
Added `entityRelated` flag in /forms/:id API, this flag will help frontend to know which forms has associated dataset i.e. it creates, updates or delete entities
Updated integration tests
I could have used ds_property_fields table to check if there's a mapping for a given form definition but that would not work for those forms which are related to a dataset without creating any properties.
GET form APIs now return `entityRelated` flag, ensure frontend doesn't break with this new flag
next PR
- [NA] verified that any code from external sources are properly credited in comments
> new: Added hasDataset field on GET extended form

- lib/util/db.js
- package-lock.json
- package.json
- test/integration/other/db-stream.js
> Minimal slonik patch for closing stream queries (release)

- lib/http/service.js
- lib/model/query/datasets.js
- lib/resources/datasets.js
- lib/resources/projects.js
- test/integration/api/datasets.js
- test/integration/api/projects.js
Created new API that returns all datasets of a given project.
Endpoint: `/v1/projects/id/datasets`
Response contains only published datasets, by published I mean the corresponding form has been published
hmmm
None
Will do it in a separate PR
- [NA] verified that any code from external sources are properly credited in comments
> new: API GET /projects/id/datasets

- test/integration/other/migrations.js
Making a change that I [noticed](https://github.com/getodk/central-backend/pull/603#discussion_r966651171) while working on #603. See the commit messages for additional notes.
> Do not reuse database connection to drop database in migration tests

- lib/bin/check-open-db-queries.js
This could be added at the end of the benchmark to confirm there are no hanging queries.
> Add script: check-open-db-queries

- .circleci/config.yml
- Makefile
- lib/bin/check-file-headers.js
Originally written in https://github.com/getodk/central-backend/pull/612, to avoid updating the check-file-headers ignore list with benchmarker `node_mdoules` directory.
Simplify diff by ignoring whitespace: https://github.com/getodk/central-backend/pull/619/files?w=1
> check-file-headers: use git ls-files to simplify ignore list

- lib/model/query/datasets.js
- lib/resources/datasets.js
- lib/resources/forms.js
- lib/util/db.js
- test/integration/api/forms/datasets.js
Added a new API that return dataset information for a draft form
Endpoint: GET /v1/projects/1/forms/formXmlId/draft/dataset 
Returns an array of all the datasets and their properties that will be created by publishing the given draft form. If the dataset is already there then `properties` field will contained only properties delta i.e. only properties that will be created by publishing the given draft form. Response also returns `datasetStatus` ; possible values are 1) `Draft` means dataset will be created 2) `Published` means dataset is already there and given properties will be added.
This API will be consumed by frontend to display dialog box when user is publishing a draft form that has entityRelated definition.
Alternative was to return current and future state of …
> new: API Get form/formXmlId/draft/dataset

- lib/worker/worker.js
Not sure if we use server_name else where, but I checked central and central-frontend and didn't see it.
> server name not needed now that user has hostname information.

- benchmarker/scripts/ci-benchmark
Streams should time out after 2 minutes of inactivity, so we should wait for that before deciding if there are unterminated/hanging connections left open after requests have been served.
> ci-benchmark: add final timeout for stream queries

- lib/model/frame.js
- lib/resources/forms.js
- lib/resources/odata.js
- lib/resources/submissions.js
- lib/util/db.js
Code Refactor: moved ensureDef to util/db.js as ensureFormDef to eliminate code duplication
NA
NA
NA
> improve: move ensureDef to util/db.js to eliminate code duplication

- .circleci/config.yml
- .github/workflows/benchmarker.yml
- Makefile
- benchmarker/scripts/ci-benchmark
- package-lock.json
- package.json
- test/integration/other/db-stream.js
Closes #482
Closes #485 
Closes #565
Incorporates backported fixes:
* https://github.com/gajus/slonik/pull/360
* https://github.com/gajus/slonik/pull/414
* https://github.com/gajus/slonik/pull/420
> Patch slonik to close streams more reliably

- lib/external/sentry.js
This PR sets [Sentry tags](https://docs.sentry.io/platforms/node/enriching-events/tags/) that are specified in an environment variable named `SENTRY_TAGS`. The approach is generic — any sort of tags could be set — but it was developed as part of getodk/central#317 in order to pass Central version information to Sentry. Together with getodk/central#317, this PR closes #547.
Nothing yet. Once this PR has been merged, I'll verify it on the QA server.
We discussed this broad strategy in getodk/central#317.
This change only touches Sentry. When I verify this change, that'll also verify that Sentry is still working.
No change needed.
> Set Sentry tags

- lib/formats/openrosa.js
- lib/model/frames.js
- lib/model/migrations/20220829-01-create-entities-defs.js
- lib/model/migrations/20220921-01-attach-dataset-to-form.js
- lib/model/query/datasets.js
- lib/model/query/form-attachments.js
- lib/resources/datasets.js
- lib/resources/forms.js
- lib/util/db.js
- lib/util/problem.js
- test/integration/api/datasets.js
- test/integration/api/forms/draft.js
- test/integration/api/forms/forms.js
- test/integration/api/forms/versions.js
- Added a new endpoint `PATCH /projects/:id/forms/:formId/draft/attachment/:name`, it expects following request body:`{ dataset: <boolean> }` and returns attachment object
- Updated `GET /projects/:id/forms/:formId/attachments`, it now returns `blobExists` (previously `exists`) and `datasetExists`
- `form_attachments` table has a new column `datasetId`, a constraint is added that makes sure that only `blobId` or `datasetId` is filled
Note: `PATCH ../attachment/:name`, `POST ../attachment` and `DELETE ..attachment` tries to perform requested action aggressively, which means existing `blobId` will be set to null if link dataset request is received using PATCH and similarly `datasetId` will be set to null if blob is uploaded using POST, and DELETE sets both to null.
Integration test
Had …
> new: link and unlink dataset to a form

- lib/model/frames.js
- lib/model/migrations/20221003-01-add-dataset-verbs.js
- lib/model/query/projects.js
- lib/resources/datasets.js
- lib/resources/forms.js
- test/integration/api/datasets.js
- test/integration/api/forms/datasets.js
- test/integration/api/projects.js
Changes to backend to support Frontend PR: https://github.com/getodk/central-frontend/pull/636 (first version of Datasets tab)
* Adds dataset count to Project extended metadata (so Frontend can show datasets tab and page only if some exist)
* Adds `dataset.list` and `dataset.read` verbs to the permissions for the following roles: admin, manager, and viewer.
* Adds some other verbs like `dataset.create` and `dataset.update` to admin and manager only (not viewer)
Still todo in this PR or a separate one:
Tests.
Needed by frontend.
> Add Dataset verbs and add Dataset count to Project extended metadata

- lib/model/frames/dataset.js
- lib/model/migrations/20220803-01-create-entities-schema.js
- lib/model/query/audits.js
- lib/model/query/datasets.js
- lib/model/query/entities.js
- lib/worker/entity.js
- test/integration/api/audits.js
- test/integration/api/datasets.js
- test/integration/api/forms/datasets.js
- test/integration/api/projects.js
- test/integration/other/entities.js
Logs `dataset.create`, `dataset.update`, `entity.create` and `entity.create.error` events.
Some changes to make this happen:
* adding an `acteeId` on Datasets
* adding the above events to the listed types of audit log events under new categories of Dataset and Entity events
Tests
This will add new audit log events but shouldn't have any regression risks.
Need to document new types of events.
> Audit logging of dataset and entity creation

- lib/model/query/form-attachments.js
- test/integration/api/datasets.js
Fixes a bug I noticed while trying to make use of entities.
> Fix: update dataset form attachment on publish

- lib/model/query/datasets.js
- lib/resources/forms.js
- test/integration/api/forms/datasets.js
#Changes:
- Response now returns all the properties of the dataset, regardless of which form defined it
- Added `inForm` fields in the response, it distinguishes if the a property is defined by the current form. Had to make this change to cater the need of the frontend design
- Added `dataset-diff` endpoint for published forms, it doesn't return `isNew` flag
> new: dataset-diff endpoint for published forms

- lib/model/migrations/20220803-01-create-entities-schema.js
- test/integration/api/datasets.js
- Added cascade on delete for `dataset_form_defs` and `ds_property_fields` because unused drafts are deleted whenever a new draft is uploaded. Since there's a relationship between above table with `form_defs`, deletion fails.
> cascade delete dataset_form_defs and ds_property_fields

- lib/model/frames.js
- test/integration/api/datasets.js
- test/integration/api/forms/draft.js
- test/integration/api/forms/forms.js
- test/integration/api/forms/versions.js
Addresses some comment that came up in code review ([here](https://github.com/getodk/central-backend/pull/576#discussion_r996173898) and [here](https://github.com/getodk/central-backend/pull/576#discussion_r1008407467)) about how the attachment API endpoint changes with the addition of attachments from datasets. 
Instead of removing `exists` in the attachment response, `exists` will be true if there is an attachment either from a file or a dataset (e.g. it will be the boolean OR of `blobExists` and `datasetExists`). Thus this change will no longer be a breaking change. 
Made the change, checked the tests, fixed the tests.
There are 3 flags returned now about attachment state, but they are clear/descriptive and they are additive so they will not impact people using earlier versions of the …
> Make attachment exists flag or of blobExists and datasetExists

- lib/model/query/entities.js
- test/integration/worker/entity.js
There was a bug with reapproving an entity-creating submission where when the entity worker would just crash the backend server.
Now it cleanly fails to make a new entity without crashing.
Tests
Small fix of promise chain bug.
It's good -- Less crashing!
No.
> Fix: Reprocessing doubly-approved entity submission

- lib/model/query/entities.js
- lib/worker/entity.js
- test/integration/worker/entity.js
Frontend needs to have the entity **label** and **dataset name** in the details of the `entity.create` audit log in order to display this info on the submission activity feed.
Tests and seeing it in action.
It's pretty straightforward. It does mean duplicating the data of the entity label, but saves us from changing how the audit log pulls in extra info. 
Lets the right information come through the API to show on Frontend.
No, we don't describe the details of the different types of audit events in the API docs.
> Add label and dataset name to entity.create audit log

- lib/model/migrations/20221117-01-check-datasetId-is-null-for-non-file-type.js
- lib/model/query/form-attachments.js
- lib/resources/forms.js
- lib/util/problem.js
- test/integration/api/datasets.js
Closes #681 
Adds a database constraint on `form_attachments` table to check datasetId is null for non-file/non-data type attachments
I could have added condition to existing constraint but to keep things segregated I have added a new constraint
NA
NA
> fixes 681: added constrainst to check datasetId is null for non-data attachments

- lib/resources/submissions.js
- test/integration/api/submissions.js
This reverts commit 8377a0f1f62607098148af77a939f2cce3710994.
This commit may be re-introduced alongside similar changes to the OpenRosa API.
> Revert "Allow submission edits on closed forms (#530)"

- lib/data/entity.js
- lib/model/query/entities.js
- lib/worker/entity.js
- test/integration/worker/entity.js
Closes #669 by cleaning up the entity creation code used by the worker that processes submission update events. 
- went back to relying on postgres to flag entity creation errors due to constraint violations (use a nested transaction to do this and properly catch the errors and then be able to continue logging)
- made the processing code use async/await to be easier to follow
- moved the audit logging code for entity creation and error events into the processing code, not the worker
- refactored the tests to be clearer and handle different kinds of failure/non-failure cases:
* submission should not be processed
* submission successfully makes entity
* submission fails to make entity because of validation error
* submission fails to make entity because of constraint violation error …
> fixes #669: cleaning up code for entity worker

- lib/data/dataset.js
- lib/data/entity.js
- lib/model/frames/entity.js
- lib/model/query/entities.js
- test/data/xml.js
- test/integration/api/datasets.js
- test/integration/worker/entity.js
- test/unit/data/dataset.js
- test/unit/data/entity.js
Closes #676
Tests and trying it out end-to-end in central. Here's a full entity registration form in xml:
```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:entities="http://www.opendatakit.org/xforms/entities" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:odk="http://www.opendatakit.org/xforms" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<h:head>
<h:title>Trees registration with gps</h:title>
<model odk:xforms-version="1.0.0" entities:entities-version="2022.1.0">
<instance>
<data id="trees_registration_gps" version="2022.11.18.01">
<location/>
<species/>
<meta>
<instanceID/>
<entity dataset="trees" id="" create="">
<label/>
</entity> …
```
> fixes #676: Updating parsing to match entity spec

- lib/model/query/datasets.js
Closes #686.
I think this is pretty tricky to test in a way that's not brittle. I believe this issue only comes up if you upload a form def with a `meta/entity` field in an earlier version of Central, then upgrade to a version that supports datasets/entities. That's not something that we're really set up to test. The query that I'm modifying is only used in one place, and I think we can be confident that this join is helpful (or at least not harmful!). This area might get more complicated once a single form can contribute to multiple datasets, but we're not there yet.
> Don't return meta/entity fields for form def not associated with dataset

- lib/model/query/datasets.js
- lib/resources/datasets.js
- lib/resources/forms.js
- test/integration/api/datasets.js
- test/integration/worker/entity.js
Closes #671
Added integration tests
none
APIs should now return only published datasets with its published properties. 
On the frontend we have to update download dataset link and test that linking dataset to attachment is working - especially it links only published datasets
We should mention that dataset related APIs only returns published datasets, explicitly mention what do we mean by "published datasets" and "published property"
> fixes #671: only published dataset and its published properties should be accessible

- lib/model/migrations/20221118-01-make-entities-columns-not-null.js
- lib/model/query/datasets.js
- test/integration/api/datasets.js
Closes #679
- added not null constraints on several columns
- Updated unique constraint on ds_property_fields table, added a test to ensure that we don't allow multiple fields to be mapped to a single dataset property
NA
NA
NA
> fixes #679: added not null constraints on several columns

- lib/data/entity.js
- lib/model/frames/dataset.js
- lib/model/frames/entity.js
- lib/model/query/datasets.js
- test/integration/api/datasets.js
- test/integration/api/projects.js
- test/unit/data/entity.js
Fixes several items of #678
and partial fix for #674
- removed unnecessary readables writables
- removed duplicate tests
- renamed CTE expressions
- removed  from makeHierarchy
- changed {} with Object.create
- added deletedAt is null to getDatasetDiff sql
- projects/:id/datasets doesn't return revisionNumber
NA
NA
`projects/:id/datasets` doesn't return `revisionNumber` anymore
> Improve code at several places for dataset/entities feature

- lib/model/query/datasets.js
- test/integration/api/datasets.js
Added condition in dataset-diff SQL query to return dataset even if there is no published properties. 
Fixes issue # 8 in QA's "ODK Central" doc
- Integration tests
- Dataset summary on Form Draft Status page and Publish modal should be tested as well
NA
> fix: dataset-diff should return dataset even if there's no properties

- lib/model/query/forms.js
- lib/resources/forms.js
- test/integration/api/datasets.js
* don't parse dataset schema of an encrypted form
* If we have keyId on a Form then we can skip dataset parsing logic
* For Form with keyId, we can return empty array for dataset-diff endpoints
Closes #698
- Integration tests and manual testing
- For now, I have short-circuited dataset parsing logic on form upload. Later we can parse complete form and return warnings, for that we have to validate form xml.
- Initially I was thinking that frontend needs to be changed as well for this but it turns out nothing is required there. I have manually tested and all looks fine.
NA
> Enhance: don't parse dataset schema of an encrypted form

- lib/formats/odata.js
- test/data/xml.js
- test/integration/api/odata.js
- test/unit/formats/odata.js
- OData `$select` now support selecting complex type / group fields
- Added integration tests
- Tested manually on Excel
NA
- All possible OData endpoints should be tested
NA
> Enhance: complex type / groups can be '$select'ed

- lib/model/migrations/20221208-01-reduce-tz-precision.js
- test/integration/api/odata.js
Closes #459 
- Reduce precision of timestamptz columns to milliseconds across the database
- Added integration test
- see the discussion on the issue #459 
NA
NA
> Fix #459: reduce timestamptz precision

- lib/model/query/datasets.js
- lib/resources/datasets.js
- test/integration/api/datasets.js
Added new API `datasets/:name` that returns metadata of a dataset i.e. properties, forms that created properties and linked forms that consume the dataset.
> new: /datasets/:name API

- lib/model/frames/dataset.js
- lib/model/query/datasets.js
- lib/resources/datasets.js
- test/integration/api/datasets.js
Added `extended` option for datasets API that returns entities count and timestamp of latest entity
> Enhance: See more context on Datasets list

- test/integration/setup.js
CircleCI has [failed](https://app.circleci.com/pipelines/github/getodk/central-backend/1307/workflows/4bb5130e-cb29-4534-8169-b1e57b0bfced/jobs/2130) (timed out) on `master`, and the error message points to a `before` hook in test/integration/setup.js that calls `initialize()`. I suspect that the `afterEach` hook that calls `initialize()` has the same issue: CircleCI timed out [here](https://app.circleci.com/pipelines/github/getodk/central-backend/1304/workflows/e7526ea9-e86f-440d-ab72-dbb09b5a1e2a/jobs/2123) for the test "should pass the container and event details to the job", but there's no `afterEach` hook in that file. The `afterEach` hook that calls `initialize()` is the only one in test/integration/setup.js.
In terms of why we're seeing these timeouts now, maybe #583 made things …
> Disable timeout when calling initialize()

- config/default.json
- docs/api.md
- lib/data/analytics.js
- lib/model/query/analytics.js
- test/integration/other/analytics-queries.js
See getodk/central#350. The only change to the metrics is removing the `backups_configured` metric. I'm removing that metric because we're removing Google Drive backups (getodk/central#323), which means that backups will never be configured. (Direct backups will continue to work, but those aren't configured.)
Tests. During regression testing, the QA team will verify that analytics are shown in Frontend and sent to data.getodk.cloud. I don't think that the team usually verifies specific changes to metrics, but they probably could do so here. If that sounds like it'd be useful, I could mark getodk/central#350 as "needs testing".
I think this is the first metric that we're removing, so I'm not totally sure what the best approach is. I think it makes sense to remove the `backups_configured` …
> Update analytics for v2023.1

- lib/model/query/datasets.js
- test/integration/api/datasets.js
Fixes duplicate linked forms in dataset metadata endpoint
Added a test
NA
NA
Will be done separately
> fix duplicate linked forms in dataset metadata endpoint

- package-lock.json
Closes #684 
Again!
just ran `npm audit fix --legacy-peer-deps` for this one to update cookiejar.
> Updating deps again

- lib/model/migrations/20221208-01-reduce-tz-precision.js
Issue: `20221208-01-reduce-tz-precision.js` is timing out if there is too much data in DB.
Change: Replaced `Promise.all` with for-loop in migration file
> fix #459: use for-loop instead of Promise.all in migration

- lib/data/schema.js
- lib/model/frames/form.js
- lib/model/migrations/20230109-01-add-form-schema.js
- lib/model/query/analytics.js
- lib/model/query/datasets.js
- lib/model/query/forms.js
- lib/worker/form.js
- test/integration/api/datasets.js
- test/integration/api/forms/draft.js
- test/integration/api/forms/versions.js
- test/integration/api/submissions.js
- test/integration/other/form-purging.js
- test/integration/other/migrations.js
- test/unit/data/schema.js
Introduces an intermediate form schema table for collapsing form fields from different versions of the same form that share the same schema. Closes issue #662.
This PR is meant to be all under the hood, but it touches a lot of things under the hood. The main structure of these changes are as follows:
1. Migration to collapse duplicate form schemas. This involves adding a `form_schemas` table that just stores an int, and replacing `formDefId` columns on `form_fields` and `form_defs` with a link to this schema ID `schemaId` that can be shared across defs. There is also a block of code that goes through all existing form defs and compares their fields to assign appropriate schema IDs. 
2. A change of all queries that include `form_fields` to join with `form_defs` through the schema ID …
> Intermediate form schema table to collapse dupe schemas

- lib/model/query/users.js
- test/integration/api/users.js
- test/integration/setup.js
Closes #736.
New integration test.
The biggest question to me was which action to use. I used `user.update` since changing a password also logs that action. This is how we describe `user.update` in the API docs:
> * `user.update` when User information is updated, like email or password.
I think that fits its new use in this PR.
This is a targeted change, so regression risks should be low.
I think the current description of `user.update` in the API docs already fits its use in this PR.
> Create audit log entry when password is invalidated

- lib/model/query/entities.js
- test/integration/api/datasets.js
- test/integration/worker/entity.js
Closes #729. This is to make the server not log an error when reapproving an edited submission that was already made into an entity.
Wrote a test to mimic scenario where this came up. It failed and then with the code change, it passes.
It's ok for now.
Not very risky.
No.
> Check for existing entity across submission defs for same submission

- lib/model/query/analytics.js
- lib/model/query/forms.js
To enable, add to `default` in config:
```
"taskSchedule": {
"purge": 1,
"analytics": 1
}
```
Otherwise default remains set to 30 days.
Closes #713
I tried setting the numbers through the config and printing them out? Not sure how to write a test or if it's necessary. We don't test other server config settings. 
It's pretty simple.
Not really for users, more for QA to use. Since the default time ranges aren't even being added to the config, most people won't even notice this.
Should there be some sanitization of these values? 
no.
> Allows task frequencies for purging and analytics to be set in config

- lib/external/sentry.js
- lib/http/service.js
- test/unit/external/sanitize-sentry.js
- Added request duration in the event object of Sentry
- Tested manually 
- I have added `x-request-received-at` in the request header, I could have created a different property in the request object but that would have forced me to modify RequestHandler of Sentry. Implemented solution is the simplest one.
- NA
- NA
> Add request duration in Sentry logs

- test/integration/api/users.js
- test/integration/setup.js
This PR updates `service.login()` to call `expect(200)` after it sends a request to create a session. I somehow managed to misspell alice in a test 😅 and adding this `expect()` call helped me figure out what was going wrong. Making this change means that the error message will be more informative. I also think that setting the expectation that the session request is successful makes it easier to reason about what `service.login()` does. `service.login()` retrieves the `token` property from the response body, so if the response isn't a 200, I think things get confusing.
However, there was one test that actually expected that the session request sent by `service.login()` would fail. I rewrote that part of the test, and I think doing so actually made the test clearer as well.
> Have service.login() call expect(200)

- lib/data/schema.js
- test/integration/api/datasets.js
- test/integration/other/select-many.js
- test/unit/data/schema.js
Related to a bug found by QA (and @matthew-white) when looking into issue #439. 
A "select" and a "selectMultiple" field were considered to be the same type of field, so if a user uploaded a form with a single select (`select1`) and then changed it to a selectMultiple (`select` in xml), the intermediate form schema would not think the schema had changed, continue to treat it as a single select, and thus any multi select behavior (mainly involving exports) would fail. 
This PR adds a condition in to the form schema `compare()` utility to also look at the selectMultiple attribute (or lack thereof) on a field. 
It also adds a test for the scenario above and some additional unit tests. 
Because the migration uses this `compare` function, this should fix any issues with that, too.
Tests.
It's …
> Fix compare to not match select and select1 fields

- lib/model/query/forms.js
- lib/util/problem.js
- test/data/xml.js
- test/integration/api/forms/draft.js
- test/integration/api/forms/forms.js
- test/integration/api/forms/list.js
- test/integration/api/forms/test.js
- test/integration/api/submissions.js
- test/integration/other/select-many.js
- test/unit/data/briefcase.js
This PR addresses a situation (maybe this should become an issue but it's also not that big of a deal) where the submission view page on Frontend failed to load when showing a submission for a form without a `<meta/>` tag (generally containing the instance ID). We expect forms in the present day to all include meta information, but in case they don't, this change will now reject the uploading of forms that are missing the meta group.
Tests.
Another option is leaving the code as is and not checking. I think the biggest risk is for us as developers - it's more code to maintain. And many of the old tests didn't have meta information so I had to go through and update them. 
*Edited to add*: For forms that are already in the system, this might cause problems when trying to make a new draft of …
> Check for meta group on form upload

- lib/model/query/forms.js
- test/integration/api/forms/draft.js
Closes #381 
Unskipping some tests that existed before.
It was easy to add this to the downcast checking function! 
Shouldn't have a big impact on users unless they're changing their field types a lot. Should help people keep their data cleaner. 
I don't think so.
> Disallow string downcast for groups and repeats

- lib/model/query/forms.js
- lib/resources/submissions.js
- lib/util/problem.js
- test/integration/api/submissions.js
Closes #629, where if the submission XML is missing the version string or has a version that doesn't match any known version for that form, the response returns a generic 404 error message. Now it returns a more informative 404 error message. 
The 404 resource not found is an artifact of how when we have a specific version to look for, our form query has these specific constrains and it's easy to reject if we don't find what we are looking for.
The approach of this PR changes that flow a bit: if we don't find the right form and form def/version that the submission is targeting, we look again _without_ the specific version constraint. If we find something when we look that way, then it's a problem with the form version. It feels like extra work, but it'll lead to clearer error messages.
It …
> Return specific Problem when form version in submission not found

- lib/data/entity.js
- lib/model/query/form-attachments.js
- lib/model/query/submissions.js
- lib/resources/datasets.js
- lib/resources/forms.js
Closes #678: long tail of entity-related changes that don't fit in their own issues/PRs. 
Links to the specific comments:
1. [coalesce(e."updatedAt", e."createdAt") ](https://github.com/getodk/central-backend/pull/576#discussion_r1013194274)
2. [renaming `streamEntityCsvs` and variables in that function](https://github.com/getodk/central-backend/pull/576/files/b70ec975c5fffb70b01b74b91073aefa926eaee1#r1012891214)
3. [SubmissionPartial to just Submission](https://github.com/getodk/central-backend/pull/576/files/b70ec975c5fffb70b01b74b91073aefa926eaee1#r1012111496) 
Tests.
I went through every comment in PR #576 where this issue came from and either
- marked it as resolved a while ago through some other code change
- fixed it here if it was a quick fix
- made sure it had its own issue
Very …
> Long tail of entity/dataset small code changes

- lib/model/frame.js
- lib/model/frames.js
- lib/model/frames/form.js
- lib/util/db.js
- lib/util/problem.js
- test/integration/other/encryption.js
- test/unit/util/db.js
Closes #707 
Unit test, integration test and manually tested with the form with 25K questions.
Postgresql has a limit of parameters that can be passed in a query. To insert large number of rows it provides `unnest` function. Alternative is to break the rows into batches which is not performant and would require a lot of code changes.
Test cases related to multiselect question, client audits, form attachments and submission attachments should be executed.
no
> fixes 707: use sql.unnest instead of sql.join for bulk insert

- soak-tester/scripts/ci-soak-test
When we took out the password argument from the cli tool, the soak test stopped working with this error: `ERROR: Unknown option -p`
> Changing how password used in soak test

- lib/formats/openrosa.js
- lib/model/query/datasets.js
- lib/resources/datasets.js
- test/integration/api/datasets.js
Closes #770 
- Added ETag in response of entity.csv and logic to return 304 if `If-None-Match` matches serverEtag
- Fix a bug: form manifest crashes if the form has attached dataset with entities in it. Root cause md5sum function expects a string and we were passing a Date object
- Fix: use coalesce of updatedAt and createdAt for timestamp of latest entity
- Added integration tests
- Manually tested ETag logic
NA
Test ODK Collect's behaviour for forms with dataset attached that has entities in it.
No
> ETag for entities.csv

- lib/model/query/datasets.js
- lib/model/query/entities.js
- test/data/xml.js
- test/integration/api/datasets.js
- test/integration/worker/entity.js
Closes #779, #767 and #675 
Dataset properties when returned for a specific dataset (not in a diff) or for the header of a CSV are ordered first in published order, and then the order they are found in the form. 
Things get a little complicated when multiple forms share properties, but as much as possible, properties are grouped with the form fields they came from. 
Entities in the CSV and in the OData endpoint are returned in reverse chronological order like submissions with the newest entity at the top.
This PR also fixes an issue with setting the publishedAt field on relevant dataset properties when they already exist but are unpublished.
Tests. 
One original suggestion was to order the properties by their property id, but there can be a situation where
- form 1 has properties A, B, C, …
> Return dataset metadata properties and entities in order

- docs/api.md
- lib/model/frames/submission.js
- lib/model/query/submissions.js
- lib/resources/submissions.js
- test/assertions.js
- test/integration/api/submissions.js
Closes #417, #481, #590
Updated integration tests
Detailed discussion on Slack
None
Updated.
> Update Submissions response

- .circleci/config.yml
- .github/workflows/soak-test.yml
- Makefile
- docs/api.md
Match what the standard setup will be starting with 2023.2. There are no changes needed to the code so we might as well start doing this now.
Nothing, CI should be enough.
We could wait until we're ready to release backend but I don't see any advantage in that. I used 14.6 which is the [latest available from CircleCI](https://circleci.com/developer/images/image/cimg/postgres). This matches our [recommendations in docs](https://github.com/getodk/docs/pull/1577/files#diff-c3ac24ca7534cc83beec0c8af79032b0aff1d9010803759e057192dcd4739952R205).
None, this is CI only.
No.
> Use postgres 14

- lib/model/migrations/20230324-01-edit-dataset-verbs.js
- lib/resources/datasets.js
- lib/resources/forms.js
- test/integration/api/projects.js
- test/integration/other/migrations.js
Closes #794 
Adds `dataset.read` and `entity.read` verbs for reading individual datasets and (eventually) entities to the list of verbs for Admins, Managers, and Project Viewers.
Also adds `entity.create` and `entity.update` verbs for Admins and Managers to be ready for entity creating/updating!
Tests.
Something we've needed for a little while.
No effect. In some places, `dataset.list` was used in place of `dataset.read` but the same roles have the same verbs so it doesn't really change anything.
No, verbs aren't individually listed in the docs.
> Add dataset.read and entity.read verbs.

- lib/model/query/datasets.js
- lib/model/query/form-attachments.js
- lib/resources/datasets.js
- lib/resources/forms.js
- lib/resources/odata-entities.js
- test/assertions.js
- test/integration/api/datasets.js
- test/integration/worker/entity.js
Closes #691 
The diff looks like a mess because I changed a bunch and moved things around. Here's the new organization:
`Datasets.createOrMerge` and `Datasets.publishIfExists` used by the Forms query module.
This is mostly the same as before but there's an issue #793 for refactoring.
Get all datasets for a project or get a single dataset. These return minimal information about Datasets -- just the metadata, really, or the "extended" metadata consisting of entity counts and last entity timestamp. They can be used for auth checks and listing basic information about Datasets on frontend. More complicated stuff about Datasets (including properties) is accessed below. 
One observation here is that these are called by a resources where the project id and dataset name is known. By having a …
> Rename getter functions in Dataset query module

- lib/model/query/datasets.js
- lib/model/query/forms.js
Closes #793
Changes the interface between Forms.createNew and Forms.createVersion that updates Datasets. Now `Datasets.createOrMerge` takes raw arguments from Forms and builds and filters what it needs itself. 
Tests have remained the same.
It was a little awkward making the Forms query module filter out the form fields and build a partial Dataset object to pass the name and project id through. Now the code in the Forms module is simpler. If more changes need to happen on Dataset creation, they can happen within the Dataset query module. The function in the query module is also now async/await and a bit easier to follow.
No changes to users.
No changes to docs.
> Move prep work from Forms to Datasets.createOrMerge

- lib/data/entity.js
- lib/model/frames/entity.js
- lib/model/migrations/20230406-01-add-entity-def-fields.js
- lib/model/migrations/20230406-02-move-entity-label-add-deletedAt.js
- lib/model/query/entities.js
- test/integration/other/migrations.js
- test/integration/worker/entity.js
- test/unit/data/entity.js
Closes #817 and #818. Also closes #816. 
This PR includes 2 migrations that get the `entities` and `entity_defs` table better set up for ongoing entity work.
1. Adds `creatorId` to `entity_defs` to track who is responsible for each version / update of an entity
2. Adds `userAgent` as well to `entity_defs` to track more context about each version
3. Moves `label` from the root `entities` table to `entity_defs` because it is something that can be updated
4. Adds a `deletedAt` field to `entities` table.
The `creatorId` and `userAgent` are filled from the submissionDefId that we already have linked to each entity. In the future, entities will be able to be created without a submission, which is why we need to store these source fields separately and not implicitly keep them in the submission. …
> Entity migrations

- .gitignore
- lib/data/entity.js
- lib/model/frames/entity.js
- lib/model/query/entities.js
- lib/resources/entities.js
- test/integration/api/entities.js
This PR is part of working on issue #797, allowing entities to be updated.
New data can be sent in `{ data: { age: '44' } }` in the body of a `PATCH` request to a specific entity. It will update the entity, save the API authenticator as the creator ID, indicate that the source of the update was the API, and add an audit log event.
If a field is provided that is active in the dataset, the request will be rejected.
The label can also be updated: `{ data: { label: 'New Label' } }`.
There's no notion of versionNumbers in here yet.
Tests.
Docs in a separate PR.
> Entity updating via PATCH

- docs/api.md
- lib/model/query/datasets.js
- lib/resources/datasets.js
- lib/resources/forms.js
- lib/util/http.js
- test/integration/api/datasets.js
- test/integration/api/forms/forms.js
Closes #826
Added ETag feature for OpenRosa attachment endpoint. It works for both blobs and datasets
Integration tests and manual verification locally
NA
No
Updated.
> added etag feature for openrosa attachment endpoint

- lib/http/preprocessors.js
Use `.substring()` in preference to `.slice()` when manipulating Strings to make code's intention clearer.
> auth: make string manipulation code clearer

- lib/data/dataset.js
- lib/model/query/datasets.js
- test/integration/api/datasets.js
- test/unit/data/dataset.js
Closes #688 by adding validation to the entity/dataset property names. These are checked when the form with the dataset definition is uploaded. 
Tests, including tests that were already there.
Similar to dataset name validation approach.
The main tricky part of this validation is that while the dataset metadata is parsed from the form XML in one place, which can easily included the dataset metadata validation, the properties are parsed as part of the form field parsing, which doesn't seem like an appropriate place for dataset property validation. Thus this validation happens all the way inside the `Datasets.createOrMerge` query function, far from the other bit of dataset validation. Maybe that validation should be moved? 
Limits the set of allowable dataset/entity property names. Probably …
> Validation of entity/dataset property names

- lib/http/preprocessors.js
- lib/http/service.js
- test/unit/http/preprocessors.js
The `sessionHandler` function handles more than just sessions, so it seems appropriate to rename it `authHandler`.
It currently handles authentication via:
* session token in Authorization header & cookie
* field key
* HTTP basic auth
For GET/HEAD requests using session-based authentication via Cookie header, this function also checks the CSRF token.
> Rename authHandler to reflect wider responsibilities

- test/integration/other/analytics-queries.js
- test/integration/other/migrations.js
As discussed at https://github.com/getodk/central-backend/issues/588#issuecomment-1523024085, this enables `make test` to pass on my machine.
Scope could possibly be narrowed to these tests:
```
1) datbase migrations: removing default project
should put old forms into project:
Error: Timeout of 4000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/odk/odk-central-backend/test/integration/other/migrations.js)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7)
2) datbase migrations: intermediate form schema
should test migration:
Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. …
```
> tests: double explicit timeouts

- lib/data/entity.js
- lib/model/frames/entity.js
- lib/model/query/entities.js
- lib/resources/entities.js
- lib/util/problem.js
- test/integration/api/entities.js
- test/integration/api/odata-entities.js
- test/unit/data/entity.js
Closes #798 
Allows entities to be created via POST request to `/v1/projects/:projectId/datasets/:datasetName/entities`
Sample payload may look like this, with uuid, label, and data. Provided properties must be a subset of existing dataset properties. Values of label and data must be _strings_ (numbers must be in quotes and null/empty values must be empty strings: `''`)
```
uuid: '12345678-1234-4123-8234-111111111aaa',
label: 'Johnny Doe',
data: {
first_name: 'Johnny',
age: '22'
}
```
Tests.
Wanted to double-check the format of the incoming entity with other folks.
- Should label be in or out of the data block?
- Should the outer fields be in a meta block? It would match the submission xml a bit more but i don't know how much it matters.
I tried to reuse the same validation used by …
> Create entity via POST

- lib/http/preprocessors.js
- soak-tester/index.js
- test/integration/other/bearer-auth.js
- test/unit/http/preprocessors.js
Include trailing space in checks for `Basic` and `Bearer` prefixes in Authorization headers.  This space is already assumed to exist in subsequent parsing code.
An extra check is added for requests which _provide_ the Authorization header, but in an unrecognised format.  This ensures that a 401 header is still sent in preference to 404, as per #329.  It also changes the response code for unsupported auth-schemes _when they do not start with either `Bearer` or `Basic`_.
> Make Authorization header checks tighter

- lib/data/entity.js
- lib/model/query/entities.js
- lib/resources/forms.js
- test/integration/api/datasets.js
- test/integration/worker/entity.js
Closes #801 & #842
Ensure ODK Collect and Enketo can still use entities data as attachment in the forms.
will be done as part of #809
> enhance: entity csv export to match with odata feed

- lib/resources/entities.js
- test/integration/api/entities.js
Closes #855 
Getting things cleaned up for release 
- we've decided NOT to include a PUT endpoint for updating entities as the functionality is covered by the PATCH endpoint
- removes the RESTORE endpoint (could bring back later)
- removes an endpoint about entity version numbers (could bring back, not included in this release)
> Removed some boilerplate code about PUT and RESTORE for entities

- docs/api.md
- lib/model/query/datasets.js
- lib/resources/datasets.js
- test/integration/api/datasets.js
Closes #793 
Integration Test
NA
No
Yes
> enhace #793: query param to sanitize property names

- lib/model/frames/entity.js
- lib/model/migrations/20230512-01-add-entity-root.js
- lib/model/migrations/20230512-01-add-entity-source.js
- lib/model/migrations/20230512-02-backfill-entity-id.js
- lib/model/migrations/20230512-03-add-entity-source.js
- lib/model/query/audits.js
- lib/model/query/entities.js
- lib/resources/entities.js
- test/integration/api/datasets.js
- test/integration/api/entities.js
- test/integration/other/migrations.js
This PR is heavily inspired/builds directly off of PR #846, introducing an entity audit log endpoint that implicitly reconstructed important information about the context of an entity's creation.
This is a prototype of introducing an explicit entity_source table instead of reconstruction that information.
1. migration to add `entity_sources` table
* includes
* `auditId` (triggering event id)
* `submissionDefId` (current one kind of triggering object)
* `details` (a place to store info about the object that we need to persist after object gets deleted)
* also adds column to `entity_defs` table
* populates and links new table
* migration is additive right now - doesn't yet remove `submissionDefId` (essentially our first version of source) from `entity_defs` table
3. change entity flow to …
> Prototype of entity_source table connected to entity audits

- lib/model/query/audits.js
- test/integration/api/entities.js
The entity source table contains the id of a source event that created that entity def. Originally, it was just a submission approval event, but now other types of events, namely `submission.create`, can also make an entity. Instead of calling it `approval` in the API response, we wanted to give it a more generic name.
Went with `sourceEvent` but other options could include `triggeringEvent` or `event`.
This will need docs changes in the other docs PR.
> Change name of approval event in entity audits to something more generic

- lib/model/query/submissions.js
- test/integration/api/submissions.js
Closes #858 
Added integration test
Other option was to change the behaviour of `forApi()` but looks too risky to me
None, I'll create a separate PR to verify/fix same for entities
No
> fixes #858: Submission frame should be reinstantiated

- lib/data/entity.js
- test/integration/api/datasets.js
Closes #869 
Integration Tests 
I could have typed array of array as literal but that looked ugly
No
No
> fixes 869: pass property path as array instead of dot delimited string

- lib/data/analytics.js
- lib/model/query/analytics.js
- test/integration/other/analytics-queries.js
Backend portion of https://github.com/getodk/central/issues/410
Needs the frontend translation change and the central config version change and the new version of the form to be uploaded.
[odk-analytics.xlsx](https://github.com/getodk/central-backend/files/11566705/odk-analytics.xlsx)
Integration Test +
Tried sending local analytics to test server.
NA
No
No
> Add usage metrics for counting entity updates

- config/default.json
This change is needed for getodk/central#410 alongside #889. Updating the form version is part of the checklist in getodk/central#410. I always forget where we need to update the form version, but I'm pretty sure it's this repo, not the `central` repo: I don't see an analytics config in `central`.
I've updated the form version in the config to match the form attached to #889.
This is just a config change. Once this PR and #889 are both merged, we'll be able to try out the new metric on staging.
> Update analytics form version in config

- lib/model/query/form-attachments.js
- lib/resources/forms.js
- test/integration/api/datasets.js
- added dataset download ability to testing endpoint
- moved the common logic to query module
Integration test + verified running it locally
I could have kept the common logic in resource module but that would entail passing 6+ parameters to new function because we container is only injected in query module.
No
No
> Fixes: testing form that consumes dataset

- lib/resources/submissions.js
- test/data/xml.js
- test/integration/api/submissions.js
Closes https://github.com/getodk/central/issues/433
Multer is parsing filename with latin1 encoding instead of UTF-8. https://github.com/expressjs/multer/issues/1104
- Tested locally + integration test
Created local middleware to convert latin1 encoding to utf8
This is localized changed, if submission are tested from Enketo and Collect are tested then we should be good
None
> fixes 433: convert latin1 to utf for filenames return by multer

- lib/formats/mail.js
- test/integration/api/users.js
I think when a new user gets this message, it's not going to be clear that they know what "data collection" is and whose data is being collected, and all that. Seems safer and friendly not to add this context and just say "ODK Central server"
> Data collection is either too specific or too general

- package-lock.json
- package.json
- test/assertions.js
- test/integration/api/sessions.js
- test/integration/api/submissions.js
- test/integration/setup.js
- test/integration/worker/entity.js
Resolves `npm` warning:
```
WARN deprecated superagent@3.8.3: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
```
> Update dev dependency: supertest

- lib/http/endpoint.js
- test/unit/http/endpoint.js
Closes #701
Manually tested downloading csv file of encrypted form with 1K submissions
We don't need to start database transaction for downloading of csv file, just like we don't start it for zip download
None
None
> fixes #701: don't start transaction for POST submission.csv

- lib/model/query/datasets.js
- test/data/xml.js
- test/integration/api/datasets.js
On Slack, @lognaturel identified a bug where a form field that populates an entity property is not updated if it’s changed by a new form version.
> For example, let’s say my form has fields `form` and `form_name`. I put a `save_to` on `form_name`. Then I realize I made a mistake and change the `save_to` to `form`. New submissions using the new form definition still save `form_name`.
It seemed like the fields being used to parse entity properties from a submission weren't filtered to just the properties in that specific form def/schema.
Looking into it more, this was indeed the case: when looking up fields by the submission's form def id, dataset property fields were joined via the form schema, but the schema doesn't change when just the entity bindings change (but maybe it should??) …
> Fix entity bug where the wrong properties of an entity are populated

- lib/model/query/analytics.js
- test/integration/other/analytics-queries.js
Closes #921. This PR doesn't change the current behavior, but it tries to make that behavior clear. For example, I used to think that usage reports were sent every 30 days. After this PR, usage reports will continue to be sent every 31 days — but I think that fact will be clearer.
Updated and new tests.
I considered not making any changes at all. I realized that I could send daily usage reports by setting the `default.taskSchedule.analytics` config to 0 instead of 1. However, I think this PR makes things a little clearer.
I'll also leave a comment about an individual line.
The current behavior is intended to stay the same. I've updated tests to help verify that there hasn't been a change in behavior.
I don't think so. We say in the API docs that usage data is sent monthly, which is …
> Clarify how often usage reports are sent

- docs/api.md
- lib/resources/sessions.js
- test/integration/api/sessions.js
This PR adds an endpoint to delete the current session, making it easy to log out without specifying the token of the current session in the URL. We will probably use this endpoint in Frontend, but I also imagine that some API users would find it convenient.
New tests. I copied some of the tests of DELETE /v1/sessions/:token. I didn't copy all the tests, since the two endpoints call a shared function: I think the tests of DELETE /v1/sessions/:token provide good coverage of that shared behavior.
I created a shared function because I think there's enough logic shared between DELETE /v1/sessions/:token and the new DELETE /v1/sessions/current to warrant one. DELETE /v1/sessions/current ends up being quite short and looks very similar to GET /v1/sessions/restore.
I chose the path …
> Add endpoint to delete current session

- lib/resources/sessions.js
- test/integration/api/sessions.js
After a session is created, Backend returns two cookies: `__Host-session` and `__csrf`. The cookies expire at the same time as the session, so if a session expires on its own, the cookies will expire as well and be cleared. If the user logs out the session before it expires, then the `__Host-session` cookie is cleared — but the `__csrf` cookie is not. I don't think that's a huge deal, but I think it's cleaner to clear both cookies together, which is what this PR does.
Updated tests.
The change is pretty small.
This change isn't really user-facing. It's more about cleaning up after logout. I think the risk of regression is low.
I don't think changes are needed. We discourage the use of cookie auth in the API docs, and we don't document the `__csrf` cookie at all.
> Clear __csrf cookie after logout

- test/integration/setup.js
We have a couple of migrations that log messages. I think that logging is helpful for users and in migration tests. However, those messages are also logged whenever the database is reinitialized during testing (whenever `testServiceFullTrx()` or `testContainerFullTrx()` is used). I don't think the logging is useful in that case and actually makes it harder to read the test output. This PR tries to improve that case by silencing logging from migrations only when the database is (re)initialized during testing.
Before making this change, I ran a subset of tests and saw logging from migrations. After making this change, that logging was gone. However, other logging continued to come through: I called `console.log()` in a test, and I saw its output.
This is a small change and targeted so that …
> Silence logging from migrations when setting up database in testing

- test/integration/api/analytics.js
This is related to https://github.com/getodk/central-backend/issues/763 but I've set up the issues so this frontend PR (https://github.com/getodk/central-frontend/pull/836) will close it. This specific PR just adds a test.
Didn't change any code, just added a test. I think we added analytics before we removed the default project, and then I was concerned backend was making a malformed response in that empty-project scenario. It's not -- it makes a reasonable response with an empty project array.
Didn't change any code.
Didn't change any code.
No.
> Added test for analytics of zero projects

- Makefile
We have a few different makefile rules related to testing: `test`, `test-full`, `test-integration`, and `test-unit`. `test-full` is what's run in CircleCI, but `test` is much faster because it mocks bcrypt. `test-integration` and `test-unit` run a subset of tests, and I believe they're only run locally. However, unlike `test`, they don't mock bcrypt. I've noticed that this makes `test-integration` take a long time. I often run `test-integration`, and it'd be nice if it mocked bcrypt so that it was faster. Another way to put it is that I think `test-integration` should be a subset of `test` rather than a subset of `test-full`. I think it's important that tests in CircleCI don't mock bcrypt, but while iterating on development locally, it's nice to be able to run tests more quickly.
I …
> Mock bcrypt during `make test-integration`

- lib/model/query/datasets.js
- test/integration/api/datasets.js
Closes #708 
Ordering the dataset properties is really tricky because of how they're represented in the database. The gist of this change is that when querying the `dataset-diff` endpoint, that is done relative to a specific form, a specific _version_ of that form, even, so the order of the properties should match the order of the fields in that version of the form and be grouped together, and the order of the rest of the properties really isn't as important. (These properties are not even shown on Frontend.) Or if the order if the rest of the properties does seem important, I want that to be determined by the one other chunk of code dedicated to ordering dataset properties for a whole dataset.
Given all that, I split the query from one massive query into 
1) getting just the properties …
> Change dataset-diffs to return properties in form question order

- docs/api.md
- lib/model/query/audits.js
- lib/model/query/datasets.js
- lib/model/query/forms.js
- test/integration/api/audits.js
- test/integration/api/datasets.js
Closes #664 and #811
NA
None
Yes
> Enhances #664: add logs only when changes are published

- lib/data/schema.js
- test/integration/api/datasets.js
- test/unit/data/schema.js
Closes #670 
We had a number of questions from the issue
- What happens if a `saveto` is on a bind for a structural field, like a group or repeat group?
* Answer: pyxform is more strict than Central when it comes to dataset/entity schemas in form definitions. If you try to put a `saveto` on a structural field, it will return an error like `Groups and repeats can't be saved as entity properties.`
- What does Central currently allow/disallow, given that pyxform is more strict?
* Answer: Central is looking for binds with `type` attributes and ignoring other kinds of binds. It doesn't disallow them, though, because sometimes a bind might be used on a structural field for handling relevance (see https://github.com/getodk/central-backend/issues/147). 
- What happens when a `saveto` is on a …
> Validate savetos on structural fields

- lib/model/query/datasets.js
- test/integration/api/datasets.js
Closes getodk/central#464
Integration tests and manual verification
This is the simplest solution, other thing that could do was return properties without forms and a separate field to specify relation between sourceForm and properties
None
Should be done in #949
> fixes #464: always return source forms

- lib/model/query/submission-attachments.js
- test/integration/api/submissions.js
- test/integration/other/encryption.js
The submissions.csv.zip exports client audit logs in two ways:
1. It exports each submission's individual client audit log along with other submission attachments (via `SubmissionAttachments.streamForExport()`).
2. It combines all client audit logs into a single CSV file (via `ClientAudits.streamForExport()`).
If we're doing (2), then I think we don't really need to do (1). Exporting both (1) and (2) effectively exports each client audit log twice. For some forms, there can be more client audit log data than actual submission data, in which case exporting both ends up adding quite a bit of redundant data.
Note that the individual client audit logs aren't easily accessible from the .zip. Typically, each client audit log has the same name: audit.csv. That means that each log is written to …
> Do not export individual client audit attachments in .csv.zip

- lib/model/frames/entity.js
- lib/model/migrations/20211021-remove-hashes-from-audits.js
- lib/model/migrations/20230830-01-remove-entity-label-from-audits.js
- lib/model/query/audits.js
- lib/model/query/entities.js
- test/integration/api/submissions.js
- test/integration/worker/entity.js
Backend part of issue #822 
Frontend PR [here](https://github.com/getodk/central-frontend/pull/850) (Makes small change on frontend to look up `label` from a new place.)
In the same way we look up current information about a submission when we get audit log events for a specific entity (so we can appropriately handle deleted submissions), this does the same thing for entity information.
Previously, the details for an event like `entity.create` contained an `entity` object with `uuid`, `dataset`, _and_ `label`. 
`label` has been removed, so the audit details only contain `uuid` and `dataset` but default.
But through the `getBySubmissionId` query, for events about entities, `details.entity` contains entity data populated from the database. This object has the same structure you'd see …
> Remove entity label from audit log and look up info in database

- test/integration/other/analytics-queries.js
There are failures of these tests in CI due to timeouts.
CircleCI occasionally:
* https://app.circleci.com/pipelines/github/getodk/central-backend/1741/workflows/7d9014c0-3358-42d0-ad81-32dc2a195ebb/jobs/2583
Github Actions frequently:
* https://github.com/alxndrsn/odk-central-backend/actions/runs/6048978821/job/16415366255#step:7:10856
* https://github.com/alxndrsn/odk-central-backend/actions/runs/6049092424/job/16415712862#step:7:10849
* https://github.com/alxndrsn/odk-central-backend/actions/runs/6049135803/job/16415849308#step:7:10842
* https://github.com/alxndrsn/odk-central-backend/actions/runs/6049985595/job/16418307942#step:7:10862
* https://github.com/alxndrsn/odk-central-backend/actions/runs/6049504238/job/16416917068#step:7:10879
* …
> test/analytics-queries: increase test timeouts

- lib/formats/mail.js
Adds "Otherwise" to more closely match other similar emails.
Only visual verification.
I considered moving the "please sign in" up to the first paragraph but I decided to match the structure of other existing emails instead.
> Improve flow of SSO account creation email

- config/default.json
- lib/data/analytics.js
- lib/model/query/analytics.js
- test/integration/other/analytics-queries.js
Closes #
Here's an xlsx file representing the updated form: https://docs.google.com/spreadsheets/d/1L6GwYeTZjNSilI-pSLRA1ZnoFgfRYLBs/edit#gid=1058536497 
Adds 7 new properties under System:
- sso enabled (still TODO)
- number of client audit attachments
- number of client audit attachments that failed processing
- number of extracted client audit rows
- number of overall audit log events failed at least once
- number of overall audit log events failed completely (5 times)
- number of overall audit log events that were never processed and are over a day old
Versioning of the form changed to match release, e.g. `v2023.4.0_1`
> Usage metrics for v2023.4

- lib/model/query/analytics.js
Matt noticed that the analytics preview was returning more subproperties than `recent` and `total` because of how i'd combined a SQL query and pulled the response back out.
```
"num_audit_log_entries":{"recent":1440,"total":3337,"any_failure":0,"failed5":0,"unprocessed":0}
```
now should be
```
"num_audit_log_entries":{"recent":1440,"total":3337}
```
> Fix to analytics saving extra property in wrong place

- lib/data/entity.js
- lib/data/odata.js
- lib/formats/odata.js
- lib/http/endpoint.js
- lib/model/query/entities.js
- lib/model/query/submissions.js
- lib/resources/datasets.js
- lib/resources/odata-entities.js
- lib/resources/odata.js
- lib/util/db.js
- lib/util/odata.js
- lib/util/util.js
- test/integration/api/datasets.js
- test/integration/api/odata-entities.js
- test/integration/api/odata.js
- test/unit/data/odata.js
- test/unit/formats/odata.js
- test/unit/util/db.js
- test/unit/util/util.js
Closes #665
What has been done to verify that this works as intended?
Why is this the best possible solution? Were any other approaches considered?
- Base64 of a json object is used for skipToken. Fields of the json object depends on the odata table. In case of Submission, it is instanceId, for Submission subtable (repeat) it is repeatId (hash of the data - existing approach) and for Entities it is UUID
- I didn't compress the token, base64 encoding fulfills the requirement
- We are still fetching all the Submissions when data for the subtable is requested because we need to count the total repeating rows and return `nextlink` conditionally i.e. only when there are more rows to be returned. So pagination for subtable is not much of a help, it only saves bandwidth between …
> Odata opaque cursor 

- test/integration/api/datasets.js
Backend part of https://github.com/getodk/central/issues/467
Tested it with frontend and added a specific test.
When getting metadata about a dataset/entity list, it doesn't even seem to include the `publishedAt` timestamp, so it makes sense to only return published datasets at the `/datasets/:name` url and return 404 resource not found otherwise.
Limits access to unpublished datasets but makes some parts of frontend more consistent.
Writing this out in the API would be a good idea. Tagging https://github.com/getodk/central-backend/issues/949
> Return 404 if accessing unpublished dataset aka entity list

- config/default.json
- lib/bin/run-analytics.js
- lib/external/odk-analytics.js
- package-lock.json
- package.json
Closes #970 
I'm not really sure what was wrong -- pipeline + old FormData + an XML attachment in a buffer was just Not Working. Maybe something about not knowing the length of the request up front (even though I think we do have it) and that messing up streaming?
Anyway, this seems to work a lot better. 
Got rid of `form-data` package because I think I added it just for this purpose of sending analytics.
Tried it.
I think it's pretty reasonable -- streaming the xml data directly in the request instead of shoving it into a file attachment, and using the REST API instead of the OpenRosa API. 
Keeps analytics from breaking, but this just runs in a little cron job so it shouldn't have any impact on users.
no
> Fix sending usage metrics/analytics by using REST endpoint

- lib/data/dataset.js
- test/unit/data/dataset.js
Closes https://github.com/getodk/central/issues/482
Tests
This wont make the property name lowercase but it will temporarily lowercase it before doing the regex validation.
> Make name/label entity prop validation case-insensitive

- lib/model/migrations/20230907-01-opened-form-verb.js
- lib/model/query/auth.js
- lib/model/query/forms.js
- lib/model/query/projects.js
- lib/resources/forms.js
- lib/resources/projects.js
- test/integration/api/app-users.js
- test/integration/api/projects.js
- test/integration/api/public-links.js
- test/integration/other/encryption.js
- test/integration/other/roles-data-collector.js
- test/integration/setup.js
Closes [sec#2](https://github.com/getodk/security/issues/2)
**Impact:**
Following endpoints were accessible for "App User", "Data Collector" and "Public link" when Form was closed, after this change they return 403:
- /v1/projects/1/forms/:name
- /v1/projects/1/forms/:name.xls
- /v1/projects/1/forms/:name.xml
- /v1/projects/1/forms/:name/versions
- /v1/projects/1/forms/:name/fields
- /v1/projects/1/forms/:name/manifest
- /v1/projects/1/forms/:name/attachments
- /v1/projects/1/forms/:name/attachments/:name.csv
Integration tests + Manual testing
Discussed the solution over Slack
None
No
> Enumerator should be able to access only open Form

- lib/model/query/datasets.js
- lib/resources/entities.js
- test/integration/api/datasets.js
- test/integration/api/entities.js
Closes https://github.com/getodk/central/issues/483
Follows suggestions from that PR:
1. Noticed that `Datasets.get()` was getting all datasets including unpublished ones so entities could in some cases be created via API before dataset was published and available (only if they had no data properties, though). 
2. Checked usage of `Datasets.get()` throughout code
3. Made 3rd param `publishedOnly` non-optional and set to false in the only place it matters: when uploading multiple forms that contribute to a dataset and none are published yet. 
- I looked into this case a little more and saw how with this flag set incorrectly (set to only find published datasets), we'd get an extra actee id in the database but it didn't show up in any tests. 
Test and inspecting and agreeing with the …
> Disallow entity creation via API for unpublished datasets

- lib/bin/create-docker-databases.js
- lib/bin/purge-forms.js
- lib/model/query/forms.js
- lib/task/purge.js
- test/integration/task/purge.js
Closes https://github.com/getodk/central-backend/issues/652 and fixes a bug with the flag parsing of the purge script (and enabling the logging in another utility script)
more tests
> Add xmlFormId as option to form purge utility 

- package.json
Closes https://github.com/getodk/central/issues/480
Reverted back engine requirement to major version i.e. 18 instead of patch level
Verified on test env
> fixes c#480: set required engine version to major level (18)

- package-lock.json
Every time I run `make node_modules`, this change is made.  
Ref 73157108a43052f9d1f50b09ae980275d3b7b4be
> package-lock: loosen engines.node in line with package.json

- lib/external/enketo.js
- lib/model/frames/form.js
- lib/model/query/assignments.js
- lib/model/query/audits.js
- lib/model/query/forms.js
- lib/worker/form.js
- test/integration/api/audits.js
- test/integration/api/forms/draft.js
- test/integration/api/forms/forms.js
- test/integration/fixtures/02-forms.js
- test/integration/setup.js
- test/integration/task/reap-sessions.js
- test/unit/external/enketo.js
- test/util/enketo.js
This PR addresses three cases related to getodk/central#385:
- When a form is created for the first time, request an `enketoId` for the draft.
- When a form is published for the first time, request an `enketoId` and `enketoOnceId` for the form.
- When a form is created for the first time and immediately published (via the `?publish=true` flag of the API, thereby skipping a draft), request an `enketoId` and `enketoOnceId` for the form.
These are the last cases to address, so this PR closes getodk/central#385.
I quickly searched the API docs for "Enketo", but I didn't see anything that needed to case.
> Request Enketo IDs during request when form is created or published

- lib/model/query/datasets.js
- test/integration/api/datasets.js
Closes https://github.com/getodk/central/issues/487
This PR makes slight changes to the error messages coming from Backend about problems parsing form XML containing entity definitions.
There is a somewhat generic message for entity form parsing problems that says "The entity definition within the form is invalid" followed by a `reason` more specific to the problem, e.g. what we were seeing before with "Invalid Dataset property." Both parts get passed through to Frontend. I'm not sure localization makes the most sense here because the problem was with `reason` and we probably don't want to maintain translations for all possible reasons for this one case, especially since they are all within the same problem code. 
For this one case about "dataset property", it was easy to change it to …
> Improve error messages about datasets

- package-lock.json
I updated the `systeminformation` package by running `npm audit fix`. `systeminformation` is a subdependency of `pm2`:
```
$ npm ls systeminformation
odk-central@0.1.0
└─┬ pm2@5.3.0
└─┬ pm2-sysmonit@1.2.8
└── systeminformation@5.21.8
```
Just running tests.
Given that the package is a subdependency within the allowed semver range, I'm hopeful that any risk of regression is low.
> Update systeminformation dependency

- README.md
Making this implicit requirement explicit!
> Add Postgres version requirement

- lib/http/endpoint.js
- lib/resources/oidc.js
Spinner source: https://loading.io/css/
Licence: CC0 (public domain)
Closes https://github.com/getodk/central-backend/issues/971
-----
1. initially: centred animated spinner is displayed
2. after 10 seconds: "continue" link fades in below
> oidc: show unbranded spinner on forwarding page

- README.md
> Update API doc format to OpenAPI

- lib/task/db.js
Replace the statement to disable/enable connections. RDS doesn't allow to update `pg_database` catalog. Following links suggest right way to turnoff DB connection is to `ALTER DATABASE`:
https://stackoverflow.com/a/43888064/3633589
https://dba.stackexchange.com/questions/202685/postgresql-cannot-update-pg-database
Verified on dev (AWS) and test (DO) instances
> Updated statement to enable/disable DB connections

- CONTRIBUTING.md
- Makefile
- odk-docs.dockerfile
To help us preview API docs without need to setup getodk/docs repo.
You should be able to see ODK docs by running `make api-docs`
> Added ability to build odk-docs via dockerfile

- Makefile
Added a rule in Makefile to skip @slow test, this is helpful for me during development because most of the time I'm not changing the code which is tested by slow tests like encryption
> added test-fast in Makefile

- lib/http/endpoint.js
- lib/resources/oidc.js
- lib/util/html.js
- test/unit/util/html.js
Alternative approach to https://github.com/getodk/central-backend/pull/1008 & https://github.com/getodk/central-backend/pull/1011.
> oidc: use mustache for templating

- docs/api.yaml
- test/unit/data/odata-filter.js
For getodk/central#503, I'm currently planning to use the OData "not equals" operator in the `$filter` query parameter, something like `__system/conflict ne null`. While looking into that, I noticed that the API docs say that `neq` is the OData operator. However, the operator is actually `ne`: https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_NotEquals. I updated a test to confirm that.
> Clarify that OData operator for "not equals" is ne, not neq

- lib/model/frames/entity.js
- lib/model/query/entities.js
- lib/resources/entities.js
- test/integration/worker/entity.js
Addresses some clunkiness in https://github.com/getodk/central-backend/pull/1005 but I wanted to put it in a separate PR so the meaning of #1005 would be clearer.
There's a 2x2 square of situations and I tried to make the via submission vs. API cases more similar. 
[creating entities, updating entities] x [via submission, via API]
Via API:
* parse data from request
* entity def source is basic, practically empty
* creator is inferred from request auth
* audit logging happens through `createNew.audit` and `createVersion.audit`, which checks that submission def was not provided
Via submission:
* data parsed from submission
* entity def source is complex, based on submission, def, event, etc.
* creator is the submission's creator
* audit logging happens in a submission event processing …
> Refactor Entities.createVersion

- test/integration/api/forms/draft.js
- test/integration/api/forms/forms.js
- test/util/enketo.js
Follow-up PR to #989, adding more tests. Only test/ is changed, not lib/.
#989 included tests of requests to publish an existing form. This PR also tests requests to create a form (either as a draft form or as an immediately published form).
> Test that Enketo IDs are requested during request to create form

- lib/model/query/entities.js
- test/integration/api/datasets.js
- test/integration/api/entities.js
- test/integration/worker/entity.js
- test/unit/data/entity.js
Closes the following issues:
* https://github.com/getodk/central-backend/issues/1009
* https://github.com/getodk/central/issues/510 
* except for offshoot issue: https://github.com/getodk/central/issues/520)
In particular:
**commit 1**
- updated entity-parsing unit tests 
**commit 2**
- moved extra tests of streaming CSVs of entities from `worker/entity` test to `api/datasets` test (multi form and updated entities in particular)
- removed redundant checks and tests from `worker/entity` test file
- added entity update tests to relevant sections of `api/entities` API test file
* returning current version and data of updated entity
* audit log events for an entity
**commit 3**
- added tests of entity processing errors flagged by worker
**commit 4**
- added tests about when submissions about …
> Refactoring entity tests and adding new entity update tests

- docs/api.yaml
- lib/model/migrations/20231013-01-change-entity-error-action.js
- lib/model/query/analytics.js
- lib/model/query/audits.js
- lib/model/query/entities.js
- lib/util/problem.js
- test/integration/api/audits.js
- test/integration/api/datasets.js
- test/integration/other/analytics-queries.js
- test/integration/worker/entity.js
Closes https://github.com/getodk/central/issues/520
Migrate `entity.create.error` to `entity.error` and add new `404.8` Problem with descriptive error about entity UUID not found. Example:
`The entity with UUID (12345678-1234-4123-8234-123456789abc) specified in the submission does not exist in the dataset (people).`
Tests, trying it in frontend.
It makes the most sense to have a generic entity processing error, so all previous `entity.create.error` error events, which were the only possible processing errors before updates, have been migrated to `entity.error`. 
Makes clearer errors. I don't think there are regression risks.
Did make a small change the one place this error was mentioned in the documentation.
> Migrate entity.create.error audit action to entity.error

- lib/data/entity.js
> Add label for getDiffProp comparison

- test/integration/api/datasets.js
Closes getodk/central#516
Forms that update entities vs. creating entities don't get parsed any differently at upload time. The effects these forms have on dataset properties are the same as entity-creation forms. This PR adds a few tests of this behavior. 
I think these tests will be more important to have in place when we get back to this issue: https://github.com/getodk/central/issues/518 (Restrict submissions to the entity actions listed in the form) because that will involve code changes around dataset parsing and form uploading.
> Tests for entity-updating forms modifying dataset properties

- docs/api.yaml
- lib/data/entity.js
- lib/model/frames/entity.js
- test/assertions.js
- test/integration/api/entities.js
- Added `relevantToConflict` field in GET /versions response; this should help in creation of conflict summary table on Entity feed page
- Return the fields that are stored in `entity_defs` table for all Entity related endpoints, except `data` and `dataReceived`
- Updated assertions and API docs to reflect the changes
> Add relevantToConflict field in the GET /versions response

- lib/model/query/entities.js
- lib/resources/entities.js
- lib/util/db.js
- test/integration/api/entities.js
Closes getodk/central#541.
Added a comprehensive test
With this approach Postgresql is responsible for handling concurrency and locking mechanism, and application code remains clean.
Other option was to create an unique constraint on uuid+version and reprocess the submission when there is a violation. I was worried about reprocessing because in that case we would need to refetch the latest Entity version and merge it again that can cause unique constraint violation at the time of insertion.
None
NA
> Lock the Entity while it's being updated

- lib/data/entity.js
- lib/data/submission.js
- lib/model/frames/entity.js
- lib/model/query/entities.js
- lib/util/problem.js
- test/integration/api/entities.js
- test/integration/worker/entity.js
- test/unit/data/entity.js
- test/unit/data/submission.js
Closes [getodk/central#527](https://github.com/getodk/central/issues/527)  by allowing an entity update submission with no `<label>` tag specified. 
Specifying a blank `<label></label>` will be treated as ignoring the label (but only during an update).
Specifying an empty property `<age></age>` can now be used to set that property to blank.
The PR also adds a new Problem for not being able to find the base version of an entity, which should fix this one case of not seeing any error on frontend: https://github.com/getodk/central/issues/536 
tests
should probably add tests for the new individual functions i added, but most of the cases are also tested through higher level tests.
This led me to refactor `validateEntity()`. It used to be that there was some validation spread out through the …
> Don't require label in entity update and allow other blank updates

- lib/data/entity.js
- lib/model/frames/entity.js
- lib/model/query/entities.js
- test/integration/api/entities.js
- test/unit/data/entity.js
Closes https://github.com/getodk/central/issues/514
A submission describing an entity can now set both `create` and `update` flags to true. The submission processing will try to update first, and if it can't find the entity with the specified uuid, it will try to create the entity.
If there is any error besides 404.8 (entityNotFound) when performing the update, it will log the error and stop before trying to create. For example, if the base version is wrong in the update+create, the error will be about not finding the correct base version.
Lots of tests.
> Support updating AND creating entities from a single submission/form

- lib/data/dataset.js
- test/data/xml.js
- test/unit/data/dataset.js
Makes Central support the latests version of the entities xform spec (v2023.1.0). This version is all about submissions that allow (online) entity updates. We wanted a way to alert users that if their form used the new entity update xform spec and they uploaded it into an old version of Central, it would let them know that it couldn't do the updating. 
The xform spec changes between versions was additive, adding the `update=true`, `baseVersion` so this is mostly allowing the new spec version, but it doesn't change how the forms are processed under the hood. 
Tests
Is it too simple? Is there a better "check if version is in acceptable list of versions" snippet of code?
Lets us try entity update forms converted with the latest pyxform!
> Allow 2023.1 entity xform spec version (entity updates)

- lib/model/query/entities.js
- test/data/xml.js
- test/integration/api/datasets.js
- test/integration/api/entities.js
Closes https://github.com/getodk/central/issues/517 by letting `submission.update.version` events also be used to update entities. 
All the scenarios listed in the issue are tested.
I also tested what happens when some submissions that are meant to _update_ entities get picked up in the "pending submissions" when a dataset that requires approval for entity creation gets toggled to no longer require approval. Since we don't know ahead of time which submissions create vs. update entities, we can't really treat them differently here. 
However, entity updates should get processed right away (regardless of if approval is required) so this probably wont come up often. The main situation this comes up is if a entity update submission comes in, the worker hasn't come by to process it yet, and the …
> Trigger entity update on submission edit

- lib/model/query/entities.js
- test/integration/api/entities.js
Closes https://github.com/getodk/central/issues/539
Easy fix, `dataReceived` was available, just not getting used and passed to DB when creating a new entity.
Added some tests
> Capture label in dataReceived for new entities

- lib/model/migrations/20231002-01-add-conflict-details.js
- test/integration/other/migrations.js
Closes https://github.com/getodk/central/issues/540
I debated between adding a new migration that would fill in this data, or changing the old migration file. I decided to change the old migration file, the one that added `baseVersion` and that introduced the column `dataReceived`, to also populate the label field in `dataReceived`. 
I was nervous about getting that change right so I wrote a test, but I've committed the code with the test skipped. 
A test.
I think this is tidier. The change is simple, it'll mean fewer migrations have to run on upgrade. The only downside is some of our test data may not have the label populated. 
no 
no
> Update backfill migration to also set label in dataReceived column

- lib/model/query/datasets.js
- test/integration/api/datasets.js
Related to https://github.com/getodk/central/issues/547
The main code change here is that in the list of submissions to reprocess when toggling the dataset `approvalRequired` flag, submissions that were already processed for some reason and led to an entity processing `entity.error` are now filtered out and not reprocessed.
Two main scenarios: 
1. A submission failed to create an entity, and then the status was changed so there was a new `submission.update` event. Because the first attempt created an error, this will no longer be re-processed.
2. A submission failed to update an entity, and then something with the dataset changed (maybe a non-existent entity came into existence) but that submission wont be reprocessed in the "reprocess all unprocessed submissions" flow. (It was awkward it …
> Tests of reprocessing submissions that yielded entity.error earlier

- lib/data/entity.js
- test/integration/api/entities.js
Resolves the following comment: https://github.com/getodk/central/issues/505#issuecomment-1838953240
> Return correct response for conflict after multiple prior resolutions

- lib/model/query/forms.js
- test/integration/api/datasets.js
Closes https://github.com/getodk/central/issues/554
There are multiple code paths for publishing forms (which is related to https://github.com/getodk/central-backend/issues/755). This only adds this auto linking feature when you have a draft of a form and publish it in a separate API call, because that is the main flow available to Central. The immediately POST a new form and publish is many a dev tool for testing and I didn't want to worry about adding this auto-linking code in both places.
Tests
Used @lognaturel's [create or update form](https://staging.getodk.cloud/#/projects/11/forms/participant_create_update)
See note about making new dataset
See that nothing is attached
See that form uses and updates dataset after being published for the first time
Form works
Entity create/update …
> Auto-link form that creates and consumes dataset on publish

- .github/workflows/oidc-e2e.yml
- .github/workflows/oidc-integration.yml
- .github/workflows/soak-test.yml
- .github/workflows/standard-suite.yml
Without these, a runaway job can continue for the default job timeout of **[6 hours](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes)**.
I've set the timeouts as approximately double the time I've seen for recent ✅ green builds.
> GitHub Actions: set job timeouts

- Makefile
- odk-docs.dockerfile
API-docs container: use env variable for spec path, this fixes issue where git is unable to operate on mounted file.
> API-docs container: use env variable for spec path

- config/default.json
I updated pyxform-http's port to 5000 to match Central's docs because of https://github.com/getodk/central-backend/issues/1000.
But that broke running pyxform-http on macOS because port 5000 is used by [ControlCenter](https://nono.ma/port-5000-used-by-control-center-in-macos-ventura-controlce).
So, I'll be reverting the pyxform-http change, but I think we should also make this change here. I say think because I have no idea the implications for this change in Central.
> Change pyxform-http port because macOS uses port 5000 for ControlCenter

- Makefile
Follow on to https://github.com/getodk/central-backend/pull/1052
I wanted the changes that affect production to go on staging as quickly as possible so left this behind. At the time I was having trouble running the make task because I already had a postgres server running on my machine. The make task would start the container but then would fail when trying to create the `jubilant` role because it already existed in my local db.
I've also switched to the alpine image. I don't think we need any particular utilities to be available and this saves ~40mb in download.
Discarded my existing container and image, ran the make task, verified I could use the db with Central and that the postgres version was 14.10.
This is not really a complete solution because it won't upgrade an existing …
> Upgrade postgres to 14.10 in dev container setup

- test/unit/data/schema.js
Followup to PR https://github.com/getodk/central-backend/pull/1053
Another little test that `SchemaStack` is ok with fields that represent structures but have no children.
> Add little empty structure unit test

- lib/model/query/datasets.js
- test/integration/api/datasets.js
This PR relates to getodk/central#560 and I think is a major part of the issue there. It looks like we weren't excluding deleted entities from extended metadata about the entity list.
You can see this by looking at the example in the issue: https://staging.getodk.cloud/#/projects/62/entity-lists/trees/entities. There, the count of entities is sometimes off by 1. And there is 1 deleted entity: https://staging.getodk.cloud/v1/projects/62/datasets/trees/entities?deleted=true
New test.
> Exclude deleted entities from extended metadata about entity list

- lib/bin/run-server.js
- lib/worker/worker.js
- test/integration/other/analytics-queries.js
- test/integration/worker/worker.js
Closes #533. Instead of running a single worker loop, Backend will now run 4. I didn't change the timing of how a worker waits between work.
Existing tests continue to pass, but tests usually run workers manually (via `exhaust()`). When they do run a loop, it's at most one loop. I think it's hard to really test multiple loops and that the best thing to do is just to get the PR merged before regression testing begins. If we run into performance or other issues during regression testing, we can address them then.
I probably could have called the existing `worker()` function multiple times, but I noticed that each invocation of `worker()` would create functions to `check`, `run`, and `report`. Instead, I created a new function named `workerQueue()` that will create all worker-related …
> Run multiple worker loops

- lib/formats/odata.js
- test/integration/api/odata-entities.js
Closes https://github.com/getodk/central/issues/565 a bug where the entity odata feed didn't work.
Tests, and tested it in Excel for mac!
> Add version and conflict to entity metadata odata spec

- lib/data/dataset.js
- lib/model/migrations/20231208-01-dataset-form-def-actions.js
- lib/model/query/datasets.js
- lib/model/query/entities.js
- lib/model/query/forms.js
- lib/util/problem.js
- test/data/xml.js
- test/integration/api/entities.js
- test/unit/data/dataset.js
Closes getodk/central#518.
New tests.
The permitted actions from the form def are persisted on the `dataset_form_defs` record. It seems like a good idea to persist the actions rather than parsing the form XML each time a submission is processed for entities. `dataset_form_defs` also seems like the right table to store the actions. In the future, a form def will be able to take actions on multiple datasets, and in theory, it could take different actions on the different datasets. So conceptually, the permitted actions aren't per form def: they're per form def + dataset.
Note also that a single form may have different versions/defs that permit different actions. When a submission is processed, the form version specified in the submission will be used.
All existing forms that make changes to …
> Check entity actions in submission against those permitted by form def

- config/default.json
- lib/data/analytics.js
- lib/model/query/analytics.js
- test/integration/other/analytics-queries.js
Closes https://github.com/getodk/central/issues/498
Adds
* `num_entity_updates_sub` (total and recent) entity updates via submission
* `num_entity_updates_api` (total and recent) entity updates via api
* the two above sum together to get the previous metric `num_entity_updates`
* `num_entities_updated` (total and recent) counts the _entities_ updated rather than the update _events_
* can be used to figure out what fraction of all entities ever get updated, and then with the update frequencies, how many updates each has on average 
* `num_entity_conflicts` entities that have ever had a conflict
* how common are conflicts in general? 
* `num_entity_conflicts_resolved` entities that have ever had a conflict that are currently resolved
* do people use entities with conflicts without resolving …
> Usage metrics for 2023.5 about entity updates from submissions and conflicts

- docs/api.yaml
- lib/data/entity.js
- lib/model/query/audits.js
- test/integration/api/datasets.js
- test/integration/api/entities.js
- test/integration/other/migrations.js
- test/integration/worker/entity.js
Closes #1036
It used to be that entity events that were triggered by a Submission (e.g. entity create OR update) would return these objects in the `details`: 
- `sourceEvent` (the actual event that caused the entity update, whether it was a submission approval, or submission creation, etc.)
- `submission` (the Submission object, but only if a Submission was part of the event AND the Submission was not deleted)
- a `submissionCreate` object for the Submission (if a Submission was part of the event) that had enough historical information including the creation time and instance ID to describe the Submission even if it was deleted. 
Now, entity audits (accessed via `/projects/.../datasets/.../entities/[uuid]/audits`) have `details.source`. This looks like
* `source: { submission, event }` …
> Remove submissionCreate from entity audit events

- lib/model/query/audits.js
- test/integration/api/entities.js
This was meant to be part of backend PR https://github.com/getodk/central-backend/pull/1072 but i forgot to push it!! 
Frontend PR https://github.com/getodk/central-frontend/pull/932 expects a source for every entity audit event, even API events, where the source is currently just `{}`.
> Return empty source object for all entity audit events

- docs/api.yaml
- lib/resources/forms.js
- lib/resources/submissions.js
- lib/util/http.js
- test/integration/api/entities.js
- test/integration/api/forms/forms.js
- test/integration/api/submissions.js
* improved server performance in situations where a client re-accesses the same data multiple times
* near-zero implementation cost, as blob hashes have already been fetched from db
* centralises code for serving blobs, which will simplify implementation of:
* support for external storage options
* streaming blob data from db (not currently scheduled AFAIK)
* additional tests
* additional documentation
> Add ETag header to all blobs

- lib/data/entity.js
- lib/model/frames/entity.js
- lib/model/query/entities.js
- test/integration/api/entities.js
I came across this when I was trying to check entity sources created via bulk import. 
In the `/versions` endpoint, the source of each def was getting populated from the audits table, which in general is a good idea.
1. we already have audits around to determine some last conflict resolved event
2. the entity audits query does a bunch of work to fill out the most complete details about an event source, including full submission if it exists, backup submission details if it doesn't, and the corresponding event. 
But, we're about to have entity defs that don't have a single audit event (unless they do/will?) associated with their creation, because one event will likely be shared across multiple new entities. 
We have a way to directly look up an entity def's source, so I added that to the …
> Be able to pull entity version source details from def source table

- .eslintrc.json
- lib/bin/cli.js
- lib/model/migrations/20231002-01-add-conflict-details.js
- lib/model/migrations/20231208-01-dataset-form-def-actions.js
- lib/resources/oidc.js
- oidc-dev/playwright-tests/src/oidc-login.spec.js
- test/integration/task/task.js
- test/unit/util/crypto.js
Keeps the expectation of single quotes for strings, but makes enforcement less strict when:
* a single quote is included inside the string
* template literals (`backticks`) are used when not strictly required
This allows removing all existing inline exceptions for `quotes` rule, except where JSON(?) is directly included in `lib/data/analytics.js`.
> eslint: relax enforcement of string quotes

- docs/api.yaml
- lib/data/odata-filter.js
- lib/http/endpoint.js
- lib/model/query/entities.js
- lib/model/query/submissions.js
- lib/util/db.js
- lib/util/problem.js
- test/integration/api/odata-entities.js
- test/integration/api/odata.js
- test/unit/data/odata-filter.js
- test/unit/http/endpoint.js
Closes #
Adds $orderby support to OData endpoints for Entities and Submissions. This will be useful overall but it is also part of Frontend showing existing entities in the bulk entity creation flow. 
Tests
New feature for users! We've covered a lot of the OData spec at this point!
Documentation has been updated in this PR.
> Orderby support in entity odata endpoint

- docs/api.yaml
I don't think uploading a form attachment API supports `ETag` header.
> docs: upload form attachment does not support etag

- .github/workflows/oidc-e2e.yml
- .github/workflows/oidc-integration.yml
- .github/workflows/soak-test.yml
- .github/workflows/standard-suite.yml
Fixes:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
See: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> ci: upgrade github actions to node 20

- docs/api.yaml
- lib/data/entity.js
- test/integration/api/entities.js
Closes https://github.com/getodk/central/issues/574
Simple change to generate a UUID for an entity of one is not provided. This is currently for the single entity create via API case, but will apply to the bulk create, too.
For entities created with submissions, the parsing path is different so a UUID (generated by the client) is still required. 
For entity API updates, the UUID is specified in the URL, not in the request body, so nothing needs to change. 
Tests.
Short and simple!
Yes, this needs documentation changes. I intend to make those changes in this PR!
> Generate entity UUID if one is not provided in API request

- .github/workflows/oidc-e2e.yml
Extension to 401afdd4599d5931a0b2e3271c1ba8f711411cd5.
Fixes:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> ci: upgrade upload-articact action to v4

- lib/model/migrations/20190917-01-cleanup-app-user-role.js
While working on #1090, I took a look at how previous migrations had updated verbs. I noticed the use of the `+` operator in one migration, but later I realized that that's not actually a valid operator for the `verbs` column, which is `jsonb`. We use the `||` operator in other migrations, so I went ahead and replaced the `+` with `||`. Clearly, the `+` wasn't actually causing any issues: we must never have needed to run the down migration. But it was a little confusing when I was trying to find prior related work and came across the operator.
I didn't do anything to verify the change, since it seems clear that we've never needed to run the down migration. I just wanted to make the code a little clearer and more consistent with other migrations.
> Fix jsonb concatenation in down migration

- docs/api.yaml
- lib/data/entity.js
- lib/model/query/audits.js
- lib/model/query/entities.js
- lib/resources/entities.js
- test/integration/api/audits.js
- test/integration/api/entities.js
- test/unit/data/entity.js
Closes https://github.com/getodk/central/issues/573
Uses POSTing to existing `/v1/projects/1/datasets/people/entities` endpoint so it can handle
* single entities with just `{uuid, label, data}`
* multiple entities with `{entities: [{}, {}], source: {name, size}}`
For the source object,
* `source` is required
* `name` within source is required (not sure if it should be but it will help with displaying on the front end...)
* `size` (meant to represent file size) 
I was thinking about how to handle the bulk SQL insert and decided it was easiest to think/build two separate queries, one for the `entities` table and another for the `entity_defs` table. Elsewhere the code, we have complex queries for inserting a single entity's data into both tables at once, but it didn't seem reasonable to try …
> Bulk entity creation via API

- lib/model/query/entities.js
- test/integration/api/entities.js
Closes https://github.com/getodk/central/issues/582
Tests
The `../entities` REST endpoint was returning entities ordered by entity def id, which doesn't seem very meaningful. That part has been removed and now entities are returned in a stable order that matches the odata endpoint.
I hope no one is relying on that other weird order. It wasn't documented. 
We could keep not documenting the order here. The odata endpoint has a more explicit and controllable query param for ordering entities.
> Change entities REST order to match OData order

- lib/data/entity.js
- test/integration/api/entities.js
- test/integration/worker/entity.js
- test/unit/data/entity.js
I randomly generated some UUIDs but they were v1. I was confused for a bit when I got an invalid UUID error.
Tests
It gives a hint as to what's going wrong without making invasive changes.
None, text only.
No.
> Specify that entity uuids need to be version 4

- lib/model/frames/entity.js
- lib/model/query/entities.js
- lib/util/db.js
- test/unit/util/db.js
Related to https://github.com/getodk/central-backend/issues/1095 
Happy to report that I was able to insert 500,000 entities w/ 10 properties in about ~30 seconds (on my M3 mac) with this `sql.unnest` change. 
That payload was about `76,000KB` (76MB) and this limit was increased to `250000kb` (250MB)
[service.use(bodyParser.json({ type: 'application/json', limit: '250kb' }));](https://github.com/getodk/central-backend/blob/a04caadcb9052105b03e6be4e431c8f1923b1f4c/lib/http/service.js#L33-L34)
Tests of small insertions still work. 
I tried it on my own with those larger numbers.
There is still more to do to create many entities at once (streaming JSON?), but I think it's worth merging this particular change now so the bottleneck is no longer the database insert.
> Use sql unnest to optimize entity insertion

- lib/util/http.js
- test/unit/util/http.js
Closes #806
I have ran `make test-unit` and all the test passed
It was the most straight forward solution. No other approaches were needed, just letting the function consider string only
It doesn't affect much, the function now is doing what is was supposed to do, which is check for string types only.
No
> Bug Fix for `istrue` & `isfalse` utility function

- docs/api.yaml
- lib/model/migrations/20240312-01-add-dataset-create-verb.js
- lib/model/query/datasets.js
- lib/resources/datasets.js
- lib/util/db.js
- test/integration/api/datasets.js
Backend part of these two issues:
https://github.com/getodk/central/issues/575
https://github.com/getodk/central/issues/576
Two new endpoints
**`POST /v1/projects/1/datasets`**
`{ name: 'trees' }`
**`POST /v1/projects/1/datasets/trees/properties`**
`{ name: 'height' }`
Still to do:
Tests.
I considered a different endpoint for adding properties. Maybe POSTing an array properties to a dataset, or PATCHing the dataset, but it didn't feel right. One reason is the existing `PATCH .../dataset/:name` endpoint is used for setting the `approvalRequired` flag, which feels like it's at a different level than dataset properties. Dataset properties have more to them, and they seem to deserve their own endpoint with `POST .../properties`.
We could have a matching `GET .../properties`, but for now, the …
> Create new dataset (entity list) or property via the API

- lib/data/briefcase.js
- lib/formats/odata.js
- lib/http/endpoint.js
- lib/http/service.js
- lib/model/container.js
- lib/model/frames/config.js
- lib/model/frames/form.js
* remove `!= null` where unnecessary
* replace `x != null && x.y ===` with `x?.y ===`
* replace `x != null ? x :` with `x ??`
This should help with readability.
> Simplify various null comparisons

- lib/http/service.js
- test/integration/other/http-headers.js
Follows the OWASP recommendation: https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#x-powered-by
This is not super important because there are many other ways to learn about the stack but it does get flagged by some security scanners.
Ran it, looked at headers in console
I think this is the only approach!
Should have no risk of negative effect.
No.
> Remove X-Powered-By header

- docs/api.yaml
Copied it in to docs repo, ran
`make autobuild`, 
Then checked links with
`muffet --buffer-size 16000 --skip-tls-verification http://127.0.0.1:8000 --include=central-api`
The only broken link was `#openrosa-form-manifest-api` which I think is new/incomplete?
I had to make some educated guesses about some of the correct links, so please review carefully!
Better to have links than not.
> Fix broken links in docs

- lib/model/migrations/20240322-01-add-entity-source-index-to-audits.js
- lib/model/query/audits.js
Entity details page was getting really slow. `/audits` and `/versions` endpoints in particular were really slow (order of seconds on test server). Both endpoints use `Audits.getByEntityId()`.
Looking into it, when I updated the entity audit query to use the new `sourceId` for bulk entity uploads, this definitely impacted the query's performance.
https://github.com/getodk/central-backend/commit/f98187d76307dafe76482a882beba16854008c9f?diff=split&w=0#diff-754724053d58d67c63f58d13d8708e4d185a11bb2d172614693cc3f611bb5361R171
The code used to filter on `audits.details->>'entityId'`, which we had an index for. Now, not every audit log will reference an entity directly. Instead, we look up audits by `audits.details->'entityDefId'` or `audits.details->'sourceId'` in a different part of the query. …
> Update db index on entity audit query to use entityDefId and sourceId

- docs/api.yaml
In response to https://github.com/getodk/docs/pull/1761
Header will hopefully reduce confusion as to where the yaml file is managed
I think what happened with the success responses is that there are a couple of bogus example routes like [here](http://localhost:8000/central-api-authentication/#using-the-session) that show session auth. Those used to have sample responses `"message": "Success"`. It got made into a component and then it mistakenly got used.
Since those responses are fake anyway, I made them consistent with the others. I replaced every identical success response with use of the component.
> API docs improvements: fix typo, add header, correct success responses

- lib/formats/openrosa.js
- lib/model/query/datasets.js
- lib/model/query/form-attachments.js
- lib/resources/datasets.js
- lib/resources/forms.js
- test/integration/api/datasets.js
Closes https://github.com/getodk/central/issues/599
This PR attempts to unify how the ETag and OpenRosa form attachment md5 is computed for entity lists/datasets, which is the mechanism for telling clients whether they need to refetch the entity list.
This hash used to be computed from the most recent `updatedAt` timestamp of an entity in the Dataset, or `1970-01-01` for a Dataset with no entities, but this didn't account for deleted entities or new dataset properties.
This value is now a hash of the last dataset-related event (the hash of the `loggedAt` timestamp on the most recent Audit log event with the Dataset as the Actee. This is more robust to any Dataset event, like properties being added, or entities being modified or deleted. 
It is a less direct database lookup, but there was …
> Change entity list ETag to use timestamp of last dataset/entity event

- docs/api.yaml
The `Service Document` endpoint for datasets was missing an example 200 response:
https://docs.getodk.org/central-api-odata-endpoints/#id1
- Previously we had: `content: {}`.
- Updated to include actual content.
Loaded the yaml into https://editor.swagger.io/
- I assume this will be copied to getodk/docs, so is user facing.
- I think this PR template needs an update to reference `docs/api.yaml` ! 😄
> Add example content to OData `/datasets/{name}.svc` 200 response

- lib/http/service.js
- package-lock.json
- package.json
- test/integration/api/entities.js
Part of https://github.com/getodk/central-backend/issues/1095
Adds custom middleware to use a higher JSON size limit for `bodyParser` middleware for the specific entity bulk creation route.
Uses `path-to-regex` to match the route, because I think that is what express is using internally, so this dependency should technically already be included.
> Apply increased json body limit to entity post endpoint

- .github/PULL_REQUEST_TEMPLATE.md
api.md was replaced by api.yaml in #955, but the PR template still references api.md. This PR updates the template to reference api.yaml instead.
> Update api.md to api.yaml in PR template

- lib/model/query/audits.js
Hopefully addresses https://github.com/getodk/central/issues/618
I ended up pulling out the crazy part of this query that gets all the submission details that are vaguely relevant to an entity. It is now in another query that gets run separately and then if there is submission data to use, it is combined in code.
I'm curious to try this on test! I've been `EXPLAIN ANALYZE`-ing the queries. Hopefully an entity with a bulk source loads _super_ fast, single milliseconds.
https://test.getodk.cloud/#/projects/496/entity-lists/participants/entities/b5725bd9-fb5f-41e0-ba30-0eb8e6905e07
Original query (master)
* Planning Time: 10.761 ms
* Execution Time: 1357.950 ms
(I've seen it 800ms to >2 seconds)
New queries
Part 1: get all audit details and source events
* Planning Time: 2.093 ms
* Execution …
> Improve entity details audits query

- lib/model/query/datasets.js
- lib/util/problem.js
- test/integration/api/datasets.js
Closes https://github.com/getodk/central/issues/627
Prevents Forms and Dataset API from introducing published datasets with conflicting names, specifically the same name with different capitalization. 
* Error on _Form Upload_ if dataset name conflicts with a published dataset
* Error on _Form Publish_ if publishing will introduce a conflict, which can happen if there were multiple draft forms with different name variations, one was published, and then a second is attempted to be published.
* Error on "New Entity List" / API if dataset name conflicts with a published dataset
* Now allowed to create/publish a dataset that directly collides with an unpublished dataset
Tests, trying with frontend.
I basically added another database query for a similarly named dataset. In the same area of …
> Prevent Forms from introducing dataset name case conflicts

- config/default.json
- lib/data/analytics.js
- lib/model/query/analytics.js
- test/integration/other/analytics-queries.js
Backend of https://github.com/getodk/central/issues/572
Adds
* num_bulk_create_events (recent and total)
* biggest_bulk_upload
Tests, trying it.
I'm starting to get concerned about how slow these analytics queries get on servers with a lot of entities, but this will also not happen that frequently, and there is a lot of different information being calculated.
No.
> Usage metrics for release v2024.1

- lib/model/query/datasets.js
- test/integration/api/datasets.js
Closes getodk/central#645.
New test.
The code change is to a SQL query. The query is relatively simple, and existing tests continue to pass, so I think the risk of regression is low.
> Exclude form drafts from linkedForms

- docs/api.yaml
I noticed that https://docs.getodk.org/central-api-entity-management/#updating-an-entity has a 403 example with code and message both set to `pencil`. I imagine that's some fallback when no examples are specified.
We have a nice schema template for 403 errors so I went through and used that everywhere.
Some endpoints like the one above had 403s defined with json and json/extended response types. In those cases, I removed the `json/extended` one.
Some endpoints redundantly specified an example along with the schema reference which itself specifies the same examples. I removed the redundant ones.
Some endpoints have 403 responses with other response types (e.g. https://docs.getodk.org/central-api-form-management/#draft-form). I think that's also a mistake but didn't want to look too deeply …
> Use schema template for 403 errors

- test/integration/task/purge.js
The logic as to when indentation should be increased isn't clear to me, but this removes lint exceptions with minimal change to surrounding code.
> test/purge: resolve lint exceptions: no-shadow

- package-lock.json
- package.json
- test/e2e/soak/index.js
`fetch()` global has been available since node v18.  It is still officially "experimental" until node v21, but it seems reasonable to use it in development before then.
See: https://nodejs.org/api/globals.html#fetch
This avoids https://github.com/node-fetch/node-fetch/issues/1735, which I've seen locally when working with e2e tests.  However, it does seem like global `fetch` can exhibit a similar but much less frequent issue.
> remove dev dependency: node-fetch

- lib/model/query/keys.js
Closes https://github.com/getodk/central/issues/658
Query is more readable and much faster, especially in the case where there are no keys to return.
> Optimize submission keys query

- lib/model/frames/entity.js
- lib/model/migrations/20240515-01-entity-tz-precision.js
Closes https://github.com/getodk/central-backend/issues/1104
Makes `deletedAt` field on `entities` table have consistent timestamp type.
In this [issue](https://github.com/getodk/central-backend/issues/459), we chose to use `timestamptz(3)` for timestamps, but that was missed when creating this column in this table and it was just set to `timestamp`.
> Change entities deletedAt precision and add timezone

- lib/model/query/datasets.js
- lib/model/query/forms.js
- lib/resources/forms.js
- lib/util/db.js
- lib/util/problem.js
- test/integration/api/audits.js
- test/integration/api/datasets.js
- test/integration/api/forms/draft.js
- test/integration/api/forms/forms.js
- test/integration/fixtures/02-forms.js
- test/integration/other/form-versioning.js
- test/util/enketo.js
Closes https://github.com/getodk/central-backend/issues/1136
This PR consolidates Form publishing in one place, because Dataset publishing is tied to Form publishing. There were three different places to _possibly_ publish a Dataset (creating a new form, updating a form, just publishing a form) and it was too hard to think about which Form scenario led to which Dataset scenario. 
---
As of 5/10/24:
So far, I've removed `publish=true` from `Forms.createNew()`.  Any time creating a new form was also going to publish the form, the `Forms.publish()` is now called separately. 
One downside is that those lines of code aren't as cute and concise anymore. This only happened in one resource, in a test fixture, and in some tests.
Another downside is that the enketo test mock had a way to put it …
> Remove use of conditional publish from Forms.createNew

- .circleci/config.yml
This PR updates CircleCI to check for large files. Any large files will be listed.
CircleCI passes currently, but if I reduce the limit from 1 MB to 100 kB, then it fails. See https://app.circleci.com/pipelines/github/getodk/central-backend/2186/workflows/e2e9689b-4e3a-4c28-80bd-392837ccb9d3/jobs/3046 for an example of that.
I'll add a few line comments.
> Check for large files in CircleCI

- lib/formats/openrosa.js
- test/integration/api/datasets.js
Part of https://github.com/getodk/central/issues/665 and larger issue https://github.com/getodk/central/issues/668
Adds **type=”entityList”** to manifest for attachments that are actually datasets/entity lists. (integrityUrl coming next.)
```
<mediaFile type=”entityList”>
<filename>people.csv</filename>
<hash>md5:9fd39ac868eccdc0c134b3b7a6a25eb7</hash>
<downloadUrl>http://other.appspot.com/blobSource?foo=222</downloadUrl>
<integrityUrl>http://blah</integrityUrl>
</mediaFile>
```
> Specify mediaFile type=entityList for datasets in form manifest

- docs/api.yaml
I noticed that there's a mix of literal $ and %-encoded %24 used. The %24 are not rendered correctly. See for example the request table for https://docs.getodk.org/central-api-odata-endpoints/#data-document
Rendered using `make api-docs` (🫡 @sadiqkhoja), spot checked and saw $ as expected.
I considered modifying the docs code to decode values but given that several literal $ already exist and that literal values work without replacement, that didn't feel like the best option.
Could break some docs.
> Don't encode %24 in docs

- lib/model/frames/entity.js
- lib/util/db.js
- test/unit/util/db.js
I noticed this after adding a property to the Entity frame and then trying to "insertMany" entities. 
It's not the `createdAt` timestamp type that gets rearranged in the insertMany query, it's the _last_ type because `indexOf(['createdAt'], Type.insertfields` (with the brackets) always returns -1. `indexOf('createdAt',...` works as intended. Fixing this also led me to fix the typo of `timestampz` in the Entity frame that wasn't being surfaced before.
Added a new test, which I verified failed before the code change.
I don't think there was previously a scenario to trigger this bug before. It didn't come up if the last type in a Frame was a timestamp, or if the Frame didn't have a createdAt.
> Fix bug with insertMany, createdAt, and entity timestamp

- lib/model/query/entities.js
- test/integration/api/entities.js
Collecting smaller changes I want to make before committing to a offline entity spec.
> Minor code improvements to entity processing

- lib/model/query/datasets.js
- test/integration/api/datasets.js
Closes https://github.com/getodk/central/issues/612
> Check dataset verbs in endpoints about forms

- test/integration/api/datasets.js
> Fixing leftover .only mistake in a tests

- .eslintrc.json
- package-lock.json
- package.json
- test/integration/other/migrations.js
It would help if I had the linter yell at me for leaving in .only tests.
> Add eslint-plugin-no-only-tests to flag leftover .only tests.

- lib/model/query/blobs.js
The comment suggested modifying a migration which has since been released.  If there is a problem with the migration, it should be fixed with a subsequent migration.
> query/blobs: delete comment ref copy/pasted code

- lib/data/entity.js
- lib/model/frames/entity.js
- lib/model/migrations/20240607-01-add-offline-entity-branch-trunk-info.js
- lib/model/migrations/20240607-02-add-submission-backlog.js
- lib/model/query/entities.js
- lib/worker/jobs.js
- test/data/xml.js
- test/integration/api/offline-entities.js
- test/unit/data/entity.js
Possible backend solution for https://github.com/getodk/central/issues/669 
[XML form](https://drive.google.com/file/d/1G3rPaca3d34XpVgdaEvd_S1451EuEX4U/view?usp=sharing) that allows branch id / base version / trunk version to be set.
> Handle offline entities with baseVersion and trunkVersion

- test/integration/api/forms/forms.js
There were previously two adjacent tests both called:
> should return the xlsx file originally provided
> test/integration/api: de-duplicate test name

- lib/model/query/entities.js
- test/integration/api/offline-entities.js
Small followup to https://github.com/getodk/central/issues/669 
Prevents submissions that are being held for later processing (because of offline entity ordering) are not mishandled
- not reprocessed an extra time
- not re-enqueued
- not causing errors
This PR also tests the (expected) behavior that if an offline branch included create and update, and the dataset required approval before creating the update, that the update would be held until the create submission was approved and applied. (Though it gets pretty hairy on the Collect side to think about keeping all of this information/state in sync when combining approval required + offline. See [forum post](https://forum.getodk.org/t/openrosa-spec-proposal-support-offline-entities/48052) about ideas for syncing.)
> Check approvalRequired reprocessing with offline entity queue

- lib/model/query/audits.js
- test/integration/api/audits.js
- test/integration/api/offline-entities.js
Closes https://github.com/getodk/central/issues/686
- don't include in nonverbose audit logs
- don't include in the audit logs for a specific submission
> Suppress submission.reprocess from audit logs

- lib/data/entity.js
Per https://getodk.github.io/xforms-spec/entities.html#declaring-that-a-form-creates-entities:
> MUST have attribute id populated by a RFC 4122 version 4 UUID
> entity: add comment explaining UUID regex

- lib/model/migrations/20240715-01-backlog-add-event-entityuuid.js
- lib/model/query/entities.js
- test/integration/api/offline-entities.js
This is meant to be a precursor to another PR for issue https://github.com/getodk/central/issues/682
The main changes here are
* Migration to add more useful columns to submission backlog
* Reordering and reorganizing code in entity query module
* Changing flow of `Entities._updateEntity` to try to determine the base version of an entity _before_ it looks up the existing server version, because this helps with the logic of holding submissions for later processing, and will eventually help with the force-processing case. 
* Removes `branchId` from tests about creating entities
> Improvements to offline entity backlog processing

- lib/model/query/entities.js
I noticed the same issue I had before come up in a slightly different place: https://staging.getodk.cloud/#/projects/21/forms/cactus_monitoring/submissions/uuid%3A7f406fd6-a7ab-4b7d-9cde-b91e465e56fc
I should probably think of a way to test these tasks better, either with an e2e test, or by doing something to the testing framework. The testing framework currently doesn't let you use the API to set up a test scenario for the cli scripts.
> Adding promise resolution to createNew audit logger

- lib/model/query/entities.js
- test/integration/api/offline-entities.js
Changing entity submission backlog duration from 7 days to 5 days. 7 days felt too long to wait.
> Rename taskSchedule.entitySubmissionBacklog config and default to 5 days

- lib/model/query/datasets.js
- test/integration/api/datasets.js
Closes https://github.com/getodk/central/issues/695
When an entity list property was created through a draft form, it inserted a row of (datasetId, name, publishedAt) with null `publishedAt`. The query to insert a new property via the API (which would also immediately publish that property) flagged any new property insertion as a a conflict. The query has been updated to act as an upsert that will publish an unpublished property instead of failing.
> Allow property name from deleted form to be used in entity list

- Makefile
Enable statement logging in local PostgreSQL docker containers launched with `make run-docker-postgres`.
This is very helpful if trying to understand exactly what SQL queries are being made, and fiddly to enable.
> dev/postgres: log statements

- lib/model/query/forms.js
CTE results are materialised, so this change should make the query faster & use less resources.
> forms.purge(): don't return unused columns

- lib/bin/s3.js
- lib/model/query/blobs.js
- lib/task/s3.js
- test/integration/task/s3.js
Closes https://github.com/getodk/central/issues/703
> lib/bin/s3: add limit to upload-blobs

- package-lock.json
- package.json
Closes https://github.com/getodk/central/issues/652
When I first ran npm audit:
```
body-parser  <1.20.3
Severity: high
body-parser vulnerable to denial of service when url encoding is enabled - https://github.com/advisories/GHSA-qwcr-r2fm-qrc7
fix available via `npm audit fix --force`
Will install express@4.21.0, which is outside the stated dependency range
node_modules/body-parser
express  <=4.19.2 || 5.0.0-alpha.1 - 5.0.0-beta.3
Depends on vulnerable versions of body-parser
Depends on vulnerable versions of path-to-regexp
Depends on vulnerable versions of send
Depends on vulnerable versions of serve-static
node_modules/express
braces  <3.0.3
Severity: high
Uncontrolled resource consumption in braces - https://github.com/advisories/GHSA-grv7-fg5c-xmjg
fix available via `npm audit fix …
```
> Upgrade backend dependencies

- README.md
- lib/model/migrations/20240913-01-add-blob-s3.js
- lib/task/s3.js
Only require pgrowlocks extension in testing, because installing/creating the extension can require more privileges than other migrations.
> s3: remove PGROWLOCKS extension from db-migrations

- test/integration/api/datasets.js
- test/integration/other/analytics-queries.js
> Unskip tests by preventing additional entity.error

- config/default.json
- lib/data/analytics.js
- lib/model/query/analytics.js
- test/integration/other/analytics-queries.js
Closes https://github.com/getodk/central/issues/653
Example of new metrics:
```
num_offline_entity_branches: 1,
num_offline_entity_interrupted_branches: 1,
num_offline_entity_submissions_reprocessed: 1,
max_entity_submission_delay: 0.022,
avg_entity_submission_delay: 0.015
```
This covers these metrics:
- 1\. Number of offline branches involving more than one update
- 2\. How many branches were interrupted in the middle of being processed?
- 3\. How many submissions were put in the backlog just long enough for updates to be processed in the correct order? In other words, how many `submission.reprocess events` have there been?
- 6\. How long does it take for an entity change to be processed? What is the max amount of time between when the submission was created and the entity version was …
> Backend usage metrics (offline entities) for 2024.2

- docs/api.yaml
Closes https://github.com/getodk/central/issues/659
Very exciting!
> API docs for 2024.2, mainly submission deletes

- .gitignore
- lib/bin/repl.js
- lib/bin/run-server.js
- lib/util/default-container.js
Example use:
./lib/bin/repl
Available vars: Actees, Actors, Analytics, Assignments, Audits, Auth, Blobs, ClientAudits, Comments, Configs, Datasets, Entities, FieldKeys, FormAttachments, Forms, Keys, Projects, PublicLinks, Roles, Sentry, Sessions, SubmissionAttachments, Submissions, Users, all, db, enketo, env, mail, maybeOne, maybeOneFirst, one, oneFirst, run, s3, sql, stream, with, xlsform
> await db.any(sql`SELECT * FROM blobs`)
[]
> bin/repl: run NodeJS REPL with initialised container

- lib/worker/worker.js
- test/integration/api/offline-entities.js
This PR adds a test for getodk/central#705. It runs the race condition described in the issue many times, asserting that it is successful each time.
The test in #1033 takes a more explanatory approach, beginning transactions manually and controlling the timing of queries. I think that test is helpful, but it didn't seem useful to just copy it for this new issue. It's also not easy to control the timing of `Entities._processSubmissionEvent()`, which I think would be needed in order to write such a test.
The test that I wrote runs the race condition described in the issue. Even without locking, things occasionally work fine: the offline update doesn't end up stuck in the backlog. That's the case <10% of the time on my local machine. Given that things sometimes work, I run the race condition …
> Test concurrent submissions that affect same entity

- README.md
If I run tests locally using a database that doesn't have `pgrowlocks`, I see an error message:
```
task: s3
s3 disabled
✔ uploadPending() should fail
✔ setFailedToPending() should fail
✔ getCount() should fail
s3 enabled
getCount()
error: function pgrowlocks(unknown) does not exist
...
Error: cannot count blobs by status due to missing PostgreSQL extension: PGROWLOCKS.
To install this extension, execute the following query in your PostgreSQL instance:
CREATE EXTENSION IF NOT EXISTS pgrowlocks;
```
The instructions here are clear, and tests pass once I create the extension in my test database. However, I think it'd be worth preventing the error by creating the extensions at the time of database setup. The readme includes instructions to manually set up the databases, and this PR adds the …
> Add pgrowlocks to instructions for manually setting up databases

- test/integration/task/s3.js
Hopefully closes https://github.com/getodk/central-backend/issues/1208 
Did a bunch of sleuthing and saw that `uploadPending` was trying to upload 0 pending blobs. I overlooked `aBlobExistsWith` at first because I thought it was checking an assertion or something, but when I finally revisited what it was really doing (inserting a blob), I noticed this way in which it could be contributing to failing tests. 
This would not have been possible without the previous PR (https://github.com/getodk/central-backend/pull/1213) to clean up around the tests, so thanks!
> Fix intermittently failing S3 test

- lib/data/entity.js
- lib/model/frames/entity.js
- lib/model/query/entities.js
- test/integration/api/entities.js
- test/unit/data/entity.js
- test/unit/model/frames/entity.js
Closes https://github.com/getodk/central/issues/727
Thanks for the example test, @sadiqkhoja! I used it to debug and then made a simplified test.
When create and update are both present in an entity, Central first tries to update and then tries to create if the update failed in a certain way. 
In this scenario, the update step was failing at the parsing step. The update flag in the entity system data is set to true, but there is no base version, and that causes an error. The code changes how the parsing works a little bit to not use what is written in the entity system data directly, but to use the context of whether it is currently trying to update or create. A similar change was made to the label parsing method.
> Handle missing baseVersion in entity upsert (create and update) case

- test/integration/other/blobs.js
Adds a passing test for de-duplication of two blobs with identical content & mime type, but different filenames.
> test/blobs: add explicit test for de-duplication

- lib/data/schema.js
- lib/model/frames/form.js
- lib/model/migrations/20241010-01-schedule-entity-form-upgrade.js
- lib/model/query/audits.js
- lib/model/query/forms.js
- lib/worker/form.js
- lib/worker/jobs.js
- test/integration/other/form-entities-version.js
- test/integration/other/migrations.js
- test/unit/data/schema.js
- test/util/xlsform.js
Closes https://github.com/getodk/central/issues/692
> Alter entity spec version and add branchId, trunkVersion in form schema

- test/e2e/standard/run-tests.sh
Fixes https://github.com/getodk/central-backend/actions/workflows/standard-e2e.yml.
It looks like the final cleanup kills the process itself.
Locally this returns exit code `0`, but on CI it returns `1`.
> ci: test/e2e/standard: fix kill_child_processes()

- docs/api.yaml
- lib/data/odata-filter.js
- lib/data/odata.js
- lib/data/submission.js
- lib/formats/odata.js
- lib/model/frames/submission.js
- lib/model/query/submissions.js
- test/integration/api/odata.js
- test/unit/data/odata-filter.js
- test/unit/data/odata.js
- test/unit/formats/odata.js
Part of getodk/central#709
- Added unit and integration tests. 
- Manually verified with the frontend.
- Checked with Excel to ensure there's no regression.
I have added `__system/deletedAt` field in the OData response and made it filterable. If client’s `$filter` expression doesn’t contain `__system/deletedAt` related clause then default `__system/deletedAt eq null` is added.
This approach keeps our Odata API consistent with respect to other system fields and quite useful for clients who are interested in filtering Submissions by deletedAt column. Maybe in future we also want to add this on the frontend.
Other option was to add a special filterable boolean field `__system/deleted`, which is simple but doesn't come with the benefits mentioned above.
OData spec doesn’t have anything …
> Update Submissions OData to include `deletedAt`

- test/util/zip.js
This should make tests fail faster, and make failures easier to understand:
Previously: `Error: end of central directory record signature not found`
Now:        `Error: expected 200 "OK", got 400 "Bad Request"`
Related:
* https://github.com/getodk/central-backend/issues/595
* https://github.com/getodk/central-backend/issues/588
* https://github.com/getodk/central-backend/pull/1052
> test/httpZipResponseToFiles: don't unzip non-zip responses

- lib/data/entity.js
- lib/model/query/entities.js
- test/integration/api/offline-entities.js
Closes https://github.com/getodk/central/issues/698
This PR makes two changes:
**1: Update per-version conflict state**
The `<entity uuid>/versions` endpoint returns a `conflict` state for each version of the entity, which is computed from other information about the entity versions. These values should stay the same even when the top level `conflict` flag on the entity changes (or is manually resolved). These version-specific conflict states used to be detected just from `baseVersion+1 != version`. 
In this PR, we've copied branch-tracking logic from Frontend to check whether each version if it is contiguous with its trunk version, and return a `soft` conflict state if it is non-contiguous but otherwise not a hard conflict.
We could also consider having backend return more of the details …
> Mark soft conflict if not contiguous with trunk

- test/integration/other/encryption.js
Also mark these tests as @slow.
* these tests have been seen to time out on CI
* these tests time out around 10% of the time on my machine
Closes #1249
> test/encryption: increase end-to-end test timeouts

- test/unit/http/endpoint.js
- test/unit/http/middleware.js
- test/unit/http/preprocessors.js
- test/util/node-mocks-http.js
odk-central-backend uses express's default querystring parser (qs), whereas node-mocks-http uses querystring.
See: https://github.com/eugef/node-mocks-http/issues/299
> test/unit: match real querystring processing

- lib/data/schema.js
- lib/model/migrations/20241029-01-schedule-entity-form-upgrade-create-forms.js
- lib/worker/form.js
- test/integration/other/form-entities-version.js
- test/unit/data/schema.js
Closes https://github.com/getodk/central/issues/757
* adds a new migration that flags all the _other_ entity forms in the table `dataset_form_defs` (forms that reference datasets but don't update)
* adds form migration code that can transform a v2022.1 form into a v2024.1 form by changing the entity spec version and adding a suffix to the form version
* every flagged form is upgraded to the 2024.1 version by trying both 2022 and 2023 upgrades (which have no effect if the specific old version is not found)
I *could* have gone back and changed the existing migration, but since this has already been applied on the QA server, it seemed ok to just add another migration.
> Include entity create 2022.1 forms in 2024.1 upgrade

- .eslintrc.json
- lib/data/schema.js
- lib/data/submission.js
Enforced via making the `exited` prop private.
This makes use of "private properties", which have been available since node 12(?).
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties
Eslint's ecmaVersion needed updating to allow eslint to parse `lib/data/schema.js`.
>  SchemaStack: use .hasExited() consistently

- lib/data/entity.js
- lib/model/frames/entity.js
- lib/model/query/entities.js
- test/unit/data/entity.js
We (myself, QA, LN, etc.) have been noticing lately that entity lists, both in frontend and in forms in enketo, have been taking an uncomfortably long time to load.  
* staging: [dataset with 1 entity taking 10 seconds to load](https://staging.getodk.cloud/#/projects/118/entity-lists/movies/entities)
* staging (same dataset as above): [form taking 10 seconds to load](https://staging.getodk.cloud/-/preview/Zk1RSkRhv6avflpna68snsVGynPRMfr)
* staging [dataset with 20 entities taking >10 seconds](https://staging.getodk.cloud/#/projects/103/entity-lists/cacti/entities)
* staging [dataset with 60K entities, loading 250 of them taking 10 seconds](https://staging.getodk.cloud/#/projects/93/entity-lists/entities_60k/entities)
* QA: [dataset 2 entities taking 1 second to …
> Speed up entities query for dataset CSV export and entity OData

- test/unit/http/endpoint.js
- test/util/node-mocks-http.js
* always include a functional EventEmitter in mocked responses
* remove "modern" wrappers which duplicate functions now available in node-mocks-http by default
> test/unit: simplify HTTP mocks

- lib/util/util.js
- test/unit/util/util.js
#1214 changed the implemention of `base64ToUtf8()` from `btoa(...)` to `Buffer.from(...)`.  This also introduced a change in behaviour, which did not trigger any test failures.
This commit reverts to behaviour similar to the previous version while continuing to avoid the deprecated `btoa()` function.
RFC4648 states:
> Implementations MUST reject the encoded data if it contains characters outside the base alphabet when interpreting base-encoded data, unless the specification referring to this document explicitly states otherwise.
See: https://datatracker.ietf.org/doc/html/rfc4648#section-3.2
> base64ToUtf8(): reject invalid characters

- lib/http/preprocessors.js
- lib/util/http.js
- test/unit/http/preprocessors.js
- test/unit/util/http.js
Related:
* https://github.com/getodk/central-backend/pull/1269
* https://github.com/getodk/central-backend/pull/1268
* https://github.com/getodk/central-backend/pull/1267
* https://github.com/getodk/central-backend/pull/1270
Ref #1260
> CSRF token: handle failed url-decoding

- Makefile
- lib/http/endpoint.js
- test/integration/other/http.js
Previously, non-url-decodable paths would return 500.
> http/endpoint: handle URL-decode errors

- lib/data/odata.js
Avoid using `encodeURIComponent()` directly in template string.
> data/odata: use url`` template literal

- lib/model/query/audits.js
- lib/util/problem.js
- test/integration/api/audits.js
Related:
* https://github.com/getodk/central-backend/pull/1269
* https://github.com/getodk/central-backend/pull/1267
* https://github.com/getodk/central-backend/pull/1265
* https://github.com/getodk/central-backend/pull/1270
> audit-logs: handle bad url-encoded X-Action-Notes header

- lib/model/query/blobs.js
- lib/resources/user-preferences.js
- lib/task/analytics.js
- lib/util/option.js
- test/integration/api/datasets.js
- test/unit/util/option.js
Guard against none-unsafe derefences of Option values.
This change requires implementation of support for Ramda's `.equals()` function for `Option.of(...)`, which incidentally worked previously due to the underlying implementation.  The main motivation for implementing `.equals()` support is that there are various places in the code which use `Ramda.isEmpty()` instead of `Option.isEmpty()`.  These are likely mistakes, but there is no obvious, elegant way to detect these mistakes.
> Option: block direct access to .value

- lib/http/preprocessors.js
Cookies are already url-decoded by `cookie-parser`, introduced in #910.
Alternative to https://github.com/getodk/central-backend/pull/1269
> http: don't double-decode session cookie

- test/unit/http/preprocessors.js
These tests were always passing because their assertions were contained in unreturned promises.
Related:
* https://github.com/getodk/central-backend/pull/1269#discussion_r1835442470
* https://github.com/getodk/central-backend/pull/1285
> test/preprocessors: return promises

- lib/model/frames.js
- lib/model/query/form-attachments.js
- test/integration/api/forms/draft.js
- test/integration/api/forms/forms.js
- test/integration/api/forms/versions.js
- test/integration/other/form-entities-version.js
Closes https://github.com/getodk/central/issues/758
Exposes the property `hash` on form attachments, which is set to:
* null if the attachment is a dataset or if the attachment blob is empty
* the `md5` hash value of the attachment blob file
Unlike the OpenRosa hash for the form manifest, this value is set to null for dataset attachments and doesn't change when a dataset has more entities added/updated.
yes, need to add to docs.
> Expose md5 hash of file attachments through api

- test/unit/http/endpoint.js
Introduced in #403 / 6e075a345b80041dae7c8156e10219fa0a606b21, this appears to be an outdated workaround for different behaviours in legacy node versions.
> test/http/endpoint: remove cryptic node14 reference

- .circleci/config.yml
- .github/workflows/oidc-integration.yml
- .github/workflows/s3-e2e.yml
- .github/workflows/soak-test.yml
- .github/workflows/standard-e2e.yml
- .github/workflows/standard-suite.yml
- Makefile
- test/e2e/oidc/run-tests.sh
* it looks like it's no longer required
* it seems to introduce inconsistent/unnecessary changes in package-lock.json
> npm: stop using --legacy-peer-deps

- docs/api.yaml
@eyelidlessness pointed out that the extension and type are in conflict!
Nothing.
I could have changed the type to `audio`. Doesn't feel like it matters.
Hopefully the examples will make more sense!
This is it.
> Match file extension to type

- lib/data/dataset.js
- lib/model/query/forms.js
- test/data/xml.js
- test/integration/api/datasets.js
- test/integration/other/empty-entity-structure.js
- test/integration/other/form-entities-version.js
- test/integration/other/migrations.js
- test/unit/data/dataset.js
- test/unit/data/schema.js
Closes https://github.com/getodk/central/issues/730
I updated the versions in `testData.forms.simpleEntity` and `testData.forms.updateEntity` so the tests didn't have to change, but for any test that expected the older version, I also made test forms `testData.forms.simpleEntity2022` and `testData.forms.updateEntity2023` and used those (along with `?ignoreWarnings=true`) where appropriate.
Frontend PR: https://github.com/getodk/central-frontend/pull/1059
> Warn about <2024.1 entities spec and update tests

- lib/resources/oidc.js
- lib/util/oidc.js
* imposes stricter checks on callback params, making /callback fail faster if `code_verifier` cookie is missing & code is missing from callback params
* recommended at https://github.com/panva/openid-client/tree/v5.4.3/docs#clientcallbackredirecturi-parameters-checks-extras
> oidc: include response_type for client.callback()

- lib/model/query/submissions.js
- test/integration/api/submissions.js
Part of getodk/central#789
Updated existing test.
~This is the simplest approach. Other options is to backfill submissionId in the audit table for submission.delete and submission.restore events.~
Added `submissionId` in delete and restore audit.
None
NA
> Add submissionId in delete and restore audit

- lib/formats/odata.js
- lib/http/endpoint.js
- test/integration/api/odata.js
- test/unit/formats/odata.js
Related https://github.com/getodk/central/issues/763
> rowStreamToOData(): reject unmatched repeatIds

- docs/api.yaml
- Currently the docs for `POST /projects/{projectId}/datasets/{name}/entities` show the response type for uploading a single Entity.
- They have not been updated to show the response type when bulk uploading multiple Entities.
- Ideally the response would return the Entity data, but this is not trivial, due to having to re-fetch data from the db for each Entity (line 98 & 113):
https://github.com/getodk/central-backend/blob/fb96aa3333d3442ea43365755766262f21de3969/lib/resources/entities.js#L93-L114
- The endpoint currently returns `'success': true`.
- I updated the docs to reflect this, until the endpoint returns the Entity data (if possible).
- I reused the pattern in the docs for return type `application/json; extended` to use `application/json; bulk`, allowing us to display two …
> [Docs] add response example for bulk entities upload

- lib/model/query/entities.js
- test/integration/api/offline-entities.js
Closes https://github.com/getodk/central/issues/808 and https://github.com/getodk/central/issues/810
Also includes test of scenario in this issue: https://github.com/getodk/central/issues/811
Just fixed a bug in how this one query was working! Was looking for the root submission def but it wasn't filtering correctly.
> Fix "query returns an unexpected result" bug with entity create-as-update

- .github/workflows/soak-test.yml
Spun off from https://github.com/getodk/central-backend/pull/1315.
Soak tests are slow, and are only likely to break occasionally.  Re-enabling them on branches when working on specific features, e.g. `slonik` or `pg` upgrades, would be sensible.
Another option might be to also run if there are changes in `package.json` or `package-lock.json`.
No effect.
No.
> ci: only run soak tests on master branch

- lib/util/option.js
- test/unit/util/option.js
Making `Option.value` a private field broke `should(Option).eql()` behaviour.
See: #1287 / 5ef4c721664b344463ae7520ac3b1fa24c879402
Closes #1296
> Option: fix should.js .eql() behaviour

- lib/task/db.js
- lib/task/fs.js
- lib/task/task.js
Reading the current task code, it's not immediately clear why `task.promisify` is used in place of node's built-in `promisify` function.  Digging deeper, it turns out that this is exactly the same function.  This PR aims to save future developers from the overhead of understanding that `task.promisify === require('node:util').promisify`.
Ran tests
It simplifies the code.
This change should not affect users.
No.
> task: remove remapping of node:util.promisify()

- test/integration/api/submissions.js
- test/integration/other/encryption.js
- test/integration/other/submission-purging.js
- test/unit/data/attachments.js
- test/unit/data/briefcase.js
- test/unit/util/zip.js
- test/util/zip.js
Separating file data and meta data prevents clashes for files with names including:
* `filenames`
* `toString`
* etc.
Working on #1309, the return value from `httpZipResponseToFiles()` was confusing as it mixes both zipfile contents and zipfile metadata in the same object.  This PR aims to ease use of `httpZipResponseToFiles()`.
Ran tests.
This change was prompted by difficulties in understanding the results of `httpZipResponseToFiles()` when writing new zip-based tests.
Only affects developers; hopefully change is intuitive and improves understanding.
No.
> test/util/zip: processZipFile(): prevent filename clashes

- lib/resources/oidc.js
- test/e2e/oidc/playwright-tests/src/oidc-login.spec.js
* pass `next` value to IdP as `state`, with additional random prefix
* this makes the "next" value more trusted
* fix support for Authentik and other IdPs which do not support auth URLs without `state` (https://github.com/goauthentik/authentik/pull/9735)
* may also improve support for IdPs which lack PKCE support (see: https://github.com/panva/openid-client/blob/1486c3a020af8d12449d1d6a4bdf4f2bf4d32b77/README.md#authorization-code-flow)
Closes #1134
Closes #1135
Alternative: separate `state` & `next` cookies in https://github.com/getodk/central-backend/pull/1135
The approach in this PR is an improvement on that as it prevents tampering with the `next` cookie, e.g. by cookie tossing.
Should only affect users integrated with Authentik, which should now work.
No.
> oidc: pass state to IdP in authorization URL

- docs/api.yaml
- lib/resources/submissions.js
- lib/util/problem.js
- test/integration/api/submissions.js
Closes getodk/central#794
Added tests. Manually tested in dev env.
Uses existing approach and keeps the change limited to OpenRosa endpoint.
None
Yes
> Improves #794: Update error message on duplicate submission when original is soft deleted

- lib/data/entity.js
- lib/model/query/entities.js
- test/integration/api/offline-entities.js
Closes https://github.com/getodk/central/issues/815
From [here](https://github.com/getodk/central/issues/815#issuecomment-2514895303):
> @ktuite, I think what's happening here is that the entity as a whole is being marked as a conflict, but the API is not returning v2 as a conflict (its conflict property is null). Now that https://github.com/getodk/central-backend/pull/1251 has been merged, I think we need to update getWithConflictDetails() in a similar way to how it was updated in https://github.com/getodk/central-backend/pull/1187. There are now three situations in which an entity can be marked as a conflict (described in https://github.com/getodk/central/issues/805), but getWithConflictDetails() only accounts for two of them ([here](https://github.com/getodk/central-backend/blob/0bc6209 …
> Log create-as-update as a conflict

- docs/api.yaml
- lib/model/query/analytics.js
- lib/model/query/audits.js
- lib/model/query/entities.js
- lib/worker/jobs.js
- test/integration/api/audits.js
- test/integration/api/offline-entities.js
- test/integration/other/analytics-queries.js
Changed `submission.reprocess` event to `submission.backlog.reprocess` and removed the actor ID on that event because it's more of a system thing? Maybe I need that actor ID though and should add it back.
Added 
* `submission.backlog.hold` for when things to into the backlog
* `submission.backlog.force` for when submissions are force-processed from the backlog
* `submission.backlog.reprocess` when a submission's processing is triggered by a previous submission in a branch, which isn't quite the same as being "forced"
> Log additional backlog events

- lib/formats/odata.js
- lib/util/db.js
- lib/util/problem.js
- package-lock.json
- test/unit/formats/odata.js
Closes https://github.com/getodk/central/issues/764
> odata: handle invalid skiptokens

- docs/api.yaml
- lib/model/query/datasets.js
- lib/util/problem.js
- test/integration/api/datasets.js
Closes getodk/central#769
Added tests and manual verification.
I initially changed the database column type to `citext` to stop duplicate property names (case insensitive) but that prevented creation even when existing properties were unpublished. With the implemented approach we can have two unpublished Forms with same properties but different capitalization. Error is thrown when user tries to publish second one.
Change affects already complicated area of Form and EntityList creation, that should be tested thoroughly.
Yes
> Feature #769: Reject duplicate properties with different capitalization

- lib/resources/odata.js
- package-lock.json
Closes https://github.com/getodk/central/issues/733
Following dependencies are not updated due to breaking changes in `knex`:
```
braces  <3.0.3
Severity: high
Uncontrolled resource consumption in braces - https://github.com/advisories/GHSA-grv7-fg5c-xmjg
fix available via `npm audit fix --force`
Will install knex@3.1.0, which is a breaking change
node_modules/findup-sync/node_modules/braces
micromatch  <=4.0.7
Depends on vulnerable versions of braces
node_modules/findup-sync/node_modules/micromatch
findup-sync  0.4.0 - 3.0.0
Depends on vulnerable versions of micromatch
node_modules/findup-sync
liftoff  2.2.3 - 3.1.0
Depends on vulnerable versions of findup-sync
node_modules/liftoff
knex  <=2.3.0
Depends on vulnerable versions of liftoff
node_modules/knex
```
<hr>
I had to remove extra …
> npm audit fix for 2024.3

- .circleci/config.yml
- .github/workflows/oidc-e2e.yml
- .github/workflows/oidc-integration.yml
- .github/workflows/s3-e2e.yml
- .github/workflows/soak-test.yml
- .github/workflows/standard-e2e.yml
- .github/workflows/standard-suite.yml
- Makefile
- package-lock.json
- package.json
- test/e2e/oidc/run-tests.sh
- test/e2e/s3/run-tests.sh
- test/integration/task/task.js
Ran backend and frontend, clicked around to see whether there are any obvious issues.
There are a handful of deprecation warnings which we can take care of whenever.
We could stay on Node 20 which is still in maintenance LTS for over a year. But Node 22 has been in active LTS for a couple of months now and I'd rather we follow the active LTS releases unless there are any breaking changes we can't adapt to quickly. Making this change before regression testing gives us the best safety net we can get. Any issues there may be would probably only crop up under real usage.
There are some risks of subtle behavior changes, especially around things like streams. For streams in particular, the `highWaterMark` default is now 64k so the streams we don't explicitly configure will be impacted. There's …
> Use node 22, now in maintenance LTS

- test/e2e/s3/test.js
Node 22 introduced deprecation warnings which changed the stderr output of `lib/bin/s3.js`, breaking a test assertion.
Related #1340 
Closes #1339
> test/e2e/s3: relax regex for failed connection

- test/e2e/s3/test.js
It may not be immediately obvious that stdout and stderr are actually available when a call to `child_process.exec()` fails.  Attaching them here should bring attention to this, and aid future debugging.
This change assisted in debugging #1339
> test/e2e/s3: attach stdout & stderr to exec() errors

- Makefile
- test/e2e/oidc/run-tests.sh
- test/e2e/s3/run-tests.sh
- test/integration/task/task.js
These were initially removed in #1337 due to noise from upgrading to node 22.  However, seeing deprecation warnings in dev & testing is probably helpful.
This change requires a test checking stderr contents to relax its assertion slightly.
Related: #1339
> Remove no-deprecation flags from node invocations

- lib/model/query/analytics.js
- test/integration/other/analytics-queries.js
Closes https://github.com/getodk/central-backend/issues/1228
Makes use of `runSequentially` instead of Promise.all() to do multiple database queries for computing usage metrics.
> Change analytics queries to run sequentially

- package-lock.json
- package.json
Fixes following deprecation warnings:
```
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:20281) [DEP0053] DeprecationWarning: The `util.isObject` API is deprecated. Please use `arg !== null && typeof arg === "object"` instead.
(node:20281) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
(node:20281) [DEP0055] DeprecationWarning: The `util.isRegExp` API is deprecated. Please use `arg instanceof RegExp` instead.
(node:20281) [DEP0047] DeprecationWarning: The `util.isDate` API is deprecated.  Please use `arg instanceof Date` instead.
```
Upgraded playwright version as well, because [pipeline](https://github.com/sadiqkhoja/central-backend/actions/runs/12306021106/job/34347371060) is failing with this …
> Updated node_config package to 3.3 to fix the deprecation warnings

- config/default.json
- lib/data/analytics.js
- lib/model/query/analytics.js
- test/integration/other/analytics-queries.js
Closes https://github.com/getodk/central/issues/722
Based on this PR where I change Promise.all to runSequentially for the bulk analytics queries.  https://github.com/getodk/central-backend/pull/1344
> Usage metrics for 2024.3 release

- docs/api.yaml
Closes https://github.com/getodk/central-backend/issues/1211
This PR
- adds 2 missing form actions (`form.update.draft.replace` and `upgrade.process.form.entities_version`) 
- the other place in this release that we added new actions (for the submission backlog) already have these actions mentioned in the API docs.
- adds the user preferences endpoint to the changelog and removes some extra auth headers in the examples for those endpoints
- adds the file attachment hash to the form attachment endpoint with a little bit of explainer text and changing the example responses to be more consistent
> Changes to API docs for 2024.3 release

- test/integration/api/submissions.js
This probably isn't the desired behaviour, but it *is* the _current_ behaviour.
> submissions/attachments: demonstrate current null Content-Type handling

- .github/workflows/oidc-e2e.yml
It looks like this was broken by refactoring in 12635f025493229dc96b3d089153ce38751dc67a
This change was useful for diagnosing https://github.com/getodk/central-backend/pull/1359
> ci: e2e/oidc: fix artifact upload path

- test/e2e/oidc/playwright-tests/src/utils.js
This seems to solve intermittent (but currently frequent) test failures in webkit.
The cause seems to be the `autofocus` HTML attribute, which was causing the password to be entered into the username form field.
Examples:
* https://github.com/getodk/central-backend/actions/runs/12740996290/job/35506986333
* https://github.com/getodk/central-backend/actions/runs/12750152065/job/35534243596?pr=1358
Seems to be happening a lot at the moment:
https://github.com/getodk/central-backend/actions/workflows/oidc-e2e.yml?query=
Screenshot of a failure looks like:
Maybe related:
* https://github.com/microsoft/playwright/issues/26349
* https://github.com/microsoft/playwright/issues/22631
> test/e2e/oidc: fix webkit race condition

- lib/util/promise.js
The "current use" documentation does not cover all current uses.
Alternatively, this documentation could be removed completely, and intention for calling runSequentially() could be defined at the call sites.
It's just a documentation change.
This documentation could be removed completely, and intention for calling runSequentially() could be defined at call sites.
Does not affect users.
No.
> runSequentially(): expand docs on current usage

- lib/model/knexfile.js
- lib/model/migrate.js
- lib/util/db.js
- test/unit/util/db.js
Renames the knex config object passed as `connection` to `knex()` from generic "connectionObject" to more specific "knexConnection".
This renaming will:
* make intention/use of `connectionObject` clearer
* ease finding of knex-related code across the repo
* aid deprecating and finally removing knex dependency
CI
Not really?
Should not impact users - it's just a variable/export rename.
No.
> knex: rename connection object

- lib/bin/check-migrations.js
- lib/bin/check-open-db-queries.js
- lib/bin/run-migrations.js
- lib/model/migrate.js
- lib/model/migrations/20191231-02-add-schema-storage.js
- test/integration/other/migrations.js
- test/integration/setup.js
Renames `withDatabase()` and `connect()` functions in the database migrator to make it clearer they are directly using knex.
In line with #1364, this renaming will:
* make intention/use of these functions clearer
* ease finding of knex-related code across the repo
* aid deprecating and finally removing knex dependency
CI
Not really?
Should not impact users - it's just variable/export renaming.
No.
> db-migrate: rename knex-specific functions

- .eslintrc.json
Because db-migration tests use a wrapper for mocha describe() calls, extra configuration is required to catch .only() calls.
See: https://www.npmjs.com/package/eslint-plugin-no-only-tests#user-content-options
Issue discovered while working on https://github.com/getodk/central-backend/pull/1355
Tested locally while working on https://github.com/getodk/central-backend/pull/1355.
It is consistent with current detection & rejection of `.only()` calls in other tests.
Only affects test code.
No.
> eslint: catch .only() calls in db-migration tests

- lib/util/db.js
- test/unit/util/db.js
* simpler code
* minor optimisation
* resolves FIXME
Introduced in https://github.com/getodk/central-backend/pull/1240, but not resolved before merge.
CI
No other approaches were considered.
No effect.
No.
> db/unjoiner: remove extra sql`` wrapper

- lib/model/query/forms.js
- test/integration/api/forms/forms.js
Closes getodk/central#869
Added a test. Manually verified.
NA
None
No
> fixes #869: return warnings if there are any

- test/integration/api/forms/test.js
Add `/test/` to the `describe()` string to make it clearer that this file is testing a specific set of endpoints.
Closes #1380
Closes #
> test/forms/test: make title more explicit

- test/integration/api/datasets.js
- test/integration/api/projects.js
- test/util/scenarios.js
The files in test/integration/fixtures are repeatedly `require()`d and run in the `initialize()` function of `test/integration/setup.js`.  The `scenarios.js` does not need this treatment.
CI
A location in `test/integration/` might be more appropriate.  However, there are already various integration-test-specific files in `test/util`, so the proposed move is following existing conventions.
No change.
No.
> test: move createConflict() from fixtures to util

- lib/model/query/sessions.js
- test/integration/other/bearer-auth.js
Currently passing a `Authorization: Bearer ...` header with a token that fails the `isValidToken()` check will return a 500 response.
To recreate:
```
$ curl https://dev.getodk.cloud/v1/projects/1 --header 'Authorization: Bearer hi'
{"message":"Internal Server Error"}
```
vs
```
$ curl https://dev.getodk.cloud/v1/projects/1 --header 'Authorization: Bearer aaaaaaaabbbbbbbbccccccccddddddddaaaaaaaabbbbbbbbccccccccdddddddd'
{"message":"Could not authenticate with the provided credentials.","code":401.2}
```
From Sentry (https://getodk.sentry.io/issues/6194482982/?environment=production&project=5724763&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=30d&stream_index=2), when the supplied token is invalid, `authHandler` can throw.
Added a test …
> query/sessions: return 401 for invalid Bearer token

- .eslintrc.json
- docs/api.yaml
- lib/model/migrations/20250113-01-disable-nullable-blob-content-types.js
- lib/model/query/blobs.js
- test/db-migrations/20250113-01-disable-nullable-blob-content-types.spec.js
- test/db-migrations/utils.js
- test/e2e/s3/test.js
- test/integration/api/submissions.js
- test/integration/task/s3.js
Set `blob."contentType"` values to `application/octet-stream` if no mime type is supplied on upload.
Related: #1351
CI.
Discussion on #1351.
This will change `Content-Type` headers for files uploaded without one from the string `null` to the string `application/octet-stream`.
Yes.
> blobs: prevent NULL contentType in db

- docs/api.yaml
- lib/model/query/submission-attachments.js
- lib/resources/forms.js
- lib/resources/submissions.js
- lib/util/blob.js
- test/data/xml.js
- test/integration/api/submissions.js
Ref #1351
Updated tests.
Discussed on https://github.com/getodk/central-backend/issues/1351
Replace `Content-Type` response header of string `"null"` with `text/csv; charset=utf-8` for `.csv` files, and `application/geo+json` for `.geojson` files.
Yes, done.
> blobs: derive missing contentType from file extension

- lib/resources/oidc.js
- test/integration/api/oidc.js
Without this check, a request without a state parameter will generate an internal server error and receive a 500-status response.
This change sends the client through the proper error-handling route.
Closes #1391
Added a test!
This could also be an e2e test, but an integration test should run and fail faster, giving faster feedback.
This change should only affect users in unhappy paths.
I don't think so.
> oidc/callback: handle missing state param

- test/integration/setup.js
Due to use of `function()` in the test wrappers, `this` was unbound from the real test functions.  This PR re-binds mocha's `this` to the test functions, allowing use of e.g. `this.timeout(...)` in individual "FullTrx" tests.
> test/integration: allow use of this.timeout() in FullTrx tests

- test/integration/api/sessions.js
This behaviour was noted by @sadiqkhoja, and seemed at least worth documenting if not fixing.
Closes #1409
Added a test.
An alternative to this test would be to check for NUL characters in supplied passwords and reject them before passing the values to bcrypt.
No effect.
No.
> api/sessions: document bcrypt implementation curiosity

- docs/api.yaml
- lib/formats/openrosa.js
- lib/model/query/datasets.js
- lib/model/query/entities.js
- lib/resources/datasets.js
- lib/resources/forms.js
- lib/util/util.js
- package-lock.json
- package.json
- test/integration/api/datasets.js
Closes [#668](https://github.com/getodk/central/issues/668)
Dependent on #1349 
Written tests. I have deployed this to dev environment for Collect team to start using this endpoint.
Used the existing pattern.
Since Form manifest is changed, it should work with older Collect clients.
yes
> Entities Integrity URL

- lib/external/sentry.js
- lib/http/endpoint.js
- lib/model/migrations/20180727-03-add-form-attachments-table.js
- lib/util/db.js
Noted while investigating #1403.
Some logging is not followed by a newline character, so it is concatenated with the next output to `stderr`.
This commit adds newline characters to calls to `process.stderr.write()` where missing, and standardises their inclusion.
Run locally; tests in CI.
Introduced in f3e85630a3985fbcb03cd84cfbe1384a1f39017d, it's unclear why `process.stderr.write()` is used in preference to `console.error()`.
No change for users, unless they're parsing stderr for e.g. monitoring.  This change would probably make parsing more reliable.
I don't think stderr output is currently documented.
> stderr.write(): add newline suffix consistently

- test/integration/setup.js
Follow-up to #1402
Noticed while investigating #1403
Due to use of `function()` in the test wrappers, `this` was unbound from the real test functions.  This PR re-binds mocha's `this` to the test functions, allowing use of e.g. `this.timeout(...)` in individual tests.
Checked all the tests still pass.
No.
No effect - it's test code only.
No.
> test/integration: allow use of this.timeout() in all tests

- test/unit/util/crypto.js
While working on https://github.com/getodk/central-backend/pull/1411, I initially copy/pasted another test which contained the following comment:
```
// i know about should.throws but i can't get it to assert the specific error type.
```
This PR cleans up that comment and simplifies error checking in the related test.
Checked the test passes, and that it fails with different error messages.
Considered using `should.throws()` but it doesn't support a simple way to assert on the error message without using regex.  There's precedent for using `assert.throws()` instead:
```sh
git grep -F .throws -- test/unit | awk '
/assert.throw/ { a += 1 }
/should.throw/ { s += 1 }
END {
print "assert.throws(): " a;
print "should.throws(): " s;
}
'
assert.throws(): 36
should.throws(): 3
```
No effect.
No.
> test/crypto: use assert.throw() instead of hand-rolling

- lib/model/migrations/20250221-01-deletedAt-index-entity.js
**Issue**: Purging of Entity takes too long when there are many rows in entities table. In our staging server there are 1.6M+ Entities, and purging query at max took 611 minutes to execute.
**Solution**:  Create an index on "deletedAt" column in `entities` table, and create an index on "sourceId" in "entity_defs" table.
**Diagnosis**: I tried running parts of CTE query individually but even the simplest query `DELETE FROM entities WHERE "deletedAT" IS NOT NULL` was taking more than 5 mins (I cancelled the execution).
Since simple query was taking so much time, I hypothesized that creating an index on "deletedAt" column should help, so I tried creating an index but that was taking too much time. So we increased the database instance size from t3.small to t3.xlarge, created the index and …
> Fixes: slow entity purging - added couple of indices

- lib/util/crypto.js
- test/integration/api/sessions.js
Closes #1406
Added more test cases.
Fixing this at the API layer instead of inside `util/crypto.js` introduces the risk that it may be fixed in one place, but still broken in another.
Should not affect legitimate use.
It should not.
> Standardise responses for invalid existing passwords

- lib/model/query/users.js
- lib/util/crypto.js
- test/integration/api/sessions.js
- test/integration/api/users.js
- test/integration/fixtures/01-users.js
- test/integration/other/basic-auth.js
- test/unit/http/preprocessors.js
- test/unit/util/crypto.js
- test/util/authenticate-user.js
Closes #1407
New test cases, and existing test cases.
The fix is pushed deeper into the `util/crypto.js` code than where validation previously occurred.  This means that validation only needs to be performed in a single place, rather than every point of use.  This in turn means it should be harder to forget validation & edge cases in future use of `hashPassword()`.
More consistent errors when passwords are unexpected data types.  Users are unlikely to encounter the change in behaviour.
It should not.
> Standardise responses for invalid new passwords

- test/integration/api/user-preferences.js
Test added while trying to understand special `null` handling at https://github.com/getodk/central-backend/blob/bf49b89d1b22d2cc6989f2c4eba7a9c739d347e9/lib/model/query/user-preferences.js#L68-L73
Closes #1423
Added a new test.
Seems quite direct, but open to other options.
This is just a new test - should not affect users except for preventing future regressions.
No.
> UserPreferences: ensure "null" and NULL are handled distinctly

- test/integration/other/entities-purging.js
Noted while working on #1437.
Previous test descriptions were causing double spaces to be inserted in test names.
Before:
```
✔ should throw an error  when entityUuid specified without projectId and datasetName (273ms)
✔ should throw an error  when entityUuid specified without projectId (105ms)
✔ should throw an error  when entityUuid specified without datasetName (97ms)
✔ should throw an error  when datasetName specified without projectId (89ms
```
After:
```
✔ should throw an error when entityUuid specified without projectId and datasetName (273ms)
✔ should throw an error when entityUuid specified without projectId (105ms)
✔ should throw an error when entityUuid specified without datasetName (97ms)
✔ should throw an error when datasetName specified without projectId (89ms
```
It's a …
> test/entities-purging: whitespace

- lib/model/query/users.js
- lib/util/promise.js
- test/integration/api/sessions.js
Closes #1430
* existing tests
* new tests
Validation of the `email` type could be performed closer to the API.  In that case, validations should be added in more places.
Should reduce number of 500 errors.  Users are unlikely to be relying on this status code.
500 errors should not be documented, so no documentation update is expected.
> Standardise responses for invalid user email

- docs/api.yaml
- lib/model/query/audits.js
- test/integration/api/audits.js
`entity.restore` and `entity.purge` should be excluded for `action=nonverbose` audits API and should be added for `action=entity`
Updated the existing tests
NA
No
Updated.
> Fixes: exclude entity.restore and entity.purge from nonverbose audits endpoint

- test/unit/util/odata.js
Add unit tests for `nextUrlFor()` from `odata/util.js` which demonstrate the current behaviour that URL-encoding of some parts of the request URL are reflected in responses.
Noticed while trying to upgrade `supertest` to the latest release.
It's a new test.  I tried changing the code to deliberately fail the test, and it does.
No other approach considered.
No effect.
No.
> odata/util/nextUrlFor: add unit tests

- lib/util/http.js
`url.parse()` was deprecated in node v18.13 and v19+:
> Stability: 0 - Deprecated: Use the WHATWG URL API instead.
See: https://nodejs.org/api/url.html#urlparseurlstring-parsequerystring-slashesdenotehost
Noticed while trying to upgrade `supertest` to the latest release.
Existing test suite.
Recommended by node.
Should not affect users.
Risks: `url.parse()`, `URL.parse()` and `new URL(...)` behave differently for invalid URLs.  I've introduced some validation for more consistency:
```js
[
undefined,
null,
'',
'asdf',
'http://example.test/some/path/to/a-file.php.exe?q=asdf&2+2=5#frag',
].map(u => {
let p1, p2;
try { p1 = url.parse(u).pathname                     } catch(err) { p1=err.message }
try { p2 = require('./lib/util/http').urlPathname(u) } catch(err) { p2=err.message }
return [ p1 …
```
> Stop using legacy url.parse()

- package-lock.json
- package.json
- test/integration/api/odata.js
Closes #1440
Test changes are due to behaviour demonstrated in https://github.com/getodk/central-backend/pull/1460
Existing test suite.
The only unexpected change is due to a combination of:
* supertest moving from `url` to `URL` for parsing/generating request URLs
* and
* lack of normalisation of url-encoded characters in request paths (it may not be correct to normalise these characters), or
* lax acceptance of url-encoded `'` and/or `:` chars
Relevant commits for the latter can be seen with `echo -e "%27\n%3A\n%3a" | xargs -n1 git log --format="%aI %h %s" -S | sort -u`:
* `2018-04-06` 7ded3b9f bug/odata: single-submission service urlparsing needs to decode escapes.
* `2018-04-23` 0bbd6c6e new: API Blueprint docs for the public API, formatted for Apiary.
* `2018-12-30` f0660000 improve …
> Update test dependency supertest (6.3.3 -> 7.1.0)

- test/db-migrations/migrator.js
Knex sorts migration files at https://github.com/knex/knex/blob/823c7b60f74fb16bcb8a8230afe1fea6673c2bd0/lib/migrate/sources/fs-migrations.js#L70
Encountered while working on #1363
It's just a comment
No other options were considered
No effect - it's just a comment.
No - it's just a comment.
> test/db-migrations: resolve TODO ref migration order

- test/db-migrations/migrator.js
This allows non-JS files in lib/model/migrations, e.g. `.eslintrc.json`.
Encountered while working on https://github.com/getodk/central-backend/pull/1363
Tests still pass (¬:
Just a simple fix.
No - it's in test code.
No - it's in test code.
> test/db-migrations: don't break on non-JS files in migrations dir

- lib/resources/forms.js
Backend change of issue https://github.com/getodk/central/issues/897
The verbs on `/projects/:projectId/forms/:id/dataset-diff` have changed to `form.read` and `dataset.list` so that project viewers are able to get the list of datasets related to a published form.
The verbs on `/projects/:projectId/forms/:id/draft/dataset-diff` are still the same (`form.update` and `dataset.list`) and I think this makes sense because project viewers can't see draft forms so they don't need to see this kind of information.
> Change dataset-diff form verb from update to read

- docs/api.yaml
- lib/model/query/form-attachments.js
- lib/resources/forms.js
- test/assertions.js
- test/integration/api/datasets.js
- test/integration/api/forms/draft.js
This PR makes a change to the POST endpoint for uploading a file for a form attachment. Right now, that endpoint returns `{ success: true }`. However, Frontend would benefit from receiving the updated form attachment (the metadata about the form attachment, not the blob). This PR makes a change along those lines, returning the updated form attachment rather than `{ success: true }`.
Even today, Frontend would benefit from receiving the updated form attachment. After a successful request to the POST endpoint, Frontend wants to update the `updatedAt` timestamp that's shown in the form attachments table. Since it doesn't know the true `updatedAt` timestamp, it just uses the current timestamp after the response is received, which should be pretty close to the true timestamp. You can see the …
> Return form attachment after POST, not { success: true }

- lib/data/client-audits.js
- lib/model/migrations/20250415-01-client-audit-remainder.js
- test/data/audit4.csv
- test/db-migrations/.eslintrc.js
- test/db-migrations/20250113-01-disable-nullable-blob-content-types.spec.js
- test/db-migrations/20250415-01-client-audit-remainder.spec.js
- test/db-migrations/fixtures.js
- test/integration/api/submissions.js
- test/integration/other/encryption.js
- test/integration/other/submission-purging.js
Closes https://github.com/getodk/central/issues/654
As discussed in the issue, the values for `user` and `change-reason` were luckily captured in the jsonb `remainder` column of the `client_audits` table. 
This PR migrates/copies the values from that column to two new columns in the `client_audits` table and adds `user` and `change-reason` as expected client audit headers to be included in the audit export.
I've added a new test for the behavior, created a database migration test, and tried it with some real data.
Straightforward solution based on discussion in issue.
Exposes `user` and `change-reason` in consolidated client audits export when these parameters are set in the xlsform: `identify-user=true track-changes-reasons=on-form-edit` 
I'm not sure client audits are mentioned in the …
> Include user, change-reason in client_audits export

- lib/formats/odata.js
- lib/http/preprocessors.js
- lib/util/util.js
- test/integration/api/forms/forms.js
- test/unit/util/util.js
- test/util/enketo.js
* rename util fn `without()` to `omit()`
This should reduce confusion between Ramda's `without()` function, for modifying arrays, and this repo's `omit()` function, which is a re-implementation of Ramda's `omit()` function, but with specific guarantees.
See:
* https://ramdajs.com/docs/#omit
* https://ramdajs.com/docs/#without
Existing test suite passes.
This should prevent confusion between:
* `without()` imported from `ramda`
* `without()` imported from `./lib/util/util`
* `omit()` imported from `ramda`
No effect.
No.
> util: reduce confusion around without() fn

- lib/external/s3.js
- lib/model/query/blobs.js
- test/integration/task/purge.js
- test/util/s3.js
This significantly improves performance (about 3x locally).
Closes #1443
* did a lot of benchmarking and staring at query plans
* added a test
* realised that to make significant improvements over the current approach, this is the simplest option
Note that the current test doesn't even rely on any data being in the joined tables
A few other options, e.g.
* adding indexes.  This PR is much less invasive, and shouldn't have side effects
* changing the `unattachedClause` clause
* to avoid `NULL` checks.  This looks like it could potentially 100x performance (or 30x over this PR), but would probably need a placeholder row in the `Blobs` table (e.g. w/ id = -1), and then add NOT NULL constraints to all `blobId` FK columns[1]
* in other ways, none of which had significant improvements.  The …
> purge: s3: delete uploaded blobs in batches

- config/default.json
- lib/data/analytics.js
- lib/model/query/analytics.js
- test/integration/other/analytics-queries.js
Backend part of https://github.com/getodk/central/issues/861
Count number of forms in each project that have webforms enabled.
> Usage metric: count webforms enabled

- docs/api.yaml
- lib/model/query/submissions.js
- lib/util/util.js
- test/integration/api/submissions.js
Closes #1495 
As mentioned in the issue, increasing the column width is not a reliable solution, we can't know the upper limit of user-agent or device ID
No
Updated
> Fixes #1495: Truncate user-agent and deviceId

- lib/resources/sessions.js
- test/assertions.js
- test/integration/api/sessions.js
This is a follow-up PR to #1472. I noticed that /v1/sessions/restore was returning `actorId` in addition to `expiresAt` and `createdAt`. `actorId` isn't a readable field on the `Session` frame, and I don't think we want to return it from this endpoint.
I updated a test.
> Don't return actorId from /v1/sessions/restore

- lib/model/query/auth.js
- lib/util/db.js
- test/integration/api/projects.js
Resolves TODO ref de-duplicating data on postgres side.
Noticed while working on #1502
All existing tests continue to pass.
The functional change is quite minimal.  There are unnecessary formatting changes included in this PR, which IMO make the whole thing more readable.
No effect.
No.
> Auth.verbsOn(): deduplicate data returned from db

- lib/model/query/auth.js
Current code seems odd.
Noted while working on #1502
This introduces some formatting change which IMO improve readability.  A simpler changeset could be achieved by maintaining existing formatting.
Potential for breaking existing authZ, but test coverage should ensure it's fine.  Also reading the code, it seems low-risk.
No.
> auth.can(): simplify SQL

- docs/api.yaml
- lib/formats/openrosa.js
- lib/model/query/datasets.js
- lib/model/query/form-attachments.js
- test/integration/api/datasets.js
Closes getodk/central#685
Added a test.
I could have modified `getLastUpdateTimestamp()` to return `approvalRequired` fields as well but that function is consumed by `Datasets.getMetadata` as well where approval required is already available. But the real reason I didn't go that route is the renaming the function, what could I have called the it (getLastUpdateTimestampAndApprovalRequired?) 🙃
The change in this PR modifies the `FormAttachments._get()` in a way that additional database queries for each dataset are no longer required, saving us multiple database round-trips.
No
Yes
> Return approvalEntityList in Form attachment manifest

- lib/task/db.js
Closes getodk/central#1100
Verified the change on dev environment to double check, previously same change was applied on test env during regression testing of the last release.
It solves the problem. I have opt not to include `--no-owner` because in our case we have single user and assumption is that the backup is created with `/v1/backup` API; any deviation or different/complex infrastructure created by end-user would be managed by themselves.
No
No
> fixes getodk/central#1100: add --no-acl flag for db restore

- lib/data/dataset.js
- lib/data/schema.js
- lib/model/query/forms.js
- test/unit/data/dataset.js
- test/unit/data/schema.js
Part one of working towards https://github.com/getodk/central/issues/1020
This PR
- allows the version 2025.1.0 entities-version spec
- no longer has an error about entity binds in repeats if the version is 2025.1 or greater
- refactors the code to expect an array of datasets in the XML parsing even though the code is still limited to finding only one dataset
> Allow entities-version 2025.1 and refactor to prepare to parse multiple datasets

- config/default.json
- lib/data/analytics.js
- lib/model/query/analytics.js
- test/integration/other/analytics-queries.js
Closes https://github.com/getodk/central/issues/1071
Introduces a new metric at the system level that counts datasets/entity lists with "ownerOnly" setting enabled:
* `num_owner_only_datasets`
Depends on merging https://github.com/getodk/central-backend/pull/1498 first
Only last commit in this PR is needed
> Add usage metrics for 2025.2 count ownerOnly datasets

- lib/data/odata-filter.js
- test/unit/data/odata-filter.js
Change: If an operand of equality operator is null then transform it into IS NULL so that index can be used if available
Verified performance improvement locally: without this change I get results in ~1500 and with the change I get it in <100ms. I have around 40K entities in a dataset locally.
Previously I had deployed this patch to staging and observed significant performance improvement. 15sec without the change and ~100ms with the change.
The approach is result of quite a bit of research and discussion with the team. Slack thread: https://getodk.slack.com/archives/C01TKJ7TG7J/p1749070387516389
I don't see any risk of regression in this change.
No
> Improve search/filter performance.

- lib/resources/forms.js
- test/integration/api/forms/draft.js
New tests.
* role check as suggested by @matthew-white 
* maybe there's a neater way to check if a form is a draft?
Might affect users who were taking advantage of the lax permissions checks.
Should not.
> forms/draft/get: fix permissions check

- lib/resources/forms.js
This comment was introduced in 4c9fbf9f0036b7320cfafeaad0a8aca4e24b23b6, when the proceeding lines read:
formResource('/projects/:projectId/forms/:id', (Form, params, withXml = false, options = QueryOptions.none) =>
((withXml === true) ? Form.getWithXmlByProjectAndXmlFormId : Form.getByProjectAndXmlFormId)(params.projectId, params.id, options)
.then(getOrNotFound));
The comment no longer seems relevant to the code that follows it, which is now much simpler than it was originally.
This commit also adds a newline, breaking apart two resource definitions, in keeping with the rest of the file.
It's a comment.
It's a comment.
It's a comment.
It's a comment.
> resources/forms: remove outdated comment

- lib/model/query/submissions.js
CI.
Additional possibilities:
* profile the change
* analyse query plans on some production databases
This change seems obviously more efficient, so further analysis has not been performed.
Simple change, obvious impact.
Submissions fetching is very common, so this might provide noticeable performance improvements.
There is a chance for regression if `options.condition` ever references some column of `projects`.  I cannot see any code where this occurs; if it happens in prod, the error should trigger alerting.
No.
> query/submissions: reduce JOINS by 1 for SELECTs

- lib/resources/odata.js
Remove reference to `singleRowRegex`, which was commented out in 2020 (6f75b049565e0fa148ae3994425994c9bd30d907) and appears to now be irrelevant.
CI.
Dead code adds noise.  I didn't strongly consider an alternative to deleting it.
No change.
No.
> lib/resources/odata: remove dead code

- lib/resources/submissions.js
- test/integration/api/submissions.js
Closes getodk/central#1166
Manual verification + added an integration test
This implements what @lognaturel suggested during the summit. i.e. this allows users with permission to create submissions to upload corresponding attachments using REST API if attachment is not already there. I have added another condition that submission should have been created by the same user.
None.
No.
> Allow data collectors/public links/app-users to upload attachment using rest endpoint

- test/integration/api/datasets.js
- test/integration/api/entities.js
- test/integration/api/users.js
- test/integration/task/account.js
- test/integration/task/config.js
Replace getOrNotFound uses with `(o) => o.get()`
In API code `getOrNotFound()` makes sense, as it generates a `Problem` which is converted to an HTTP 404 response.
In test code, the `Problem` is not required, and while the code may look neater, it obscures stacktraces and makes test failures harder to understand.
Closes https://github.com/getodk/central/issues/1162
> tests: do not use getOrNotFound()

- lib/data/odata-filter.js
Stumbled on the abstract comment "still hate this" while wondering why there was extra whitespace added in https://github.com/getodk/central-backend/pull/1521/files#diff-90d20d47db15559988f3ded320c4c99215d0ec013538f2cbca18a0d5a2925833R101-R102.  I'm guessing the hate was for the `let` keyword, so this commit removes the `let`.
CI.
Other approach considered was just to remove the comment, but I think this approach makes the intent of the code clearer.
No change.
No.
> odata-filter: extract parse error handling

- lib/model/query/analytics.js
As in other cases where searching for the latest audit, it's important to do a secondary ordering by ID to avoid duplicate audits.
Related: #1564
CI.
It might be helpful to enforce this somehow, but there are no obvious avenues currently.
Should fix a very infrequent bug.
No.
> analytics: fix audit fetching

- lib/external/sentry.js
- test/integration/setup.js
- test/unit/external/sentry.js
Sentry has a list of default integrations, which may change over time.
This commit adds a unit test to make enabled integrations explicit.
Ref: https://github.com/getodk/central/issues/1191
This change will also lay the foundation for removing irrelevant Sentry integrations.
CI, `make run`.
Alternative to https://github.com/getodk/central-backend/pull/1562, responding to comments there.
Should not affect users.
No.
> Sentry: document enabled integrations

- lib/http/preprocessors.js
Second arg was always called with the same, defined value.
Follow on from https://github.com/getodk/central-backend/pull/1488
CI.
* could keep as-is, but the extra indirection seems harder to follow than necessary
* could maintain `return reject(...)` instead of `throw`?  `throw` seems more idiomatic
No change.
No.
> http/preprocessors: simplify authBySessionToken() signature

- lib/http/preprocessors.js
Clean up `Option` handling in `authBySessionToken()`.
Related:
* https://github.com/getodk/central-backend/pull/1587
* https://github.com/getodk/central-backend/pull/1582
Closes getodk/central#
CI.
Clearer?
No effect.
No.
> http/preprocessors: use getOrReject() idiomatically

- .github/workflows/standard-suite.yml
- Makefile
- package-lock.json
- package.json
This PR replaces `swagger-cli` with `redocly`, as recommended at https://github.com/APIDevTools/swagger-cli:
> ⚠️ Swagger CLI has been deprecated, due to the maintenance burnden of trying to keep up with expectations of a huge userbase with little to no pull requests or support. [Redocly CLI](https://redocly.com/redocly-cli/) covers all of the same functionality, and has more advanced linting with custom rules, and we highly recommend using that instead. They have conveniently provided a [migration guide](https://redocly.com/docs/cli/guides/migrate-from-swagger-cli/) for existing Swagger CLI users. Read the review of [Redocly CLI from APIs You Won't Hate](https://apisyouwonthate.com/blog/redocly-cli/).
CI.
It's the first step - `redocly lint` currently passes, although with many warnings. …
> api-docs/lint: replace swagger-cli with redocly

- .github/ISSUE_TEMPLATE/config.yml
All issues are now filed in the `central` repo. However, this PR adds a cross-link from this repo to `central` to make it easier to initiate issue creation from this repo.
I'll verify it once the PR is merged.
I thought about listing the link on the bottom so that end users are less tempted to click it. We really want users to post issues in the forum. But in practice, users don't file GitHub issues often; it doesn't come up that often. Ultimately, I think it's helpful to parallel the order in the `central` repo, where GitHub automatically places "Blank issue" on top.
> Add link to file new issue in central repo

- test/integration/api/users.js
Noted while considering https://github.com/getodk/central/issues/1315#issuecomment-3234750850.
I read the context of the verb loading, and they look to be site-wide.
There are probably syonyms to site-wide, including "sitewide".  Both are already in use in this repo.
No effect.
No.
> test/api/users: fix typo: sidewide -> site-wide

- docs/api.yaml
- lib/model/query/entities.js
- lib/resources/entities.js
- test/integration/api/entities.js
this endpoint facilitates 'created by' filter on the frontend (getodk/central#973)
Added a tests and manual verification
Follows same approach as getting list of submitters.
No
Done
> Feature: New endpoint to get list of creators for the entities

- lib/model/query/submissions.js
1. only return data from the db which is not already available
2. reduce nested queries
3. only update the `current` row in submission_defs
4. add extra JOIN on submission_defs to return root row's userAgent (necessary to achieve 4)
Neater rewrite of https://github.com/getodk/central-backend/pull/1544
Related: https://github.com/getodk/central/issues/1170
CI!
Discussion at https://github.com/getodk/central-backend/pull/1544; this is a neater rewrite of that, specifically tackling the `Submissions.createVersion()` function, where the `xml` field was previously passed to the database and then returned.
This PR could be changed to return query formatting to match the original more closely.  To me this makes understanding the query significantly harder.
Potential follow-ups:
* Look at …
> Submissions.newVersion(): reduce repeated data

- lib/model/query/submissions.js
* inline `_defInsert()`
* invert INSERT query to replace `nextval()` with standard key generation
* reduce data returned from PostgreSQL which NodeJS already has
* reformat main query
Follow-up to https://github.com/getodk/central-backend/pull/1606
Having read `_defInsert()` enough times to understand it, it seemed helpful to rewrite it.  I assume the reason why the `submission_def` was being inserted _before_ the `submission` was to allow use of `_defInsert()` by both `Submissions.createNew()` and `Submissions.createVersion()`, which is no longer happening.
CI.
* This PR inverts the insertion order of `submission` and `submission_def` to rely on PostgreSQL to assign the `submission`'s `id`.  This is orthogonal to decreasing the data passed between PostgreSQL and NodeJS.
* This PR could …
> Submissions.createNew(): return less data

- docs/api.yaml
- lib/http/sessions.js
- lib/model/frames.js
- lib/model/migrations/20250910-01-add-last-login-at-column.js
- lib/model/migrations/20250910-02-backfill-last-login-at.js
- lib/model/query/users.js
- lib/resources/sessions.js
- test/assertions.js
- test/db-migrations/20250910-02-backfill-last-login-at.spec.js
- test/integration/api/audits.js
- test/integration/api/users.js
- test/integration/other/knex-migrations.js
- test/util/util.js
Part of getodk/central#1104
Added/updated tests
I was contemplating to use `meta` column (jsonb) on `actors` table to store last login time, but I think we might want to use this for sort/filter in future + login can be only done by users not by any other actors that's why I decided to create a new column in `users` table.
No
yes
> Feature getodk/central#1104: Added lastLoginAt field
