getodk/central-backend

- lib/reused/option-test.js
- lib/reused/option.js
> New Option class to handle values that might not be present 

- LICENSE
- NOTICE
- README.md
> Add license information and copyright notice

- lib/model/instance/form.js
- lib/model/query/forms.js
- lib/model/query/simply.js
- lib/resources/forms.js
> new: GET /forms returns all forms.

- lib/cli.js
- lib/model/database.js
- lib/model/instance/actor.js
- lib/model/instance/membership.js
- lib/model/migrations/20171213-01-unrequire-display-name.js
- lib/model/package.js
- lib/problem.js
- package-lock.json
- package.json
For now:
* create user (with email/password).
* promote user to admin (by email). (matt this one will fail for you)
* force-set user password (by email).
> CLI script which performs administrative actions.

- lib/model/instance/form.js
- lib/model/query/forms.js
- lib/resources/forms.js
* no tests yet; all forms tests are forthcoming in one batch.
> new: extended metadata for forms on GET /forms and GET /forms/:id.

- lib/cli.js
- lib/data/csv.js
- lib/data/schema.js
- lib/model/instance/instance.js
- lib/model/migrations/20170920-01-initial.js
- lib/model/query/future-query.js
- lib/resources/users.js
- lib/reused/option.js
- lib/reused/promise.js
- lib/run-server.js
- lib/util/xml.js
- package-lock.json
- package.json
- test/api/data.js
- test/api/resources/forms.js
- test/api/resources/submissions.js
- test/unit/data/csv.js
- test/unit/data/schema.js
- test/unit/reused/option.js
- test/unit/util/xml.js
> Miscelleneous fixes (close many issue tickets)

- lib/model/instance/form.js
- lib/model/instance/submission.js
- lib/model/migrations/20180327-01-update-form-constraints.js
- lib/resources/forms.js
- test/integration/api/field-keys.js
- test/integration/api/forms.js
- test/integration/api/submissions.js
- test/unit/model/instance/form.js
- test/unit/model/instance/submission.js
Based off the form state branch/PR because otherwise the merge conflicts would be awful.
See commit messages.
> Form deletion

- lib/model/instance/form.js
- lib/model/instance/instance.js
- lib/model/instance/submission.js
- lib/model/migrations/20180322-01-additional-form-options.js
- lib/model/migrations/20180327-01-update-form-constraints.js
- lib/model/query/forms.js
- lib/resources/forms.js
- lib/resources/submissions.js
- lib/util/problem.js
- test/integration/api/field-keys.js
- test/integration/api/forms.js
- test/integration/api/submissions.js
- test/unit/model/instance/form.js
- test/unit/model/instance/submission.js
State defaults to open, which is downloadable, submitable.
In Closing state: not downloadable, submitable.
In Closed state: neither.
Also add PUT /forms/:id so the state is settable.
> Forms state

- docs/api.md
- lib/model/instance/form.js
- lib/model/instance/submission.js
- lib/resources/config.js
- test/assertions.js
- test/integration/api/config.js
- test/integration/api/forms.js
And some associated fixes. See commit messages for more.
> API Documentation

- lib/model/instance/form.js
- lib/model/instance/submission.js
- test/integration/api/forms.js
- test/integration/api/submissions.js
- test/unit/model/instance/form.js
- test/unit/model/instance/submission.js
* when we do #45 we'll have to look at this again. probably have to
depend on libxml or something.
> bug: the xml validator we relied on returns false negatives. rm for now.

- docs/api.md
- lib/resources/forms.js
- lib/util/http.js
- test/integration/api/forms.js
- test/unit/util/http.js
As stated in the title. See commits (one bugfix commit to make the main commit less painful).
> GET /v1/forms/{xmlFormId}.schema.json

- lib/data/briefcase.js
- lib/data/json.js
- lib/data/schema.js
- lib/model/instance/form.js
- lib/model/instance/submission.js
- lib/model/query/submissions.js
- lib/outbound/odata.js
- lib/resources/config.js
- lib/resources/forms.js
- lib/resources/submissions.js
- lib/task/task.js
- lib/util/util.js
- lib/util/xml.js
- package-lock.json
- package.json
- test/assertions.js
- test/integration/api/forms.js
- test/integration/api/odata.js
- test/integration/api/submissions.js
- test/integration/data.js
- test/unit/data/briefcase.js
- test/unit/data/json.js
- test/unit/data/schema.js
- test/unit/model/instance/form.js
- test/unit/model/instance/submission.js
- test/unit/outbound/odata.js
- test/unit/util/crypto.js
- test/unit/util/util.js
- test/unit/util/xml.js
commit messages are descriptive but this will probably require interactive review.
> Completely replace fast-xml-parser

- lib/model/instance/blob.js
- lib/model/instance/submission.js
- lib/util/stream.js
- test/integration/api/forms.js
* good thing this bug never hit release!
* plus a new test to catch this case.
> bug+test: was always computing an empty hash for Blob uploads.

- lib/model/query/forms.js
- test/integration/api/forms.js
> bug #126: prevent deleted forms from appearing in OpenRosa /formList.

- README.md
Updating the readme after a discussion in the Central Slack channel.
> improve: update information in readme about command line tools

- lib/model/query/forms.js
- test/integration/api/forms.js
* (we also coalesce xmlFormId in case name is blank).
> bug: forms are now supposed to be sorted ascending by name.

- lib/data/briefcase.js
- lib/resources/submissions.js
- test/integration/api/submissions.js
- test/unit/data/briefcase.js
* adds them at the very end.
* if we cannot find submitter information we omit the data for the row.
* resolves #132.
> new #132: include submitter id and name in .csv.zip export.

- lib/data/json.js
- test/unit/data/json.js
see commit messages; https://forum.opendatakit.org/t/odk-central-v0-1-alpha/13437/30
> patch collect datetime tz offset for odata

- lib/util/db.js
- lib/util/problem.js
- test/integration/api/projects.js
> Handle non-integer ID input

- .circleci/config.yml
- Makefile
- lib/bin/run-server.js
- lib/http/preprocessors.js
- lib/model/instance/project.js
- lib/model/instance/user.js
- lib/model/query/projects.js
- lib/resources/sessions.js
- lib/resources/users.js
- lib/task/task.js
- lib/util/sentry.js
- test/assertions.js
- test/integration/api/projects.js
- test/integration/setup.js
- test/integration/task/account.js
- test/unit/http/preprocessors.js
- test/util/crypto-mock.js
see commit messages.
roles-api is a pretty significant refactor of some areas and it's easier to rebase this on top of that than to base master and merge.
> miscellaneous fixes

- lib/model/instance/actee.js
- lib/model/instance/actor.js
- lib/model/instance/auth.js
- lib/model/query/actors.js
- lib/resources/projects.js
- lib/resources/users.js
- test/integration/api/projects.js
- test/integration/api/users.js
> return role verb information to the user

- lib/resources/assignments.js
- test/integration/api/assignments.js
> new: log audit actions for assignment changes (*/project, post/delete).

- lib/model/instance/form.js
- lib/model/query/forms.js
- lib/model/query/projects.js
- lib/util/db.js
- test/integration/api/forms.js
- test/integration/api/projects.js
- test/unit/util/db.js
~i think we can wait to merge this until after 0.5 because it effectively does nothing.~ HA HA HA
> cleanup and additional testing for project sandboxing correctness

- lib/data/json.js
- test/unit/data/json.js
> improve #213: include accuracy in geojson odata output as property.

- package-lock.json
- package.json
> build(deps): bump sentry from ~4 to ~5

- lib/data/attachments.js
- test/integration/other/encryption.js
- test/unit/data/attachments.js
* resolves https://github.com/opendatakit/central/issues/114
> bug c#114: strip .enc extension suffix when decrypting attachments.

- lib/http/endpoint.js
- test/unit/http/endpoint.js
it can hang for mysterious postgres reasons.
> don't run POST submissions.csv.zip in a transaction

- lib/outbound/odata.js
- test/unit/outbound/odata.js
> bug: odata edmx: double-denest would not step out context correctly.

- lib/model/instance/form.js
- lib/model/migrations/20200918-01-repair-publishedat-dates.js
- lib/model/query/forms.js
- lib/worker/form.js
- test/integration/other/transactions.js
- test/util/enketo.js
* actually all updates need for update, apparently, but we'll deal with
that later.
> bug: possible transaction override in enketo worker; needed for update.

- lib/outbound/mail.js
I have not run this myself, but I tried my darnedest to be careful.
Closes #292
> Add <a> tags to reset links

- lib/model/query/submissions.js
- lib/outbound/odata.js
- test/integration/api/odata.js
Additional fix to 9ae6b46fd4f82b435016e98e254488a3aef15ca1
> bug: filter by formid when getting OData count

- .gitignore
- docs/api.md
- lib/http/endpoint.js
- lib/resources/submissions.js
- test/integration/api/submissions.js
- test/unit/http/endpoint.js
Closes #313
I've put this on http://dev.central.getodk.org/ and verified it with Collect.
> Make submission HEAD response include OpenRosa headers and set max attachment size to 100MB

- lib/model/query/submission-defs.js
- lib/model/query/submissions.js
- lib/resources/submissions.js
- test/integration/api/submissions.js
i tried for a while to create a database index that would make createdAt not ~30% slower than id sort but it can't be done i think.
> file extension fix and createdAt sort change

- lib/bin/backup.js
- lib/task/task.js
> backups issues: don't send email if no config; email send didn't work

- lib/formats/odata.js
- lib/http/endpoint.js
- test/integration/api/odata.js
* so far as i can tell this should only ever be 403/404 but it should
work okay no matter what errors.
> improve: return xml odata endpoint errors in xml.

- docs/api.md
> Submission export parameter is attachments not media

- docs/api.md
- lib/bin/backup.js
- lib/model/frames.js
- lib/model/frames/config.js
- lib/model/migrations/20210716-01-config-value-jsonb.js
- lib/model/migrations/20210721-01-add-config-set-verb.js
- lib/model/query/audits.js
- lib/model/query/configs.js
- lib/resources/backup.js
- lib/resources/config.js
- lib/task/config.js
- lib/task/google.js
- test/assertions.js
- test/integration/api/audits.js
- test/integration/api/config.js
- test/integration/task/config.js
- test/unit/model/frames/config.js
- test/util/util.js
This PR is very much a work in progress! But I have a few questions, so I thought I'd push what I have so that we could discuss with a little context. I'll add a few specific questions below.
> new: add endpoints for configuring analytics.

- lib/external/slonik.js
- lib/model/migrate.js
- lib/util/db.js
- lib/util/problem.js
- test/unit/util/db.js
> improve #377: support more ways of connecting to the database.

- package-lock.json
- package.json
- test/unit/http/endpoint.js
* also fix a test that i thought broke w node 16 but i guess somehow
also breaks sooner with some dep combinations?
> deps: update deps for security.

- lib/data/submission.js
- test/unit/data/submission.js
* need to fill slots before ejecting good matches.
> bug: diff algo could fail to knock out enough bad matches, give npe.

- package-lock.json
- package.json
* also upgrade some test deps for security issues.
> deps: upgrade prompt to remove warning (thanks @x3ro for identifying).

- .eslintrc.json
- lib/data/briefcase.js
- lib/data/schema.js
- lib/data/submission.js
- lib/model/frames/form.js
- lib/model/migrations/20211008-01-track-select-many-options.js
- lib/model/query/forms.js
- lib/model/query/submissions.js
- lib/resources/submissions.js
- lib/util/db.js
- lib/worker/jobs.js
- lib/worker/submission.js
- package.json
- test/assertions.js
- test/data/xml.js
- test/integration/api/forms.js
- test/integration/api/submissions.js
- test/integration/other/select-many.js
- test/integration/setup.js
- test/unit/data/briefcase.js
- test/unit/data/schema.js
- test/unit/data/submission.js
> new export options for v1.4

- lib/worker/worker.js
- test/integration/worker/worker.js
oops, turns out this is why it wasn't merged yet.
> improve: add sentry reporting to more error paths in worker handler.

- lib/model/migrations/20220121-02-purge-deleted-forms.js
- lib/model/query/forms.js
- package-lock.json
- package.json
* otherwise the workers try to pick it up.
* maybe the workers should be smarter.
> bug: need to flag all upgrade-form.purged audits as processed.

- docs/api.md
Making this a separate PR so it's easier to handle with all the other open backend PRs
> Block 14 docs (deleting/restoring forms, etc.)

- config/default.json
- lib/data/analytics.js
- lib/model/query/analytics.js
- test/integration/other/analytics-queries.js
New metrics:
1. Project has a description (1/0)
2. Number of Open Forms
3. Number of Closing Forms
4. Number of Closed Forms
5. Server uses an external database (1/0)
> New metrics for Block 15

- docs/api.md
Related Forum topic: https://forum.getodk.org/t/odk-central-api-documentation-odata-comparison-operators/38029
> Make changes to API docs about OData

- lib/http/middleware.js
Feel free to merge this in a few decades :smile:
> Support API versions greater than 10

- Makefile
- lib/bin/check-migrations.js
- lib/bin/run-migrations.js
Precursor to fixing https://github.com/getodk/central-backend/issues/509
> migrations: move scripts to lib/bin

- Makefile
> Makefile: remove targets which no longer work

- .circleci/config.yml
- package.json
> Update Node to 14.19.3 to match production

- lib/resources/submissions.js
- test/integration/api/submissions.js
Address case 21 of https://github.com/getodk/central-backend/issues/469#issuecomment-1184672088
TODO:
> Allow submission edits on closed forms

- test/integration/api/submissions.js
- test/integration/other/encryption.js
- test/util/zip.js
> Catch assertion failures in integration tests using zipStreamToFiles()

- lib/util/db.js
- lib/util/problem.js
- test/integration/api/projects.js
> Return Problem response if user specifies too large number

- lib/model/query/comments.js
- test/integration/api/comments.js
- test/integration/api/submissions.js
> bugfix: comment submission response format is bizarre

- .circleci/initdb.js
- lib/model/container.js
- lib/model/frames/dataset.js
- lib/model/migrations/20220803-01-create-entities-schema.js
- lib/model/query/datasets.js
- test/integration/model/query/dataset.js
Added an integration test
As per several discussions and `Entities Implementation` document. This is first draft, things will change according to the feedback.
None
No
> Added dataset schema, database operation for creating dataset, properties and field mapping

- .circleci/config.yml
- lib/bin/check-file-headers.js
- lib/bin/check-migrations.js
- lib/bin/enforce-node-version.js
- lib/bin/purge-forms.js
- lib/bin/run-migrations.js
- lib/external/sentry.js
- lib/task/purge.js
- lib/util/quarantine/oaep.js
I noticed that a few new files are missing file headers. I think it's easy to miss those, so I wrote a small script to check that in CircleCI.
The first version of the script didn't specify anything for `skip`. For each file that the script listed, I either added a file header to the file or added the file to `skip`. I verified that when the script lists files, it exits with an exit code of 1.
We do other checks in CircleCI, so this seemed like a potentially useful addition.
Not user-facing.
No change required.
> Check file headers in CircleCI

- test/integration/setup.js
Closes #582
@ktuite if you still have a bad database, can you confirm this PR fixes your issue?
I didn't find clear info on what's going on here, but there are hints in this Reddit thread: https://old.reddit.com/r/PostgreSQL/comments/pxqe18/deleted_by_user/hepdosb/
> tests: reduce scope of knex migrator connection

- lib/external/sentry.js
Potential fix for https://github.com/getodk/central-backend/issues/584
> Update Sentry ingestion URL

- lib/external/sentry.js
Ref https://github.com/getodk/central-backend/issues/521
> sentry: set 'user' to differntiate deployments

- lib/external/sentry.js
Related to: https://github.com/getodk/central-backend/issues/521, https://github.com/getodk/central-backend/issues/547
Ref https://github.com/getodk/central/pull/316#issuecomment-1240910206
> Set sentry environment  release branch

- lib/model/query/datasets.js
corrected table name in sql to fix integration tests
> Fixes failing tests

- lib/http/endpoint.js
- test/unit/http/endpoint.js
> defaultErrorWriter: do not choke if error missing

- .gitignore
- with-pgbadger
Usage:
```bash
./with-pgbadger make test
```
etc.
> Generate pgbadger report while running something else

- docs/api.md
Fixing a few small omissions I noticed.
> Update docs for OData `$select`

- lib/bin/check-file-headers.js
Depends on: https://github.com/getodk/central-backend/pull/619
> check-file-headers: add --fix

- lib/model/query/datasets.js
- lib/model/query/entities.js
- lib/resources/forms.js
- test/integration/api/datasets.js
- test/integration/api/forms/datasets.js
- Updated `GET attachment/:name` endpoint to return dataset csv if it is linked
- Fixed dataset-diff SQL to include projectId
> new: download dataset csv as attachment

- lib/model/query/form-attachments.js
- test/integration/api/datasets.js
- Autolink attachments to dataset if name is same
> new: autolink attachment to dataset if name matches

- lib/model/migrations/20221114-01-explict-dataset-publish.js
- lib/model/query/audits.js
- lib/model/query/datasets.js
- lib/model/query/forms.js
- test/integration/api/datasets.js
Closes #666 
- Added integration tests
- Performed manual testing with frontend
Previous solution of having implicit status for dataset and its properties was not working, especially when form gets purged
I guess whole dataset/entities feature should be tested
NA
> fixes #666: dataset and property has publishedAt

- lib/resources/forms.js
- test/assertions.js
- test/integration/api/datasets.js
- test/integration/setup.js
> Make changes related to linking an attachment to a dataset

- lib/data/analytics.js
- lib/model/query/analytics.js
- test/data/xml.js
- test/integration/other/analytics-queries.js
Closes #682
Updated XLSForm: [odk-analytics.xlsx](https://github.com/getodk/central-backend/files/10105074/odk-analytics.xlsx)
- Added integration tests
- Tried pushing analytics to https://test.getodk.cloud/#/projects/390/forms/odk-analytics
- Followed existing code pattern
- Verifying analytics on data server should be sufficient
NA
> Analytics for dataset/entities

- config/default.json
updated analytics form version in default config
> updated analytics form version in default config

- benchmarker/package-lock.json
- benchmarker/package.json
Closes https://github.com/getodk/central-backend/security/dependabot/16
> benchmarker: add volta & update dependencies

- docs/api.md
Update API doc to reflect dataset / entities related changes.
You can view the draft version of the document at https://centralbackendsk.docs.apiary.io/#introduction/changelog
> updated API.md to reflect dataset/entities changes

- lib/data/odata.js
- lib/formats/odata.js
- test/integration/api/odata.js
Closes #496 and #607
- Integration Test
- Manually tested in Excel and PowerBI
> Support repeat names that are not valid OData identifiers

- lib/model/query/forms.js
I wanted to pull this out into a separate PR so the following PR #725 is a bit cleaner and the diff more readable. 
tests all still pass.
easier to read and review!
n/a
n/a
> Refactor createNew and createVersion in Forms with async/await

- lib/model/query/forms.js
- lib/resources/forms.js
- test/integration/api/forms/forms.js
- test/integration/other/encryption.js
Ignore structural change warning on form publish
Added a test
> Ignore structural change warning on form publish

- test/integration/api/users.js
I was staring at this test as part of #752, and I wanted to add one more assertion. The test title is "should not accept and hash blank passwords". The test specifies a blank password to POST /v1/users, then verifies that even though the response is a 200, a blank password cannot be used to create a session. However, that last part is more a consequence of how the session endpoint is set up. We already have a test that the session endpoint returns an error response if `isBlank()` returns `true` for the password:
https://github.com/getodk/central-backend/blob/50894bdc4c8e60970af913da744138b1e718efe9/lib/resources/sessions.js#L18-L22
https://github.com/getodk/central-backend/blob/50894bdc4c8e60970af913da744138b1e718efe9/test/integration/api/sessions.js#L79-L82
To test that Backend truly …
> Update test to double-check that blank password is not hashed

- lib/model/query/projects.js
- test/integration/api/projects.js
Closes #745 
Added integration test
> fixes #745: exclude unpublished datasets from the count

- .github/PULL_REQUEST_TEMPLATE.md
Making a similar change as in getodk/central-frontend#738.
> Update text in PR template about code from external sources

- lib/model/query/datasets.js
- test/integration/api/datasets.js
Closes #777
Added an integration test
This is cleanest thing to do. Modifying ON CONFLICT DO UPDATE is messy.
None
None
> fix: update the publishAt value if it is null

- .circleci/config.yml
- .github/workflows/soak-test.yml
- package.json
- soak-tester/package.json
Related: https://github.com/getodk/central/pull/390
NA
NA
NA
NA
> upgrade node version to 16.19.1

- lib/model/query/forms.js
- lib/worker/form.js
- test/.eslintrc.js
- test/integration/api/forms/draft.js
- test/integration/api/forms/forms.js
- test/integration/api/projects.js
- test/integration/api/submissions.js
- test/integration/other/transactions.js
- test/integration/setup.js
- test/util/enketo.js
> Speed up acquisition of enketoId in two cases

- docs/api.md
Closes #785 
API Docs update
That's what it is!
> API docs about OData Dataset Service

- lib/model/knexfile.js
This is a noop because it's in a comment.
> Upgrade code comment to use docker compose v2

- lib/resources/entities.js
- test/integration/api/entities.js
Closes #834 
Tests
Will help with continuity as we develop this part of the API.
Will be mentioned in docs
> Added force=true flag to entites PATCH endpoint

- lib/model/query/entities.js
- lib/resources/entities.js
- test/integration/api/entities.js
Closes #803 
No
We have a separate PR for that
> new: added DELETE api for entities

- lib/model/frames.js
- lib/model/migrations/20230414-01-remove-user-mfa-secret.js
- test/integration/api/audits.js
- test/integration/api/users.js
It looks like this prop was added speculatively in 2017 (938c75a43374878342593553ea324f53b90cbfcc), and has been unused since then.
> User: remove unused prop 'mfaSecret'

- lib/bin/check-file-headers.js
- package-lock.json
- package.json
- pm2.config.js
See getodk/central#336
Tested locally
NA
None, we have a circle CI step in Central repository to verify number of pm2 instances.
No
> added pm2 as dependency

- lib/model/query/audits.js
- lib/model/query/entities.js
- lib/model/query/submissions.js
- lib/resources/entities.js
- test/data/xml.js
- test/integration/api/entities.js
> new: GET /entities/:uuid/audits

- lib/model/query/entities.js
- test/integration/api/entities.js
> Make entity update audit details consistent with create details

- lib/model/query/audits.js
- test/integration/api/audits.js
Closes #821 
Tests
Need to update docs
> Update audit log to filter and expose new entity actions

- lib/data/entity.js
- test/integration/api/datasets.js
- test/integration/api/entities.js
- test/unit/data/entity.js
Closes #856 
Moves `label` up a level.  Changed the code, changed some tests.
> Move label in entity PATCH

- lib/model/query/entities.js
- test/integration/api/entities.js
Related to #858 
Integration Tests
No
No
No
> fixes #858: Entity frame should be reinstantiated

- lib/model/frames/submission.js
- lib/model/query/datasets.js
- lib/model/query/entities.js
- lib/model/query/submissions.js
- test/integration/api/datasets.js
- test/integration/worker/entity.js
> fixes 880: exclude draft and deleted submissions from entity processing

- lib/model/query/datasets.js
- test/data/xml.js
- test/integration/worker/entity.js
- Included hasIssues submissions for auto-conversion
- Added integration test
> fixes: include hasIssues submissions for auto-conversion

- docs/api.md
- lib/data/entity.js
- lib/formats/odata.js
- test/integration/api/odata-entities.js
- test/unit/data/entity.js
> fix: remove name from Entity OData

- lib/model/migrations/20230518-01-add-entity-index-to-audits.js
- lib/model/query/audits.js
> Add index to audits details->entityId

- lib/model/query/forms.js
- test/integration/api/projects.js
Closes item # 2 in QA's regression report.
Integration test
Not much changed, just set the value of `duplicating` to true
No
No
> skip checking structure warnings in forms when encrypting a project

- lib/data/entity.js
- lib/model/query/entities.js
- lib/util/problem.js
- test/integration/api/datasets.js
- test/integration/api/entities.js
- test/integration/worker/entity.js
- test/unit/data/entity.js
Closes #854
I tried to use specific "Problem" wherever I could and used `invalidEntity` as fall back option
No
No
> use specific problems instead of entityViolation and invalidEntity

- lib/http/preprocessors.js
- lib/http/service.js
- lib/resources/entities.js
- lib/resources/sessions.js
- lib/resources/submissions.js
Closes #896 
I have created a preprocessor instead of adding condition all over the place
Low risk
None.
> fixes 896: don't assume user agent to be always present

- docs/api.md
Updated API docs with the high level API specs
Documentation can be viewed at : https://centralbackendsk.docs.apiary.io/#
> Entity APIs specification

- lib/formats/odata.js
- test/integration/api/odata.js
- test/unit/formats/odata.js
Closes #722 
Added integration test
Manually verified via Excel and checked logs 
NA
NA
NA
> enhances #722: add ability to select parentID

- docs/database.md
> Enhance #912: Updated ERD to reflect last 6 months of changes

- test/integration/api/users.js
This feature looks like it's outlasted the "initial release".
> test/users: remove outdated TODO

- .circleci/config.yml
- .github/workflows/soak-test.yml
- package-lock.json
- package.json
- soak-tester/package.json
Node 16 EOL is September: https://nodejs.dev/en/about/releases/
> Update to node 18

- README.md
> Update readme for Node 18

- lib/model/migrations/20230802-01-delete-orphan-submissions.js
- lib/model/query/submissions.js
- lib/resources/projects.js
- test/integration/api/projects.js
- test/integration/other/migrations.js
Closes #911
Integration and manual test
Please see the discussion on the issue.
None
NA
> fixes 911: delete draft submission on project encryption

- lib/model/migrations/20230818-01-remove-schemaId-from-dsPropertyFields.js
- lib/model/query/datasets.js
> Remove schemaId from dsProperyFields table

- lib/model/query/form-attachments.js
- test/integration/api/datasets.js
Closes #673
Integration tests and manually verified it
NA
NA
NA
> fixes #673: dataset named itemsets and external choices form is uploaded

- docs/api.yaml
Progress towards https://github.com/getodk/central/issues/466
Ran it with https://github.com/getodk/docs/pull/1601/files
I tried a few different ways of presenting this information. I landed on a warning box because it's eye-catching and can be used in different contexts. It also feels appropriate: we want to warn users that they might have seen another word for this concept.
Docs-only.
That's what this is!
> Api entity lists

- lib/model/query/forms.js
> Fix spelling

- lib/formats/mail.js
- test/integration/api/users.js
Closes https://github.com/getodk/central/issues/481
Visual inspection of strings only.
Smallest change that supports both the owner of the account and an admin making the change.
No regression risk.
No.
> Update email text because admins can make changes

- docs/api.yaml
- Basic Auth not available when SSO is enable
- ?datasets=true for project listing
- Version number for Entities
Closes #949
> fixes #949: Updated API doc for the changes done in 2023.4

- lib/data/entity.js
- test/integration/api/datasets.js
Closes getodk/central#501
Tests
> rename version column in dataset attachemnt to __version

- lib/http/endpoint.js
- lib/util/html.js
Ref https://github.com/getodk/central-backend/pull/981#discussion_r1335236657
> OIDC: remove frontend styling from error page

- lib/data/entity.js
- lib/model/query/entities.js
- lib/worker/entity.js
- lib/worker/jobs.js
- test/data/xml.js
- test/integration/worker/entity.js
- test/unit/data/entity.js
Closes https://github.com/getodk/central/issues/509
This uses the existing submission parsing and existing update entity via PATCH infrastructure to update entities from submissions. 
There's more to do but I thought it might make sense to merge something basic in early.
Related issues that could be finished while other work starts in parallel
- https://github.com/getodk/central/issues/510
- https://github.com/getodk/central/issues/514
I'm trying to get something in place so other improvements (conflicts, merging strategies) can be worked on asap.
> Exploratory PR for starting to update entities from submissions

- lib/model/migrations/20231002-01-add-conflict-details.js
- lib/model/query/entities.js
Adds new columns to record conflict information on Entity
> Add columns to track entity conflict

- docs/api.yaml
- lib/data/entity.js
- test/integration/api/odata-entities.js
- test/unit/data/entity.js
Part of getodk/central#503
Added integration test
Yes, updated
> Added conflict property in Entity Odata

- docs/api.yaml
Includes changes done to fix extended responses
> Copied API doc from getodk-docs repo

- docs/api.yaml
- lib/model/frames/dataset.js
- lib/model/query/datasets.js
- test/assertions.js
- test/integration/api/datasets.js
- test/integration/api/projects.js
- test/integration/fixtures/scenarios.js
- test/integration/setup.js
Part of getodk/central#500
Test
Yes, updated
> Return conflicts count in Project and Dataset GET APIs

- lib/resources/datasets.js
- lib/util/db.js
- test/integration/api/datasets.js
Closes getodk/central#521.
Added integration tests
> Add filtering for entity csv

- lib/data/entity.js
- lib/model/query/entities.js
- test/unit/data/entity.js
> Return new properties in serverDiff and baseDiff

- lib/model/frames/entity.js
- lib/model/query/entities.js
- test/integration/api/entities.js
> Fixed: missing label in dataReceived

- oidc-dev/fake-oidc-server/.eslintrc.cjs
- oidc-dev/playwright-tests/.eslintrc.js
> eslint: disable import/no-unresolved in ./oidc-dev

- lib/model/frames/entity.js
- lib/model/query/entities.js
- lib/resources/entities.js
- test/integration/api/audits.js
- test/integration/api/entities.js
- Fixes: it should not resolve if resolve flag is not true
- Fixes: set updatedAt on resolve conflict
- Check for If-Match before resolve conflict
> Minor fixes for Resolve Conflict

- test/integration/api/entities.js
> Fix parallel update test - added audit logs

- lib/resources/entities.js
- test/integration/api/audits.js
- test/integration/api/entities.js
Backend part of https://github.com/getodk/central-backend/issues/1041, see discussion there
tests, trying with complimentary frontend PR
YES NEEDS DOCS CHANGES
> Use baseVersion query param instead of etag/if-match for entity PATCH

- package-lock.json
Closes https://github.com/getodk/central-backend/issues/1006
This updates `bcrypt` from `5.0.1` to `5.1.1`.
This PR also resolves the **critical** vulnerability:
```
@babel/traverse  <7.23.2
Severity: critical
Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code - https://github.com/advisories/GHSA-67hx-6x53-jw92
fix available via `npm audit fix`
node_modules/@babel/traverse
```
This PR doesn't change this other set of issues with `axios`. I think we should wait for `pm2` or something else to change, because otherwise this fix looks like it rolls all the way back to an old pm2 (or pm2/js-api) when we are currently on `pm2@5.3.0`.
```
axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - …
```
> Upgrade backend dependencies

- CONTRIBUTING.md
- README.md
- docs/api.yaml
Closes https://github.com/getodk/central-backend/issues/1051
I've gone through these pretty throughly - fixing some links in the docs themselves, adding more details, and testing the endpoints with pyodk to make sure everything matches and makes sense/can be explained.
> Review and polish of 2023.5 API docs

- .github/workflows/soak-test.yml
This changes the GitHub Actions config file soak-test.yml to match the pattern of other workflow yaml files.  This also removes the build (1x1) build matrix, and consequently makes the GitHub Actions GUI simpler to navigate for this workflow.
> ci: soak-test: standardise format

- lib/model/migrations/20240215-01-entity-delete-verb.js
- lib/model/migrations/20240215-02-dedupe-verbs.js
- lib/resources/entities.js
- test/integration/api/entities.js
- test/integration/api/projects.js
- test/integration/other/migrations.js
Closes getodk/central#597.
New test.
I tried to match previous migrations involving role verbs.
> Add entity.delete verb

- Makefile
> Update BCRYPT env variable for test-fast

- docs/api.yaml
Small edits to hopefully make the section easier to read.
> Simplify OData docs

- lib/http/endpoint.js
- test/unit/http/endpoint.js
> Don't leak error details to client

- docs/api.yaml
> Fix API docs for adding property

- lib/model/query/datasets.js
- test/integration/api/datasets.js
Closes getodk/central#643.
New test.
> Exclude deleted forms from linkedForms

- lib/model/query/submissions.js
- lib/util/db.js
- test/data/xml.js
- test/integration/api/odata.js
- test/integration/other/migrations.js
- test/unit/util/db.js
Closes getodk/central#608.
New tests.
> Add filters when selecting $skiptoken submission

- docs/api.yaml
> Fix endpoint path in API docs

- lib/model/query/blobs.js
- test/integration/task/s3.js
Closes https://github.com/getodk/central/issues/704
> s3: add audit logging

- .circleci/config.yml
- .github/workflows/oidc-e2e.yml
- .github/workflows/oidc-integration.yml
- .github/workflows/s3-e2e.yml
- .github/workflows/soak-test.yml
- .github/workflows/standard-suite.yml
- package.json
Closes #
Ran locally
Unifies versions with ops which just got upgraded
Low risk
No
> Set node version to 20.17.0

- test/integration/api/offline-entities.js
Test case for scenario identified by Matt: https://staging.getodk.cloud/#/projects/95/entity-lists/people/entities/e7fe158b-0e40-493d-a078-896f7470eb44
In this screenshot of staging before the bug was fixed, the server base version of the last version of the entity is v2 when it should be v3 (the previous version in the same branch): 
The base version appears to be computed correctly now, but I verified that it was wrong like the example above on an earlier version of the code.
> Additional offline entity test scenario

- lib/util/db.js
This should help explain how odata $skiptokens are defined and used in this codebase.
> OData $skiptoken: add inline docs

- lib/bin/repl.js
Dev dependencies are not available in production environments.
Closes #1227
> bin/repl: handle missing should dependency

- lib/data/odata-filter.js
- test/assertions.js
- test/unit/data/odata-filter.js
> odata-filter: handle unsupported functions

- lib/model/query/submissions.js
- lib/util/db.js
- test/unit/util/db.js
Related:
* https://github.com/getodk/central-backend/pull/1238
* https://github.com/getodk/central-backend/pull/1239
> db-util: use sql.*() instead of slonik-sql-tag-raw

- lib/model/frame.js
- test/unit/model/frame.js
Related:
* https://github.com/getodk/central-backend/pull/1238
* https://github.com/getodk/central-backend/pull/1240
> frame: use sql.*() instead of slonik-sql-tag-raw

- lib/data/odata-filter.js
- test/unit/data/odata-filter.js
Related:
* https://github.com/getodk/central-backend/pull/1239
* https://github.com/getodk/central-backend/pull/1240
* https://github.com/getodk/central-backend/pull/1241
* https://github.com/getodk/central-backend/pull/1242
> odata-filter: use sql.identifier() instead of slonik-sql-tag-raw

- lib/model/query/assignments.js
- lib/model/query/audits.js
- lib/model/query/datasets.js
- lib/model/query/entities.js
- lib/model/query/field-keys.js
- lib/model/query/forms.js
- lib/model/query/projects.js
- lib/model/query/public-links.js
- lib/model/query/submissions.js
- lib/model/query/users.js
- lib/util/db.js
- test/unit/util/db.js
Prevent collisions with ramda's equals() fn.
> Rename utils/db's equals() to sqlEquals()

- lib/data/odata-filter.js
- test/unit/data/odata-filter.js
* https://github.com/getodk/central-backend/pull/1238
* https://github.com/getodk/central-backend/pull/1239
* https://github.com/getodk/central-backend/pull/1240
* https://github.com/getodk/central-backend/pull/1241
Either:
> odata-filter: replace slonik-sql-tag-raw with hardcoded operators

- lib/data/submission.js
- lib/model/query/submissions.js
- lib/util/db.js
- package-lock.json
- package.json
* https://github.com/getodk/central-backend/pull/1238
* https://github.com/getodk/central-backend/pull/1239
* https://github.com/getodk/central-backend/pull/1240
* https://github.com/getodk/central-backend/pull/1242
> export/submissions: remove raw SQL modification hack

- lib/http/preprocessors.js
- lib/model/query/sessions.js
- lib/util/crypto.js
- test/unit/util/crypto.js
> Sessions.getByBearerToken(): check format before hitting db

- Makefile
> Organize Makefile into sections

- test/unit/http/preprocessors.js
Related to https://github.com/getodk/central-backend/pull/1269#discussion_r1835442470
> test/preprocessors: fix test titles

- test/unit/http/middleware.js
> test/middleware: add missing import: should

- test/integration/setup.js
- test/unit/data/attachments.js
- test/unit/data/briefcase.js
- test/unit/util/zip.js
- test/util/zip.js
Re https://github.com/getodk/central-backend/pull/1310#discussion_r1870563674
> lint: resolve keyword-spacing issues

- lib/task/task.js
An unused property was noticed while working on #1303.
Ran tests
Simplifies code.
No effect.
No.
> task: remove unused noop prop

- lib/task/s3.js
Closes #812
Tested manually.
Require pgrowlocks extension?  This was initially included, but removed by popular request: https://github.com/getodk/central-backend/pull/1190
Hopefully fixes s3 upload-pending for them.
I don't think this relates to the API.
> bin/s3/upload-pending: handle missing pgrowlocks extension

- lib/http/service.js
- lib/util/problem.js
- test/integration/api/entities.js
- test/integration/other/body-parser.js
Closes #788
Added tests.
Follows the pattern of the existing code.
No likely effect.
No.
> Handle additional bodyParser errors

- .github/workflows/oidc-e2e.yml
- .github/workflows/oidc-integration.yml
- .github/workflows/s3-e2e.yml
- .github/workflows/standard-e2e.yml
- .github/workflows/standard-suite.yml
Closes #1308
Full discussion at #1315
> ci: run github actions on pull requests

- test/e2e/util/api.js
Used in debugging https://github.com/getodk/central-backend/pull/1353
> test/e2e/api: include response status text in errors if no response body

- test/db-migrations/utils.js
Advantages of strict mode:
* should have less surprises - uses === instead of ==
* produces more helpful assertion failure messages
See: https://nodejs.org/api/assert.html#strict-assertion-mode
* CI
* tested change while working on https://github.com/getodk/central-backend/pull/1355
No other approaches considered - this one seems simple.
Should not affect users; should make futures tests more robust.
No.
> test/db-migrations: use strict assertions

- test/db-migrations/utils.js
CI, tested locally & while working on https://github.com/getodk/central-backend/pull/1355
Makes code clearer to read.  Could be compared to the existing code.
No effect.
No.
> test/db-migrations: assertRowsMatch(): use clearer var name

- package-lock.json
- package.json
Closes #1376
CI
It needs to be done eventually.  Supporting explicit S3 regions is also added.  See https://github.com/getodk/central/issues/846
This might affect behaviour of s3 users.
No.
> s3: update minio dependency to v8

- test/integration/api/oidc.js
Preliminary work for #1230
There's a test.
None,
It should not, it's just a test.
No.
> oidc/login: add integration test

- docs/api.yaml
- lib/model/frames/dataset.js
- lib/model/query/datasets.js
- test/assertions.js
- test/integration/api/datasets.js
Closes getodk/central#803
Updated tests
Follows the existing pattern
No
Done
> Return lastUpdate for the dataset endpoints

- lib/model/query/user-preferences.js
Also use existing return value from postgres wire protocol instead of generating an extra value.
Ran existing tests.
Seems more concise and obvious than the existing code.
Should not affect users.
No.
> UserPreferences: simplify DELETE queries

- lib/bin/run-server.js
- lib/external/sentry.js
- lib/http/service.js
- lib/util/default-container.js
- package-lock.json
- package.json
- test/integration/setup.js
Closes https://github.com/getodk/central/issues/877
~Should this be using the `config` package & `default.external.sentry`?  Similar question for https://github.com/getodk/central-backend/pull/637 and getodk/central-backend#601.~
Tested locally with dev config.
> Sentry: enable request performance tracing

- test/integration/api/user-preferences.js
Use ES2015 computed property names instead of `Object.assign()`.
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#computed_property_names
Existing tests.
It seems much more readable.
No effect.
No.
> test/user-prferences: simplify test expectations

- lib/http/preprocessors.js
- lib/resources/sessions.js
- test/integration/api/forms/draft.js
- test/integration/api/sessions.js
Modified tests, added a test and verify manual with Central frontend.
Overall reason for this change was discussed internally. Code change is simple and fulfills the requirement.
No
NA
> Modify restore endpoint

- lib/data/odata-filter.js
- test/unit/data/odata-filter.js
Preparing https://github.com/getodk/central-backend/pull/1521 for the point release.
Source and Target branches `hotfix/v2025.1.3` are created from `v2025.1.0` tag. 742cd4fd8303c98b555e64ce3b87fa7fd9b873ce is cherry-picked onto the source branch.
> Improve search/filter performance. (#1521)

- lib/bin/log-upgrade.js
- lib/task/log-upgrade.js
- test/integration/task/log-upgrade.js
Closes https://github.com/getodk/central/issues/971
> Log when server upgrades and version changes

- .circleci/config.yml
- .github/workflows/db-migrations.yml
- .github/workflows/oidc-e2e.yml
- .github/workflows/oidc-integration.yml
- .github/workflows/s3-e2e.yml
- .github/workflows/soak-test.yml
- .github/workflows/standard-e2e.yml
- .github/workflows/standard-suite.yml
- package-lock.json
- package.json
Closes https://github.com/getodk/central/issues/976
```
braces  <3.0.3
Severity: high
Uncontrolled resource consumption in braces - https://github.com/advisories/GHSA-grv7-fg5c-xmjg
fix available via `npm audit fix --force`
Will install knex@3.1.0, which is a breaking change
node_modules/findup-sync/node_modules/braces
micromatch  <=4.0.7
Depends on vulnerable versions of braces
node_modules/findup-sync/node_modules/micromatch
findup-sync  0.4.0 - 3.0.0
Depends on vulnerable versions of micromatch
node_modules/findup-sync
liftoff  2.2.3 - 3.1.0
Depends on vulnerable versions of findup-sync
node_modules/liftoff
knex  <=2.3.0
Depends on vulnerable versions of liftoff
node_modules/knex
multer  1.4.4-lts.1 - 2.0.0
Severity: high
Multer vulnerable to Denial of Service via unhandled exception - …
```
> Upgrade deps in package-lock for 2025.2

- lib/model/migrations/20250611-01-owner-only-index.js
- lib/model/query/entities.js
- lib/model/query/form-attachments.js
- lib/resources/forms.js
- lib/util/db.js
- test/assertions.js
- test/integration/api/datasets.js
- test/unit/util/db.js
Closes getodk/central#1137.
New tests.
I've added some notes about my decisions in line comments.
> Update OpenRosa hash to account for ownerOnly

- test/integration/other/transactions.js
If there is a failure in the test, e.g. the final assertion fails, the deadlock relief code will never run, resulting in a non-terminating test.
This can be demonstrated by running the following with `make test-integration` on `master`:
```diff
--- a/test/integration/other/transactions.js
+++ b/test/integration/other/transactions.js
@@ -39,7 +39,7 @@ describe('transaction integration', () => {
const sometime = (ms) => new Promise((done) => { setTimeout(done, ms); });
describe('enketo worker transaction', () => {
-  it('should not allow a write conflict @slow', testContainerFullTrx(async (container) => {
+  it.only('should not allow a write conflict @slow', testContainerFullTrx(async (container) => {
const { Audits, Forms, oneFirst } = container;
const simple = (await …
```
> test/transactions: fix test cleanup on failure

- lib/external/sentry.js
This integration should help to reduce duplicate errors sent to Sentry.
Ref https://github.com/getodk/central/issues/1191
```sh
$ NODE_CONFIG='
{
"default": {
"external": {
"sentry": {
"project": "1298632",
"key":"3cf75f54983e473da6bd07daddf0d2ee",
"orgSubdomain":"o130137"
}
}
}
}
' node -e '
console.log(
require("./lib/external/sentry").Sentry.getClient()._options.integrations
.find(it => it.name === "Dedupe") ? "enabled" : "not enabled"
)
'
enabled
```
No other approaches were considered.
Should not noticeably affect users.  Might have slight performance implications when `Sentry.captureException()` is called.
No.
> Sentry: enable Dedupe integration

- .github/workflows/standard-suite.yml
- docs/api.yaml
- package-lock.json
- package.json
Closes https://github.com/getodk/central/issues/1220
New CI step.
Should prevent broken/non-standard YAML from being merged to `master`.
Should help stop breaking OpenAPI docs in future.
No.
https://github.com/getodk/central-backend/actions/runs/17038971002/job/48297932338?pr=1591
```
2025-08-18T11:15:41.1098176Z [36;1mnpx --no swagger-cli validate docs/api.yaml[0m
2025-08-18T11:15:41.1139239Z shell: /usr/bin/bash -e {0}
2025-08-18T11:15:41.1139620Z ##[endgroup]
2025-08-18T11:15:41.5168721Z Error parsing /home/runner/work/central-backend/central-backend/docs/api.yaml: duplicated mapping key (1676:11)
2025-08-18T11:15:41.5169783Z 
2025-08-18T11:15:41.5169958Z  1673 |               schema:
2025-08-18T11:15:41.5170463Z  1674 |                 $ref: '#/components/sche ... …
```
> ci: validate docs/api.yaml
